### PR TITLE
modify and add testcase for rvitals for issue:3062

### PR DESCRIPTION
**Pull request by junxiawang**
1.
add test case for rvitals against openbmc #3062

Add test case for rvitals against openbmc.
what to do cases list:
Cases need to refine:
rvitals_temp
rvitals_power
rvitals_voltage
rvitals_noderange_err
rvitals_all
Cases need to add:
rvitals_h
rvitals_v
rvitals_wattage
rvitals_fanspeed
rvitals_leds
rvitals_errorcommand
2.
Delete cases1 and cases0 could cover cases1
what to do cases list:
Cases need to refine:
rvitals_temp(PPC64LE)
rvitals_disktemp(PPE64LE)
rvitals_cputemp(PPC64LE)
rvitals_voltage(PPC64LE)
rvitals_all(PPC64LE)
rvitals_noderange_err(PPEC64LE)

### CODE REVIEW

**Comment by gurevichmark** [comment]
@junxiawang Just got this information today - 
The Witherspoon machines will only return 4 vitals categories: temperature, fan speed, power and voltage.
So no need for led or wattage testcases.

**Comment by junxiawang** [comment]
@gurevichmark Okay will ask weihua to add only run 4 vitals categories testcase in bunlde.And other test cases will be left for other machines' test.

**Comment by gurevichmark** [comment]
Looks ok to me.
@xuweibj you can merge it, after you review it.

**Comment by xuweibj** [comment]
Looks good to me.

**Pull request merged**
