### PR TITLE
Add ipmi_si module to be able to run bmcsetup manually

### PR DESCRIPTION
**Pull request by Obihoernchen**
Just a quick addition for easier debugging.

### CODE REVIEW

**Comment by gurevichmark** [comment]
@Obihoernchen 
Is the idea to be able to run `bmcsetup` from the command line when the node is running genesis or on OS provisioned compute node ?

**Comment by Obihoernchen** [comment]
@gurevichmark I think my use case was to run bmcsetup via updatenode -P on a OS provisioned node manually which mitght not load ipmi_si by default.

**Comment by gurevichmark** [comment]
@Obihoernchen 
Looking at `xCAT-genesis-scripts/usr/bin/doxcat` we do `modprobe ipmi_si` when booting with genesis, but only for `x86`.
For `ppc64` we do `modprobe ipmi_powernv` instead. Should your changes to `bmcsetup` script do the same ?

**Comment by Obihoernchen** [comment]
@gurevichmark good point. Good idea I guess. I don't have a ppc64 node for testing though.
Changed.

**Review by gurevichmark — APPROVED** [review]

**Review by besawn — APPROVED** [review]

**Pull request merged**
