### PR TITLE
Update features.rst

### PR DESCRIPTION
**Pull request by andreas-h**
fix rst error

### CODE REVIEW

**Comment by daniceexi** [comment]
@andreas-h Could you sign the CLA so that xCAT can accept your contribution? http://xcat-docs.readthedocs.io/en/stable/developers/license/contributors.html

BTW, please check whether your company has signed the CCLA with xCAT like IBM. If so, you don't need to sign again.

**Comment by andreas-h** [comment]
DONE, sent it to the xcat-legal address.

**Comment by whowutwut** [comment]
@andreas-h  Thanks, we received it!

**Comment by daniceexi** [comment]
@whowutwut could handle it and invite @andreas-h to be xCAT contributor?

**Comment by whowutwut** [comment]
@daniceexi  Yep, done.  Will merge. Thannks @andreas-h !

**Pull request merged**
