### PR TITLE
Add labels for test cases which test DB operation command

### PR DESCRIPTION
**Pull request by hu-weihua**
Add labels for ``mn_only`` test cases.

* Add labels for test cases which test DB operation command
* Deleted some ``AIX`` test case at same time
* combine few test case which have same case name at same time

Related task xcat2/xcat2-task-management#208

### CODE REVIEW

**Comment by hu-weihua** [comment]
```
# XCATTEST_CASEDIR="/git/pubgit/xcat-core/xCAT-test/autotest/testcase/chdef" ./xcattest -l labelinfo
-------------------------------
The labels of cases:
-------------------------------
chdef_dynamic_group    mn_only,db,
chdef_group            mn_only,db,
chdef_group_p          mn_only,db,
chdef_m                mn_only,db,
chdef_multiple_keys    mn_only,db,
chdef_n                mn_only,db,
chdef_null             mn_only,db,
chdef_p                mn_only,db,
chdef_site_check       mn_only,db,
chdef_t_network        mn_only,db,
chdef_t_node           mn_only,db,
chdef_t_o_error        mn_only,db,
chdef_template         mn_only,db,
```
chdef_z                mn_only,db,

**Comment by hu-weihua** [comment]
```
# XCATTEST_CASEDIR="/git/pubgit/xcat-core/xCAT-test/autotest/testcase/mkdef" ./xcattest -l labelinfo
-------------------------------
The labels of cases:
-------------------------------
check_mkdef_node_with_template_priority             mn_only,db,
mkdef_dynamic_group                                 mn_only,db,
mkdef_f                                             mn_only,db,
mkdef_github_issue2582                              mn_only,db,
mkdef_group                                         mn_only,db,
mkdef_multiple_keys                                 mn_only,db,
mkdef_node                                          mn_only,db,
mkdef_node_with_a_node_template                     mn_only,db,
mkdef_null                                          mn_only,db,
mkdef_regex_bmc                                     mn_only,db,
mkdef_regex_ip                                      mn_only,db,
mkdef_regex_kvm                                     mn_only,db,
mkdef_regex_nicsip                                  mn_only,db,
mkdef_rhels73                                       os=linux,
mkdef_t_network                                     mn_only,db,
mkdef_t_o_error                                     mn_only,db,
mkdef_template_cec_template_step_by_step            mn_only,db,
mkdef_template_cec_template_without_remainder       mn_only,db,
mkdef_template_diskless_osimage_rootimgdir          cn_os_ready,db,
mkdef_template_invalid_template                     mn_only,db,
mkdef_template_switch_template_without_attribute    mn_only,db,
mkdef_z                                             mn_only,db,
```

**Comment by hu-weihua** [comment]
```
# XCATTEST_CASEDIR="/git/pubgit/xcat-core/xCAT-test/autotest/testcase/rmdef" ./xcattest -l labelinfo
-------------------------------
The labels of cases:
-------------------------------
rmdef_dynamic_group    mn_only,db,
rmdef_group            mn_only,db,
rmdef_node             mn_only,db,
rmdef_null             mn_only,db,
rmdef_t_err            mn_only,db,
rmdef_t_node           mn_only,db,
rmdef_t_o_network      mn_only,db,
rmdef_t_o_node         mn_only,db,
rmdef_template         mn_only,db,
```

**Comment by hu-weihua** [comment]
```
# XCATTEST_CASEDIR="/git/pubgit/xcat-core/xCAT-test/autotest/testcase/nodeadd" ./xcattest -l labelinfo
-------------------------------
The labels of cases:
-------------------------------
nodeadd_err_symbol            mn_only,db,
nodeadd_h                     mn_only,db,
nodeadd_noderange             mn_only,db,
nodeadd_noderange_nodetype    mn_only,db,
nodeadd_null                  mn_only,db,
nodeadd_v                     mn_only,db,
```

**Comment by hu-weihua** [comment]
```
# XCATTEST_CASEDIR="/git/pubgit/xcat-core/xCAT-test/autotest/testcase/nodels" ./xcattest -l labelinfo
-------------------------------
The labels of cases:
-------------------------------
nodels_H                             mn_only,db,
nodels_S                             mn_only,db,
nodels_b                             mn_only,db,
nodels_err_noderange                 mn_only,db,
nodels_err_symbol                    mn_only,db,
nodels_h                             mn_only,db,
nodels_noderange                     mn_only,db,
nodels_noderange_shortname_groups    mn_only,db,
nodels_noderange_shortname_mgt       mn_only,db,
nodels_noderange_shortname_tags      mn_only,db,
nodels_noderange_table               mn_only,db,
nodels_noderange_table_equal         mn_only,db,
nodels_noderange_table_unequal       mn_only,db,
nodels_noderange_table_uninclude     mn_only,db,
nodels_noderange_tablecolumn         mn_only,db,
nodels_null                          mn_only,db,
nodels_table_include                 mn_only,db,
nodels_tablevalue                    mn_only,db,
nodels_tablevalue_tablecolumn        mn_only,db,
nodels_v                             mn_only,db,
```

**Comment by hu-weihua** [comment]
```
# XCATTEST_CASEDIR="/git/pubgit/xcat-core/xCAT-test/autotest/testcase/nodech" ./xcattest -l labelinfo
-------------------------------
The labels of cases:
-------------------------------
nodech_d_error                        mn_only,db,
nodech_delete                         mn_only,db,
nodech_error_node                     mn_only,db,
nodech_error_table                    mn_only,db,
nodech_h                              mn_only,db,
nodech_noderanage_table_at            mn_only,db,
nodech_noderange_shortname_groups     mn_only,db,
nodech_noderange_shortname_mgt        mn_only,db,
nodech_noderange_shortname_tags       mn_only,db,
nodech_noderange_table                mn_only,db,
nodech_noderange_table_arrow          mn_only,db,
nodech_noderange_table_comma          mn_only,db,
nodech_noderange_table_comma_arrow    mn_only,db,
nodech_noderange_table_equal          mn_only,db,
nodech_noderange_table_include        mn_only,db,
nodech_noderange_table_unequal        mn_only,db,
nodech_noderange_table_uninclude      mn_only,db,
nodech_v                              mn_only,db,
```

**Comment by hu-weihua** [comment]
```
# XCATTEST_CASEDIR="/git/pubgit/xcat-core/xCAT-test/autotest/testcase/noderm" ./xcattest -l labelinfo
-------------------------------
The labels of cases:
-------------------------------
noderm_err_node     mn_only,db,
noderm_h            mn_only,db,
noderm_noderange    mn_only,db,
noderm_null         mn_only,db,
```

**Comment by hu-weihua** [comment]
```
# XCATTEST_CASEDIR="/git/pubgit/xcat-core/xCAT-test/autotest/testcase/nodegrpch" ./xcattest -l labelinfo
-------------------------------
The labels of cases:
-------------------------------
nodegrpch_err       mn_only,db,
nodegrpch_groups    mn_only,db,
nodegrpch_h         mn_only,db,
nodegrpch_v         mn_only,db,
```

**Comment by hu-weihua** [comment]
```
# XCATTEST_CASEDIR="/git/pubgit/xcat-core/xCAT-test/autotest/testcase/noderange" ./xcattest -l labelinfo
-------------------------------
The labels of cases:
-------------------------------
noderange_10-20                        mn_only,db,
noderange_XCAT_NODE_PREFIX             mn_only,db,
noderange_XCAT_NODE_SUFFIX             mn_only,db,
noderange_dir_tmp-nodelistfile         mn_only,db,
noderange_exclusion                    mn_only,db,
noderange_f1-f2_n1-n3                  mn_only,db,
noderange_group1-group3                mn_only,db,
noderange_group_intersection           mn_only,db,
noderange_individual_grp               mn_only,db,
noderange_individual_node              mn_only,db,
noderange_node01-node10                mn_only,db,
noderange_node01_10                    mn_only,db,
noderange_node10_plus_3                mn_only,db,
noderange_node_01-10                   mn_only,db,
noderange_slash_urtestnode_dot_star    mn_only,db,
```

**Comment by hu-weihua** [comment]
```
# XCATTEST_CASEDIR="/git/pubgit/xcat-core/xCAT-test/autotest/testcase/chtab" ./xcattest -l labelinfo
-------------------------------
The labels of cases:
-------------------------------
chtab_d              mn_only,db,
chtab_err_symble     mn_only,db,
chtab_err_table      mn_only,db,
chtab_h              mn_only,db,
chtab_modify_key     mn_only,db,
chtab_modify_node    mn_only,db,
chtab_null           mn_only,db,
chtab_v              mn_only,db,
```

**Comment by hu-weihua** [comment]
```
# XCATTEST_CASEDIR="/git/pubgit/xcat-core/xCAT-test/autotest/testcase/gettab" ./xcattest -l labelinfo
-------------------------------
The labels of cases:
-------------------------------
gettab_H            mn_only,db,
gettab_err          mn_only,db,
gettab_h            mn_only,db,
gettab_key_table    mn_only,db,
```

**Comment by hu-weihua** [comment]
```
# XCATTEST_CASEDIR="/git/pubgit/xcat-core/xCAT-test/autotest/testcase/tabdump" ./xcattest -l labelinfo
-------------------------------
The labels of cases:
-------------------------------
tabdump_d             mn_only,db,
tabdump_d_nodehm      mn_only,db,
tabdump_f_d           mn_only,db,
tabdump_h             mn_only,db,
tabdump_help          mn_only,db,
tabdump_null          mn_only,db,
tabdump_table         mn_only,db,
tabdump_v             mn_only,db,
tabdump_w_equal       mn_only,db,
tabdump_w_ge          mn_only,db,
tabdump_w_gt          mn_only,db,
tabdump_w_le          mn_only,db,
tabdump_w_lt          mn_only,db,
tabdump_w_match       mn_only,db,
tabdump_w_ne          mn_only,db,
tabdump_w_notmatch    mn_only,db,
```

**Comment by hu-weihua** [comment]
```
# XCATTEST_CASEDIR="/git/pubgit/xcat-core/xCAT-test/autotest/testcase/tabprune" ./xcattest -l labelinfo
-------------------------------
The labels of cases:
-------------------------------
tabprune_V_a_eventlog    mn_only,db,
tabprune_V_n_auditlog    mn_only,db,
tabprune_a_eventlog      mn_only,db,
tabprune_h               mn_only,db,
tabprune_i_auditlog      mn_only,db,
tabprune_p_auditlog      mn_only,db,
tabprune_v               mn_only,db,
```

**Comment by hu-weihua** [comment]
```
# XCATTEST_CASEDIR="/git/pubgit/xcat-core/xCAT-test/autotest/testcase/tabrestore" ./xcattest -l labelinfo
-------------------------------
The labels of cases:
-------------------------------
tabrestore_err      mn_only,db,
tabrestore_h        mn_only,db,
tabrestore_null     mn_only,db,
tabrestore_table    mn_only,db,
```

**Comment by hu-weihua** [comment]
```
# XCATTEST_CASEDIR="/git/pubgit/xcat-core/xCAT-test/autotest/testcase/xcatstanzafile" ./xcattest -l labelinfo
-------------------------------
The labels of cases:
-------------------------------
xcatstanzafile_attribute        mn_only,db,
xcatstanzafile_colon            mn_only,db,
xcatstanzafile_defaultvalue     mn_only,db,
xcatstanzafile_multattr         mn_only,db,
xcatstanzafile_normal           mn_only,db,
xcatstanzafile_objtype          mn_only,db,
xcatstanzafile_specificvalue    mn_only,db,
xcatstanzafile_tab              mn_only,db,
```

**Comment by hu-weihua** [comment]
```
# XCATTEST_CASEDIR="/git/pubgit/xcat-core/xCAT-test/autotest/testcase/regnotif" ./xcattest -l labelinfo
-------------------------------
The labels of cases:
-------------------------------
regnotif_err     mn_only,db,
regnotif_h       mn_only,db,
regnotif_null    mn_only,db,
regnotif_o       mn_only,db,
regnotif_v       mn_only,db,
```

**Comment by hu-weihua** [comment]
```
# XCATTEST_CASEDIR="/git/pubgit/xcat-core/xCAT-test/autotest/testcase/unregnotif" ./xcattest -l labelinfo
-------------------------------
The labels of cases:
-------------------------------
unregnotif_f       mn_only,db,
unregnotif_h       mn_only,db,
unregnotif_null    mn_only,db,
unregnotif_v       mn_only,db,
```

**Comment by tingtli** [comment]
I do not have comments for the labels. But when i review the cases, i found some of the old cases such as lsdef /chdef --template does not make much sense. Could we consider to rewrite the cases since we will add the label for all cases.

**Comment by hu-weihua** [comment]
@tingtli , if you found any cases need to refine/delete, log them in https://github.com/xcat2/xcat2-task-management/issues/201 as a comment. thanks.

**Comment by chuckbrazie** [comment]
I am out of the office until 07/16/2018.

I am out of the office until  Monday July 16.


Note: This is an automated response to your message  "Re: [xcat2/xcat-core]
Add labels for test cases which test DB operation command (#5353)" sent on
7/2/18 7:46:55 AM.

This is the only notification you will receive while this person is away.

**Comment by chuckbrazie** [comment]
I am out of the office until 07/16/2018.

I am out of the office until  Monday July 16.


Note: This is an automated response to your message  "Re: [xcat2/xcat-core]
Add labels for test cases which test DB operation command (#5353)" sent on
7/2/18 8:29:57 AM.

This is the only notification you will receive while this person is away.

**Comment by chuckbrazie** [comment]
I am out of the office until 07/16/2018.

I am out of the office until  Monday July 16.


Note: This is an automated response to your message  "Re: [xcat2/xcat-core]
Add labels for test cases which test DB operation command (#5353)" sent on
7/2/18 6:15:21 AM.

This is the only notification you will receive while this person is away.

**Pull request merged**
