### PR TITLE
Enhance nodeset error handling not to exit with one node error when operating a node range

### LINKED ISSUE #3838: nodeset fails to set petitboot files on node range if one node errors.
There really should be a way to have this command set the nodes it can, and leave the ones that are miss configured out.

[root@c460mgt01 ~]# nodeset c460c[801-816] osimage=rh74_compute_sf
c460c813: Error: missing mac data for c460c813

The specific situation is we are bringing up a rack of nodes and one node is in a state where genesis is not working so the mac address is bad, but we want to set the rest of the nodes up anyway.

[root@c460mgt01 ~]# lsxcatd -v
Version 2.13.7 (git commit 9cb9a8d4d5ce4d81617e2e5a5c2d32c42b596c5b, built Fri Sep  1 06:15:38 EDT 2017)

```
[root@c460mgt01 ~]# for n in c460c{801..816}; do cat /tftpboot/petitboot/$n; done;^C
[root@c460mgt01 ~]# nodeset c460c[801-816] boot
c460c801: boot
c460c802: boot
c460c803: boot
c460c804: boot
c460c805: boot
c460c806: boot
c460c807: boot
c460c808: boot
c460c809: boot
c460c810: boot
c460c811: boot
c460c812: boot
c460c813: boot
c460c814: boot
c460c815: boot
c460c816: boot
[root@c460mgt01 ~]# for n in c460c{801..816}; do cat /tftpboot/petitboot/$n; done;
#boot
#boot
#boot
#boot
#boot
#boot
#boot
#boot
#boot
#boot
#boot
#boot
#boot
#boot
#boot
#boot
```

all nodes in boot state:
```
[root@c460mgt01 ~]# nodeset c460c[801-816] osimage=rh74_compute_sf
c460c813: Error: missing mac data for c460c813

```

no nodes got their osimage set...
[root@c460mgt01 ~]# for n in c460c{801..816}; do cat /tftpboot/petitboot/$n; done;
#boot
#boot
#boot
#boot
#boot
#boot
#boot
#boot
#boot
#boot
#boot
#boot
#boot
#boot
#boot
#boot
```

Setting the nodes one at a time works though.
```
[root@c460mgt01 ~]# for n in c460c{801..816}; do nodeset $n osimage=rh74_compute_sf; done;
c460c801: install rhels7.4-ppc64le-compute
c460c802: install rhels7.4-ppc64le-compute
c460c803: install rhels7.4-ppc64le-compute
c460c804: install rhels7.4-ppc64le-compute
c460c805: install rhels7.4-ppc64le-compute
c460c806: install rhels7.4-ppc64le-compute
c460c807: install rhels7.4-ppc64le-compute
c460c808: install rhels7.4-ppc64le-compute
c460c809: install rhels7.4-ppc64le-compute
c460c810: install rhels7.4-ppc64le-compute
c460c811: install rhels7.4-ppc64le-compute
c460c812: install rhels7.4-ppc64le-compute
c460c813: Error: missing mac data for c460c813
c460c814: install rhels7.4-ppc64le-compute
c460c815: install rhels7.4-ppc64le-compute
c460c816: install rhels7.4-ppc64le-compute

```
[root@c460mgt01 ~]# for n in c460c{801..816}; do cat /tftpboot/petitboot/$n; done;
#install rhels7.4-ppc64le-compute                                                 
default xCAT                                                                      
label xCAT                                                                        
        kernel http://10.1.0.101:80/tftpboot/xcat/osimage/rh74_compute_sf/vmlinuz 
        initrd http://10.1.0.101:80/tftpboot/xcat/osimage/rh74_compute_sf/initrd.img
        append "quiet inst.repo=http://10.1.0.101:80/install/RHEL-ALT-7.4-20170808.0-Server-ppc64le/ppc64le inst.ks=http://10.1.0.101:80/install/autoinst/c460c801 BOOTIF=70:e2:84:14:28:38  ip=dhcp "            
#install rhels7.4-ppc64le-compute                                                                        
default xCAT                                                                                             
label xCAT                                                                                               
        kernel http://10.1.0.101:80/tftpboot/xcat/osimage/rh74_compute_sf/vmlinuz                        
        initrd http://10.1.0.101:80/tftpboot/xcat/osimage/rh74_compute_sf/initrd.img                     
        append "quiet inst.repo=http://10.1.0.101:80/install/RHEL-ALT-7.4-20170808.0-Server-ppc64le/ppc64le inst.ks=http://10.1.0.101:80/install/autoinst/c460c802 BOOTIF=70:e2:84:14:28:95  ip=dhcp "            
#install rhels7.4-ppc64le-compute                                                                        
default xCAT                                                                                             
label xCAT                                                                                               
        kernel http://10.1.0.101:80/tftpboot/xcat/osimage/rh74_compute_sf/vmlinuz                        
        initrd http://10.1.0.101:80/tftpboot/xcat/osimage/rh74_compute_sf/initrd.img                     
        append "quiet inst.repo=http://10.1.0.101:80/install/RHEL-ALT-7.4-20170808.0-Server-ppc64le/ppc64le inst.ks=http://10.1.0.101:80/install/autoinst/c460c803 BOOTIF=70:e2:84:14:29:4f  ip=dhcp "            
#install rhels7.4-ppc64le-compute                                                                        
default xCAT                                                                                             
label xCAT                                                                                               
        kernel http://10.1.0.101:80/tftpboot/xcat/osimage/rh74_compute_sf/vmlinuz                        
        initrd http://10.1.0.101:80/tftpboot/xcat/osimage/rh74_compute_sf/initrd.img                     
        append "quiet inst.repo=http://10.1.0.101:80/install/RHEL-ALT-7.4-20170808.0-Server-ppc64le/ppc64le inst.ks=http://10.1.0.101:80/install/autoinst/c460c804 BOOTIF=70:e2:84:14:29:49  ip=dhcp "            
#install rhels7.4-ppc64le-compute                                                                        
default xCAT                                                                                             
label xCAT                                                                                               
        kernel http://10.1.0.101:80/tftpboot/xcat/osimage/rh74_compute_sf/vmlinuz                        
        initrd http://10.1.0.101:80/tftpboot/xcat/osimage/rh74_compute_sf/initrd.img                     
        append "quiet inst.repo=http://10.1.0.101:80/install/RHEL-ALT-7.4-20170808.0-Server-ppc64le/ppc64le inst.ks=http://10.1.0.101:80/install/autoinst/c460c805 BOOTIF=70:e2:84:14:29:13  ip=dhcp "            
#install rhels7.4-ppc64le-compute                                                                        
default xCAT                                                                                             
label xCAT                                                                                               
        kernel http://10.1.0.101:80/tftpboot/xcat/osimage/rh74_compute_sf/vmlinuz                        
        initrd http://10.1.0.101:80/tftpboot/xcat/osimage/rh74_compute_sf/initrd.img                     
        append "quiet inst.repo=http://10.1.0.101:80/install/RHEL-ALT-7.4-20170808.0-Server-ppc64le/ppc64le inst.ks=http://10.1.0.101:80/install/autoinst/c460c806 BOOTIF=70:e2:84:14:2a:4b  ip=dhcp "            
#install rhels7.4-ppc64le-compute                                                                        
default xCAT                                                                                             
label xCAT                                                                                               
        kernel http://10.1.0.101:80/tftpboot/xcat/osimage/rh74_compute_sf/vmlinuz                        
        initrd http://10.1.0.101:80/tftpboot/xcat/osimage/rh74_compute_sf/initrd.img                     
        append "quiet inst.repo=http://10.1.0.101:80/install/RHEL-ALT-7.4-20170808.0-Server-ppc64le/ppc64le inst.ks=http://10.1.0.101:80/install/autoinst/c460c807 BOOTIF=70:e2:84:14:29:91  ip=dhcp "            
#install rhels7.4-ppc64le-compute                                                                        
default xCAT
label xCAT
        kernel http://10.1.0.101:80/tftpboot/xcat/osimage/rh74_compute_sf/vmlinuz
        initrd http://10.1.0.101:80/tftpboot/xcat/osimage/rh74_compute_sf/initrd.img
        append "quiet inst.repo=http://10.1.0.101:80/install/RHEL-ALT-7.4-20170808.0-Server-ppc64le/ppc64le inst.ks=http://10.1.0.101:80/install/autoinst/c460c808 BOOTIF=70:e2:84:14:2a:3c  ip=dhcp "
#install rhels7.4-ppc64le-compute
default xCAT
label xCAT
        kernel http://10.1.0.101:80/tftpboot/xcat/osimage/rh74_compute_sf/vmlinuz
        initrd http://10.1.0.101:80/tftpboot/xcat/osimage/rh74_compute_sf/initrd.img
        append "quiet inst.repo=http://10.1.0.101:80/install/RHEL-ALT-7.4-20170808.0-Server-ppc64le/ppc64le inst.ks=http://10.1.0.101:80/install/autoinst/c460c809 BOOTIF=70:e2:84:14:29:43  ip=dhcp "
#install rhels7.4-ppc64le-compute
default xCAT
label xCAT
        kernel http://10.1.0.101:80/tftpboot/xcat/osimage/rh74_compute_sf/vmlinuz
        initrd http://10.1.0.101:80/tftpboot/xcat/osimage/rh74_compute_sf/initrd.img
        append "quiet inst.repo=http://10.1.0.101:80/install/RHEL-ALT-7.4-20170808.0-Server-ppc64le/ppc64le inst.ks=http://10.1.0.101:80/install/autoinst/c460c810 BOOTIF=70:e2:84:14:28:d7  ip=dhcp "
#install rhels7.4-ppc64le-compute
default xCAT
label xCAT
        kernel http://10.1.0.101:80/tftpboot/xcat/osimage/rh74_compute_sf/vmlinuz
        initrd http://10.1.0.101:80/tftpboot/xcat/osimage/rh74_compute_sf/initrd.img
        append "quiet inst.repo=http://10.1.0.101:80/install/RHEL-ALT-7.4-20170808.0-Server-ppc64le/ppc64le inst.ks=http://10.1.0.101:80/install/autoinst/c460c811 BOOTIF=70:e2:84:14:29:2b  ip=dhcp "
#install rhels7.4-ppc64le-compute
default xCAT
label xCAT
        kernel http://10.1.0.101:80/tftpboot/xcat/osimage/rh74_compute_sf/vmlinuz
        initrd http://10.1.0.101:80/tftpboot/xcat/osimage/rh74_compute_sf/initrd.img
        append "quiet inst.repo=http://10.1.0.101:80/install/RHEL-ALT-7.4-20170808.0-Server-ppc64le/ppc64le inst.ks=http://10.1.0.101:80/install/autoinst/c460c812 BOOTIF=70:e2:84:14:28:dd  ip=dhcp "
#boot
#install rhels7.4-ppc64le-compute
default xCAT
label xCAT
        kernel http://10.1.0.101:80/tftpboot/xcat/osimage/rh74_compute_sf/vmlinuz
        initrd http://10.1.0.101:80/tftpboot/xcat/osimage/rh74_compute_sf/initrd.img
        append "quiet inst.repo=http://10.1.0.101:80/install/RHEL-ALT-7.4-20170808.0-Server-ppc64le/ppc64le inst.ks=http://10.1.0.101:80/install/autoinst/c460c814 BOOTIF=70:e2:84:14:2a:45  ip=dhcp "
#install rhels7.4-ppc64le-compute
default xCAT
label xCAT
        kernel http://10.1.0.101:80/tftpboot/xcat/osimage/rh74_compute_sf/vmlinuz
        initrd http://10.1.0.101:80/tftpboot/xcat/osimage/rh74_compute_sf/initrd.img
        append "quiet inst.repo=http://10.1.0.101:80/install/RHEL-ALT-7.4-20170808.0-Server-ppc64le/ppc64le inst.ks=http://10.1.0.101:80/install/autoinst/c460c815 BOOTIF=70:e2:84:14:2a:3f  ip=dhcp "
#install rhels7.4-ppc64le-compute
default xCAT
label xCAT
        kernel http://10.1.0.101:80/tftpboot/xcat/osimage/rh74_compute_sf/vmlinuz
        initrd http://10.1.0.101:80/tftpboot/xcat/osimage/rh74_compute_sf/initrd.img
        append "quiet inst.repo=http://10.1.0.101:80/install/RHEL-ALT-7.4-20170808.0-Server-ppc64le/ppc64le inst.ks=http://10.1.0.101:80/install/autoinst/c460c816 BOOTIF=70:e2:84:14:28:56  ip=dhcp "
[root@c460mgt01 ~]#
```

### PR DESCRIPTION
**Pull request by robin2008**
To fix #3838 

Note:  this is now only for `petitiboot`, `grub2`, `xnba` netboot type And for `rhel` family OS.
UT: 
```
# nodeset perftest osimage=rhels7.3-custom-netboot
fake3: Error: No MAC address available
fake1: netboot rhels7.3-ppc64le-service
fake2: netboot rhels7.3-ppc64le-service
fake4: netboot rhels7.3-ppc64le-service
fake5: netboot rhels7.3-ppc64le-service
Error: Failed to generate petitboot configurations for some node(s) on c910f03c05k20. Check xCAT log file for more details.
```

More UT result will be appended.

### CODE REVIEW

**Comment by robin2008** [comment]
1, for nodeset xxx osimage[=yyy]
wrong `node` attributes and `osimage` attributes will cause the `nodeset` failure.
For node,  need to check `IP, MAC,  provmethod and (osver, arch, profile), serialspeed if serialport is set`

For osimage, to check if exists, and mandatory attributes, for stateless/statelite,  need to check if the kernel/initrd/rootfs is available.

2, for other nodeset action, normally for `node` attributes only.

**Comment by robin2008** [comment]
`nodeset <nr> shell/runimg/runcmd`
================================================

* No `serialspeed` for fake5 and No `arch` for fake4
```
# nodeset perftest shell
fake4: Error: No archictecture defined in nodetype table for the node.
fake5: Error: Serial port defined in noderes, but no nodehm.serialspeed set for the node.
fake1: shell
fake2: shell
fake3: shell
Warning: Unable to find mac address for fake3
Warning: Unable to find mac address for fake3
Error: Failed to generate petitboot configurations for some node(s) on c910f03c05k20. Check xCAT log file for more details.
```
```
nodeset perftest runcmd=bmcsetup
fake4: Error: No archictecture defined in nodetype table for the node.
fake5: Error: Serial port defined in noderes, but no nodehm.serialspeed set for the node.
fake1: runcmd=bmcsetup
fake2: runcmd=bmcsetup
fake3: runcmd=bmcsetup
Warning: Unable to find mac address for fake3
Warning: Unable to find mac address for fake3
Error: Failed to generate petitboot configurations for some node(s) on c910f03c05k20. Check xCAT log file for more details.
```

```
nodeset perftest runimage=/install/html/index.html
Error: Cannot get /install/html/index.html with wget. Could you confirm it's downloadable by wget?
[root@c910f03c05k20 petitboot]# nodeset perftest runimage=http://127.0.0.1/install/html/index.html
fake4: Error: No archictecture defined in nodetype table for the node.
fake5: Error: serialport defined, but no serialspeed for this node in nodehm table
fake1: runimage=http://127.0.0.1/install/html/index.html
fake2: runimage=http://127.0.0.1/install/html/index.html
fake3: runimage=http://127.0.0.1/install/html/index.html
Warning: Unable to find mac address for fake3
Warning: Unable to find mac address for fake3
Error: Failed to generate petitboot configurations for some node(s) on c910f03c05k20. Check xCAT log file for more details.
```

**Comment by robin2008** [comment]
# nodeset perftest osimage

```
nodeset perftest osimage
fake3: Error: No MAC address available
fake2: Error: OS image name must be specified in nodetype.provmethod
fake5: Error: serialport defined, but no serialspeed for fake5 in nodehm table
fake1: install rhels7.3-ppc64le-compute
fake4: install rhels7.3-ppc64le-compute
Error: Failed to generate petitboot configurations for some node(s) on c910f03c05k20. Check xCAT log file for more details.
```

```
nodeset perftest osimage=test-statelite
fake3: Error: No MAC address available
fake5: Error: serialport defined, but no serialspeed for fake5 in nodehm table
fake1: statelite rhels7.3-ppc64le-compute
fake2: statelite rhels7.3-ppc64le-compute
fake4: statelite rhels7.3-ppc64le-compute
Error: Failed to generate petitboot configurations for some node(s) on c910f03c05k20. Check xCAT log file for more details.
```
```
nodeset perftest osimage=abc
fake3: Error: No MAC address available
Error: Cannot find the OS image abc on the osimage table.

nodeset perftest osimage=rhels7.3-custom-netboot
fake3: Error: No MAC address available
fake1: Error: Insufficient nodetype entry or osimage entry for fake1
fake2: Error: Insufficient nodetype entry or osimage entry for fake2
fake4: Error: Insufficient nodetype entry or osimage entry for fake4
fake5: Error: Insufficient nodetype entry or osimage entry for fake5
Error: Failed to generate petitboot configurations for some node(s) on c910f03c05k20. Check xCAT log file for more details.
```

**Comment by robin2008** [comment]
Now 'xnba' plugin is available too in this PR.
```
chedef perftest netboot=xnba arch=x86_64
nodeset perftest osimage=rhels7.3-x86_64-install-compute
fake3: Error: No MAC address available for this node
fake5: Error: serialport defined, but no serialspeed for fake5 in nodehm table
fake1: install rhels7.3-x86_64-compute
fake2: install rhels7.3-x86_64-compute
fake4: install rhels7.3-x86_64-compute
Error: Failed to generate xnba configurations for some node(s) on c910f03c05k20. Check xCAT log file for more details.
```

**Comment by robin2008** [comment]
Now `grub2` is available too.

```
chdef perftest netboot=grub2 arch=ppc64le
...
[root@c910f03c05k20 grub2]# ls
fake2  fonts                          grub.cfg-C0A80002  grub2-fake2  grub2.ppc
fake3  grub.cfg-01-00-60-2f-0e-8a-52  grub.cfg-C0A80003  grub2-fake3  locale
fake4  grub.cfg-01-00-60-2f-23-db-33  grub.cfg-C0A80004  grub2-fake4  powerpc-ieee1275
fake5  grub.cfg-01-00-60-2f-f4-fb-ea  grub.cfg-C0A80005  grub2-fake5
[root@c910f03c05k20 grub2]# nodeset perftest offline
fake1: offline
fake2: offline
fake3: offline
fake4: offline
fake5: offline
Warning: Unable to find mac address for fake3
[root@c910f03c05k20 grub2]# ls
fonts  grub2.ppc  locale  powerpc-ieee1275

[root@c910f03c05k20 grub2]# nodeset perftest osimage
fake1: Error: OS image name must be specified in nodetype.provmethod
fake3: Error: No MAC address available for this node
fake5: Error: serialport defined, but no serialspeed for fake5 in nodehm table
fake2: install rhels7.3-ppc64le-compute
fake4: install rhels7.3-ppc64le-compute
[root@c910f03c05k20 grub2]# ls
fake2  fonts                          grub.cfg-01-00-60-2f-23-db-33  grub.cfg-C0A80004  grub2-fake4  locale
fake4  grub.cfg-01-00-60-2f-0e-8a-52  grub.cfg-C0A80002              grub2-fake2        grub2.ppc    powerpc-ieee1275
```
For nodeset boot,  the grub2 binary link should be deleted as well.
```
# nodeset perftest shell
fake5: Error: serialport defined, but no serialspeed for this node in nodehm table
fake1: shell
fake2: shell
fake3: shell
fake4: shell
[root@c910f03c05k20 grub2]# ls grub2-*
grub2-fake1  grub2-fake2  grub2-fake3  grub2-fake4
[root@c910f03c05k20 grub2]# nodeset perftest boot
fake1: boot
fake2: boot
fake3: boot
fake4: boot
fake5: boot
[root@c910f03c05k20 grub2]# ls grub2-*
ls: cannot access grub2-*: No such file or directory
```
Same capability as before, and it won't break when some of the nodes are failure.

**Comment by daniceexi** [comment]
@robin2008 thanks for the hard work in the holiday.

We need an unified standard for how to handle the failure when handling multiple nodes in one command execution. My comments are:
* We may give an error as early as possible and stop the run for the usage error so that user could aware the wrong configuration and correct it immediately.
* Do our best to display the error at end of the output (at least in group), otherwise the failure would be submerged in the correct messages.

**Comment by robin2008** [comment]
@daniceexi 

Normally, there would be 3 different level to handle the error.
1,  for CLI usage will be checked at the first time and stop before running.
2, Only for major and common attributes (like IP, MAC to nodeset; it is depending on the CLI business logic), they will be pre-checked before going further. 
3, But for full required attributes, checking it before doing (It could get better performance in current plugin design)

And we need to distinguish the node level error (wrong node configuration) and program error (global or system error), and design the error handling logic, especially for nested calling, need to get the failure nodes after the sub-plugins handling and get rid of them for next business.

4, I agree with you better to converge error message, and `xcoll` is a good tool for that if it is hard to achieve that .

**Comment by whowutwut** [comment]
@hu-weihua Are we able to run this in a sandbox build through automation, if we feel it's quite large change?  Do we have a lot of nodeset tests that could exercise this?

**Comment by robin2008** [comment]
@vhu It has already run successfully with the development  test environment.

**Comment by zet809** [comment]
Let's merge it.

**Comment by robin2008** [comment]
For sles/ubuntu:
https://github.com/xcat2/xcat-core/pull/4122

**Pull request merged**
