### PR TITLE
Add reseat to rpower man and usage

### PR DESCRIPTION
**Pull request by aduffy19**
Add "Lenovo high-density server" section to rpower man and usage pages. Include reseat option.
This pull request does not yet include an updated .rst file.

### CODE REVIEW

**Comment by aduffy19** [comment]
@jjohnson42 @whowutwut This pull request replaces #2709 and #2711 
We haven't created the .rst file

**Comment by whowutwut** [comment]
@aduffy19  Ok no problem, we normally go through towards the end of the release and make sure that we update any missing pod -> rst files

**Comment by aduffy19** [comment]
@whowutwut Okay cool, does that mean we're able to merge?

**Comment by whowutwut** [comment]
Yes, will merge this.

**Comment by whowutwut** [comment]
In the future, you might want to create a branch for the pull requests changes...  instead of your forked copy master branch .  After the pull request is merged, the branch can be deleted.  Also in the event that the pull request takes some time to review, you can still do development and pull down changes from the upstream to your forked copy.

**Pull request merged**
