### PR TITLE
Add Rocky Linux 8.4 support

### PR DESCRIPTION
**Pull request by fangjzh**
### The modification include
add rocky linux support in the share perl module files
                     
### The PR is for task _#xxx_ or to implement feature #xxx
reply to issue #6966

_##Feature description##_
Add Rocky Linux 8.4 support

### CODE REVIEW

**Comment by gurevichmark** [comment]
@fangjzh Thank you for your interest in contributing to the xCAT project. We require all contributors to submit a Contributor License Agreement before we can accept any contributions.

Are you interested in becoming a formal contributor? If so, please feel out the Contributor License Agreement available here: https://xcat-docs.readthedocs.io/en/latest/developers/license/contributors.html and submit the completed form to the xcat-legal mailing list (instructions are included in the document).

**Comment by fangjzh** [comment]
> 
> 
> @fangjzh Thank you for your interest in contributing to the xCAT project. We require all contributors to submit a Contributor License Agreement before we can accept any contributions.
> 
> Are you interested in becoming a formal contributor? If so, please feel out the Contributor License Agreement available here: https://xcat-docs.readthedocs.io/en/latest/developers/license/contributors.html and submit the completed form to the xcat-legal mailing list (instructions are included in the document).

Thank you, I have sent the email with CLA.

**Comment by gurevichmark** [comment]
@fangjzh Is this PR complete now ? Or are you still working on additional changes ?

**Comment by fangjzh** [comment]
> 
> 
> @fangjzh Is this PR complete now ? Or are you still working on additional changes ?

It is completed. I simply added Rocky Linux support, and currently no problems have been found in deploying compute nodes. Due to my limited knowledge of xCAT, I think the code needs more tests, I hope you can provide help in this regard. Thank you.

**Review by besawn — APPROVED** [review]
Thank you for the contribution!

**Comment by ruixingw** [comment]
Today I tested using Rocky for both management and the compute nodes. 
All was good except a small problem: during node discovery process, detailed messages were not printed on the screen (see attached photo, it's stuck here before reboot to install OS), but everything was actually going on normally (ntp, discovery, ```chain=runcmd=bmcsetup,osimage=rocky8.4-x86-64-install-compute```) as I can confirm from the management node ```/var/log/messages```. The provisioning was successful in the end.

QQ20211105-212823

**Pull request merged**
