### PR TITLE
Make changes to xCAT-genesis-build process to create version dependencies in xCAT-genesis-base

### PR DESCRIPTION
**Pull request by whowutwut**
Fixes Issues #2239 

Includes the following changes: 

- Bump up the version to 2.13.0
- Edit the makerpm to replace version of xCAT-genesis-base.spec
  file so there's no need to manually set the VERSION.  We
  do need a better way for the RELEASE variable
- Require xCAT-genesis-base >= 2.13.0 for the rebuild of genesis-base
- Clean up the builder rpm to include directories to clean up correctly
  on rpm removal

With this change the builder-rpm is still created with the same naming: 
```
$ ./makerpm xCAT-genesis-builder
Building /home/vhu/rpmbuild/RPMS/noarch/xCAT-genesis-builder-2.13.0-snap*.noarch.rpm ...
```

But when we create the genesis-base, the result is the following: 
```
[root@c910f02c05p05 vhu]# /opt/xcat/share/xcat/netboot/genesis/builder/buildrpm -y
cp: omitting directory ‘/opt/xcat/share/xcat/netboot/genesis/builder/debian’
Creating the initramfs in /tmp/xcatgenesis.20848.rfs using dracut ...
Disabling early microcode, because kernel does not support it. CONFIG_MICROCODE_[AMD|INTEL]_EARLY!=y

Expanding the initramfs into /tmp/xcatgenesis.20848/opt/xcat/share/xcat/netboot/genesis/ppc64/fs ...
...
...
Wrote: /root/rpmbuild/SRPMS/xCAT-genesis-base-ppc64-2.13.0-0.src.rpm
Wrote: /root/rpmbuild/RPMS/noarch/xCAT-genesis-base-ppc64-2.13.0-0.noarch.rpm
Executing(%clean): /bin/sh -e /var/tmp/rpm-tmp.BE3mUu
+ umask 022
+ cd /root/rpmbuild/BUILD
+ /usr/bin/rm -rf /root/rpmbuild/BUILDROOT/xCAT-genesis-base-ppc64-2.13.0-0.ppc64
+ exit 0

```

Result: 
```
[root@c910f02c05p05 vhu]# rpm -qip --provides /root/rpmbuild/RPMS/noarch/xCAT-genesis-base-ppc64-2.13.0-0.noarch.rpm
Name        : xCAT-genesis-base-ppc64
Version     : 2.13.0
Release     : 0
Architecture: noarch
Install Date: (not installed)
Group       : System/Utilities
Size        : 172959487
License     : Various (see individual packages for details)
Signature   : (none)
Source RPM  : xCAT-genesis-base-ppc64-2.13.0-0.src.rpm
Build Date  : Fri 02 Dec 2016 05:46:38 PM EST
Build Host  : c910f02c05p05.pok.stglabs.ibm.com
Relocations : /opt/xcat
Packager    : IBM Corp.
Vendor      : IBM Corp.
URL         : http://xcat.org
Summary     : xCAT Genesis netboot image
Description :
xCAT genesis (Genesis Enhanced Netboot Environment for System Information and Servicing) is a small, embedded-like environment for xCAT's use in discovery and management actions when interaction with an OS is infeasible.
This package comprises the base platform with most of the xCAT specific behavior left to xCAT-genesis-scripts package.
xCAT-genesis-base-ppc64 = 2.13.0-0
```

### CODE REVIEW

**Comment by whowutwut** [comment]
@zet809 @daniceexi  

There still should be a better way to generate the release.  Looking into using `git describe` but the tags are not operating correctly.  Currently it's hard codes into `makerpm` as `GEN_BASE_REL=0`  

Any ideas?

**Comment by daniceexi** [comment]
It's hard to work out a way to bump up the release number wholly automatic. Currently figure out a process for people to follow is what we can do. And then we'll see what we can automate base on the process.

**Comment by whowutwut** [comment]
@daniceexi  OK, will leave the release hard coded at 0 for now.  Release is only required to bump up if we are re-building different versions between a minor release of xCAT that we want to allow customers to run with one or another.  Otherwise it should be sync'ed up.  

Discussed in the call, will merge this to test for 2.13.

**Comment by zet809** [comment]
Based on the Pull Request #2260, it seems the xcat-genesis-script doesn't strictly depend on xcat-genesis-base 2.13.0, right? If that is true, what is the benefit of use Epoch: 2?

**Comment by whowutwut** [comment]
Right, after I merged this and started testing, the expected result was not seen so I created the additional pull request #2260 to remove the release and go back to the snap<date> naming convention.

**Pull request merged**
