### PR TITLE
hierarchicalattrs does not work on some columns with special delimiter

### PR DESCRIPTION
**Pull request by robin2008**
### The modification include

the `hierarchicalattrs` only support comma as delimiter before,  this PR is to make user define any delimiter for some columns.

### The UT result
```
chdef -t site hierarchicalattrs="postscripts,begin:|"
tabdump prescripts
#node,begin,end,comments,disable
"fake1","all.sh|osimage:osimage1.sh",,,
"a","a",,,
"b","b",,,

tabdump postscripts
#node,postscripts,postbootscripts,comments,disable
"fake1","myself","myself",,
"a","a","a",,
"b","b","b",,

lsdef fake1 -i groups,postscripts,postbootscripts,prescripts-begin
Object name: fake1
    groups=a,b
    postbootscripts=otherpkgs,myself                                   <===== overridden as this attribute is not in hierarchicalattrs
    postscripts=syslog,remoteshell,syncfiles,myself,a,b       <=====  using comma if no explicit declare
    prescripts-begin=all.sh|osimage:osimage1.sh|a|b           <=====  using | as delimiter when specified in site
```

### CODE REVIEW

**Comment by immarvin** [comment]
i am ok with the change

**Comment by kcgthb** [comment]
Looks good but I have a question: is `prescripts-begin=all.sh|osimage:osimage1.sh|a|b` a valid syntax?
It looks like it should be combined as `prescripts-begin=all.sh,a,b|osimage:osimage1.sh` instead, doesn't it?

Actually, I'm not even sure `prescripts` support mixing prefixed (with `osimage:` for instance) and non-prefixed script names, does it? The documentation is not very clear, but the examples don't show any mixed case with non-prefixed scripts:
```
    Examples:
        myscript1,myscript2  (all actions)
        diskless:myscript1,myscript2   (AIX)
        install:myscript1,myscript2|netboot:myscript3   (Linux)
```

**Comment by robin2008** [comment]
@kcgthb 

I think both the format are supported by `prescripts`, as it is only defined the different orders.
`all.sh|osimage:osimage1.sh|a|b` describe the order of execution:
for sub-commands which are not `osimage`,  execute `all.sh -> a -> b`
for `osimage`, execute `all.sh -> osimage1.sh -> a -> b`

If define as `all.sh,a,b|osimage:osimage1.sh`, then the order as below
```
all.sh -> a -> b
all.sh -> a -> b -> osimage:osimage1.sh
```
You see, that is totally different as scripts might have dependency.  Of course, if no dependency, all is fine.

And for the attributes inheritance rules, xcat has its logic in codes:
`<node attribute> -> <1st group attribute> -> <2nd group attribute> -> <last group>`

If the attribute is not in `hierarchicalattrs`, then the above behavior is override. Or it will be combined with the order.

Whatever, I'll test it with https://github.com/xcat2/xcat-core/pull/5682 to verify it.

**Comment by robin2008** [comment]
UT for the format:
```
lsdef mid08tor03cn01 -i prescripts-begin
Object name: mid08tor03cn01
    prescripts-begin=all.sh|boot:boot.sh|osimage:osimage.sh,osimage1.sh|a|b
```
```
nodeset mid08tor03cn01 boot|grep Running
boston02.pok.stglabs.ibm.com: Running begin script all.sh for nodes mid08tor03cn01.
boston02.pok.stglabs.ibm.com: Running begin script boot.sh for nodes mid08tor03cn01.
boston02.pok.stglabs.ibm.com: Running begin script a for nodes mid08tor03cn01.
boston02.pok.stglabs.ibm.com: Running begin script b for nodes mid08tor03cn01.

[root@boston02 xCAT_plugin]# nodeset mid08tor03cn01 osimage|grep Running
boston02.pok.stglabs.ibm.com: Running begin script all.sh for nodes mid08tor03cn01.
boston02.pok.stglabs.ibm.com: Running begin script osimage.sh for nodes mid08tor03cn01.
boston02.pok.stglabs.ibm.com: Running begin script osimage1.sh for nodes mid08tor03cn01.
boston02.pok.stglabs.ibm.com: Running begin script a for nodes mid08tor03cn01.
boston02.pok.stglabs.ibm.com: Running begin script b for nodes mid08tor03cn01.

[root@boston02 xCAT_plugin]# nodeset mid08tor03cn01 shell|grep Running
boston02.pok.stglabs.ibm.com: Running begin script all.sh for nodes mid08tor03cn01.
boston02.pok.stglabs.ibm.com: Running begin script a for nodes mid08tor03cn01.
boston02.pok.stglabs.ibm.com: Running begin script b for nodes mid08tor03cn01.
```

Work as expected.

BTW:  You can still control the behavior of script by `ACTION` environment variable in your script itself. 
xCAT execute the script with below: 
`NODES=$node ACTION=$action $installdir/prescripts/$s 2>&1`

**Pull request merged**
