### PR TITLE
Make status changing log more clear

### PR DESCRIPTION
**Pull request by robin2008**
### The modification include
Clear key words for install status update log message 
- detect provisioning when updateing status to installing/netbooting
- consistent message format "xcat.updatestatus - ($node): changing status=($status)" (no need to log the time as syslog has the timestamp)
- xcatprobe - osdeploy will parse the log content, so it needs to be revised.

### The UT result
```
grep xcat.updatestatus /var/log/xcat/cluster.log
Nov 27 01:05:10 briggs01 xcat[111048]: INFO xcat.updatestatus - mid05tor12cn05: changing status=powering-off
Nov 27 01:05:45 briggs01 xcat[111048]: INFO xcat.updatestatus - mid05tor12cn05: changing status=powering-on
Nov 27 01:08:52 briggs01 xcat[110999]: INFO xcat.updatestatus - mid05tor12cn05: provisioning detected...
Nov 27 01:08:52 briggs01 xcat[110999]: INFO xcat.updatestatus - mid05tor12cn05: changing status=installing
Nov 27 01:25:20 briggs01 xcat[110999]: INFO xcat.updatestatus - mid05tor12cn05: changing status=booting
Nov 27 01:28:32 briggs01 xcat[110999]: INFO xcat.updatestatus - mid05tor12cn05: changing status=postbooting
Nov 27 01:29:49 briggs01 xcat[110999]: INFO xcat.updatestatus - mid05tor12cn05: changing status=booted
```

```
Nov 27 02:36:04 boston36 xcat[120448]: INFO xcat.updatestatus - mid21tor24cn04: changing status=powering-on
Nov 27 02:38:50 boston36 xcat[120391]: INFO xcat.updatestatus - mid21tor24cn04: provisioning detected...
Nov 27 02:38:50 boston36 xcat[120391]: INFO xcat.updatestatus - mid21tor24cn04: changing status=netbooting
Nov 27 02:40:52 boston36 xcat[120391]: INFO xcat.updatestatus - mid21tor24cn04: changing status=postbooting
Nov 27 02:41:06 boston36 xcat[120391]: INFO xcat.updatestatus - mid21tor24cn04: changing status=failed
```

### CODE REVIEW

**Comment by robin2008** [comment]
```
xcatprobe osdeploy -n mid21tor24cn03
The install NIC in current server is enP1p9s0f2                                                                   [INFO]
All nodes to be deployed are valid                                                                                [ OK ]
-------------------------------------------------------------
Start capturing every message during OS provision process....
-------------------------------------------------------------

[mid21tor24cn03] 03:55:40 Use command rpower to reboot node mid21tor24cn03
[mid21tor24cn03] 03:55:40 Node status is changed to powering-on
[mid21tor24cn03] 03:57:51 Receive DHCPDISCOVER via enP48p1s0f0
...
[mid21tor24cn03] 03:59:25 Node status is changed to postbooting
[mid21tor24cn03] 03:59:26 Via HTTP get /install/postscripts/
...
[mid21tor24cn03] 03:59:27 Via HTTP get /tftpboot/mypostscripts/mypostscript.mid21tor24cn03
[mid21tor24cn03] 04:00:54 Node status is changed to failed
All nodes specified to monitor, have finished OS provision process                                                [ OK ]
======================  Summary  =====================
There is 1 node provision failures
mid21tor24cn03 : stop at stage ''                                                                                 [FAIL]
```

**Comment by robin2008** [comment]
@hu-weihua  help to review the `xcatprobe` part.

**Comment by bybai** [comment]
I am ok to merge it.

**Comment by hu-weihua** [comment]
It is ok for me. thanks @robin2008

**Pull request merged**
