### PR TITLE
Handle openbmc login and rflash errors

### PR DESCRIPTION
**Pull request by gurevichmark**
### The modification include

* Better message suggesting to run `reventlog` if Host does not power on after `rflash -d` command

* Better message suggesting to verify REST server is running if 502 code returned from login attempt

### The UT result
Python with debug
```
[root@briggs01 xcat]# rpower mid05tor12cn03 stat -V
[briggs01]: Running command in Python
[briggs01]: Wed Apr  3 15:58:44 2019 mid05tor12cn03: [openbmc_debug] login curl -k -c cjar -b cjar -X POST -H "Content-Type: application/json" https://172.11.139.3/login -d '{"data": ["root", "xxxxxx"]}'
[briggs01]: Wed Apr  3 15:58:45 2019 mid05tor12cn03: [openbmc_debug] login (Verify REST server is running on the BMC)
[briggs01]: Wed Apr  3 15:58:45 2019 mid05tor12cn03: [openbmc_debug] login Login to BMC failed: Can't connect to 172.11.139.3 (Verify REST server is running on the BMC).
mid05tor12cn03: [briggs01]: Error: Login to BMC failed: Can't connect to 172.11.139.3 (Verify REST server is running on the BMC).
[root@briggs01 xcat]#
```

Python no debug
```
[root@briggs01 xcat]# rpower mid05tor12cn03 stat -V
[briggs01]: Running command in Python
mid05tor12cn03: [briggs01]: Error: Login to BMC failed: Can't connect to 172.11.139.3 (Verify REST server is running on the BMC).
[root@briggs01 xcat]#
```
Perl with debug
```
[root@briggs01 xcat]# rpower mid05tor12cn03 stat -V
Wed Apr  3 16:08:04 2019 OpenBMC: [briggs01]: [openbmc_debug_perl]
[briggs01]: Running command in Perl
mid05tor12cn03: [briggs01]: Error: [502] Login to BMC failed: 502 Bad Gateway. Verify REST server is running on the BMC.
mid05tor12cn03: [briggs01]: Error: BMC did not respond. Validate BMC configuration and retry the command.
[root@briggs01 xcat]#
```

Perl no debug
```
[root@briggs01 xcat]# rpower mid05tor12cn03 stat -V
[briggs01]: Running command in Perl
mid05tor12cn03: [briggs01]: Error: [502] Login to BMC failed: 502 Bad Gateway. Verify REST server is running on the BMC.
mid05tor12cn03: [briggs01]: Error: BMC did not respond. Validate BMC configuration and retry the command.
[root@briggs01 xcat]#
```

### CODE REVIEW

**Comment by gurevichmark** [comment]
For UT used the following on the BMC to stop the REST server:
```
root@witherspoon:~# systemctl stop phosphor-gevent
Warning: Stopping phosphor-gevent.service, but it can still be activated by:
  phosphor-gevent.socket

root@witherspoon:~# systemctl stop phosphor-gevent.socket
root@witherspoon:~#
```

**Comment by robin2008** [comment]
@gurevichmark 

It looks you have two different message for the same error.
And REST service is just one of the potential cause which makes 502 error, need to check with OpenBMC team to see if this is the major cause,  or the message may confuse user.

**Comment by gurevichmark** [comment]
@robin2008 I tried to catch 2 different errors here:
1. When doing `rflash -d` if the Host does not power on, I want to suggest to the user to run `reventlog` to see if any useful errors are logged.
2. When running any `r*` hardware control commands to openbmc node, login will fail with 502 error if REST server is not running. I am sure there could be other reasons for this error, but in my message I just wanted to direct the user to check the REST server. Currently we give no clue as to why login failed.

**Comment by gurevichmark** [comment]
Resolves #6173

**Comment by gurevichmark** [comment]
Closes #6173

**Pull request merged**
