### PR TITLE
[go-xcat] Ignore any error of `yum clean metadata`

### PR DESCRIPTION
**Pull request by neo954**

### CODE REVIEW

**Comment by hu-weihua** [comment]
@neo954 , could you offer some description for this pull request? thanks

**Comment by neo954** [comment]
This patch will let the script ignore any error from `yum clean metadata`. Since this error is not important. If the script still reach error when do `yum update` later. It will do the error handling there.

**Comment by hu-weihua** [comment]
I have reviewed the change and agree to merge, thanks @neo954.

**Comment by neo954** [comment]
Thanks @hu-weihua

**Pull request merged**
