### PR TITLE
Propagate signal via ssh even though pipe broken can not be detected

### PR DESCRIPTION
**Pull request by chenglch**
Add `-tt` option to force tty allocation when running ssh command

close-issue: #1609

### CODE REVIEW

**Comment by zet809** [comment]
Since xdsh can be used for RH, ubuntu, sles, switch, HMC, we need to verify whether this option works on those platforms.

**Comment by daniceexi** [comment]
@chenglch Could you give some explanation of why 'ssh -tt' helps for this issue?

**Comment by chenglch** [comment]
@daniceexi  I can't explain too much for the -tt option. Ansible also use this option by default if ssh connection is used. One thing I can confirm is that  the signal code can not be transferred to the sshd side without -t option.  

Some information from the man page of ssh
-t      Force pseudo-tty allocation.  This can be used to execute arbitrary screen-based programs on a remote machine, which can be very useful, e.g. when implementing menu services.
             **Multiple -t options force tty allocation, even if ssh has no local tty**.

Like @zet809 mentioned, I think this should be a test driven patch, I'm not sure if some platform do not support this option, or some scripts can not be executed with prompt(enable by -t) enabled.

**Comment by daniceexi** [comment]
@chenglch Get it. Thanks.

**Comment by daniceexi** [comment]
Then I think we can merge it and label this issue as test-required

**Pull request merged**
