### PR TITLE
Update the documentation to use diskful instead of diskfull

### PR DESCRIPTION
**Pull request by whowutwut**
Update the documentation pages to use "diskful" instead of "diskfull"

Address Issues #298

### CODE REVIEW

**Comment by whowutwut** [comment]
I didn't rename the file service_node_for_diskfull.rst in the advance/hierarchy.. I think @pdlun92  is making that change with one of his pull requests.

**Comment by whowutwut** [comment]
@caomengmeng , I did not realize this pull request had conflict.   I just resolved it, can you review and merge tomorrow?

**Comment by whowutwut** [comment]
@caomengmeng  is okay to merge in?

**Comment by whowutwut** [comment]
@caomengmeng  Can you merge this pull request when you get a chance? I fixed the conflicts again

**Comment by whowutwut** [comment]
@pdlun92  Can you review this pull request, it's just changing the "diskfull" -> "diskful"

**Comment by pdlun92** [comment]
a couple other "diskfull" references I found:
```
docs/source/advanced/hierarchy/index.rst:   service_node_for_diskfull.rst
docs/source/guides/admin-guides/manage_clusters/common/kvm/manage_vm.rst:   **Note**: The attribute *
*vmstorage** is only valid for diskfull VM node.

```
as well as several in the `docs/source/guides/admin-guides/references/` directory. 

Not sure which, if any, should be included in this commit

**Comment by whowutwut** [comment]
Thanks, let me update and capture those..

**Comment by whowutwut** [comment]
@pdlun92  I think I got most of the doc changes related to that now...

**Pull request merged**
