### PR TITLE
Make travis script go ahead when it failed to get PR information after max retries

### PR DESCRIPTION
**Pull request by robin2008**
### The modification include

- Make travis continue to finish the real test when it failed to get the PR information from github

- and redo the non-finished PR format checking at the end if all testing is passed.

### CODE REVIEW

**Comment by hu-weihua** [comment]
It is ok for me, thanks  @robin2008 .

**Comment by hu-weihua** [comment]
It is ok for me, thanks  @robin2008 .

**Comment by gurevichmark** [comment]
@robin2008 The comment on line 116 still says "return error".

**Comment by robin2008** [comment]
Yes, it still return error, all non-zero code is error,  but here I doesn't comment it very clearly as it is an special error.

**Pull request merged**
