### PR TITLE
Replace some die calls with exit and add undef for global variable

### PR DESCRIPTION
**Pull request by gurevichmark**
This pull request fixes the problem reported by issue #932 .

1. Replace some `die` statements with printing of the message to the screen and `exit`. This will display a more user friendly message in cases where the problem could be the user error.
2. In cases where `die` is more appropriate, add `undef $hypconn` before dying. This will free a global variable `$hyconn` and exit without the hang.

### CODE REVIEW

**Comment by whowutwut** [comment]
On the places where you still keep the die around, does the program exit but now does not have the "Plugin bug" message.. or it just does not hang anymore?

**Comment by gurevichmark** [comment]
The places where I left `die` appear to be less of user error and more of something we did not expect to happen. In those cases the error will still be "Plugin bug", it just will not hang.

**Comment by daniceexi** [comment]
@gurevichmark 
I don't have time to investigate when the kvm.pm started to use the ``CAT::SvrUtils::sendmsg`` to display message, but it was NOT the correct way. Since all the ``CAT::SvrUtils::sendmsg`` will call the same ``$callback`` to pass message to xcatclient, if there are multiple kvmhost processes are forked, there might be conflict.

The correct way is to use the return like following to pass message back.
~~~~
1079         return (1, "Unable to find current location of $node");
~~~~

And please check if using ``return``, do we still need to ``undef $hypconn;``?

**Comment by gurevichmark** [comment]
Changed pull request to use `return` instead of the `exit` to return error message and exit without the hang. As the result, caller of the subroutine had to change to detect the error condition and do its own `return`. I also removed the `undef $hypconn` statements that I added in the previous merge, because I do not know how to test all those code paths.

Therefore this pull request only fixes the problem reported by the issue #932. If other issues about `die` hangs from kvm.pm get reported, they will be fixed under a different pull request.

**Comment by gurevichmark** [comment]
@daniceexi Can you please review these latest changes.

**Comment by daniceexi** [comment]
I have reviewed the change and agree to merge.

**Pull request merged**
