### PR TITLE
support rflash for firestone machine, need to verify with Firestone m…

### PR DESCRIPTION
**Pull request by zet809**
…achine

### CODE REVIEW

**Comment by whowutwut** [comment]
Should this change wait until it's verified with the Firestone machine before it's merged into the xcat2?

**Comment by daniceexi** [comment]
@whowutwut 
1. The code is independent with other features, so it's safe to check in even without real test.
2. We will try to wait for the ready of JMET machine, but if it still cannot ready before we make all the code review done, we will check in the code otherwise this task will hang.

Generally for this kind of case that task depends on other stuff, I'd like to check in code first to make a milestone so that people could put effort on other task. Of course that check in should not affect ohter functionalities.

**Comment by daniceexi** [comment]
Has done the first round of review with Er Tao.

**Comment by whowutwut** [comment]
@daniceexi, ok sure. Sounds good

**Comment by zet809** [comment]
For the comments, I have checked in the modifications.

**Comment by daniceexi** [comment]
I have reviewed pull request and agree to check in.

**Pull request merged**
