### PR TITLE
Add a check for some required rpm package to successfully create the xcat-deps package

### PR DESCRIPTION
**Pull request by whowutwut**
Some internal build machines have been cleaned up and so as I was looking at the process to build the xcat-deps package on other machines we have, found that we can add some verification to make sure the machine has the correct packages to successfully build the linux xcat-dep packages. 

### The modification include

Testing for `rpm-sign` installed on the machine running `builddeps.sh` so that it actively checks that the machine we are running the deps build is configured correctly . 

Clean up commented code that was removed 3 years back 

### The UT result

```
[vhu@c910loginx01 xcat-core]$ rpm -q rpm-sign
package rpm-sign is not installed
[vhu@c910loginx01 xcat-core]$ ./builddep.sh UP=0
ERROR: rpm-sign is required to successfully create the xcat-deps package. Install and rerun.
[vhu@c910loginx01 xcat-core]$
```

### CODE REVIEW

**Comment by zet809** [comment]
hi, @whowutwut, beside this enhance, we may also need to block user to run this script from ubuntu node?

**Comment by whowutwut** [comment]
@zet809 Yes, good point, we should try to do something to prevent executing this on debian based OS...  With commit 9253791c71a37f9aff17018a55be9b2eeefbe018


### Debian
```
root@fs2vm110:~# cat /etc/*release*
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=16.04
DISTRIB_CODENAME=xenial
DISTRIB_DESCRIPTION="Ubuntu 16.04.4 LTS"
NAME="Ubuntu"
VERSION="16.04.4 LTS (Xenial Xerus)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 16.04.4 LTS"
VERSION_ID="16.04"
HOME_URL="http://www.ubuntu.com/"
SUPPORT_URL="http://help.ubuntu.com/"
BUG_REPORT_URL="http://bugs.launchpad.net/ubuntu/"
VERSION_CODENAME=xenial
UBUNTU_CODENAME=xenial
root@fs2vm110:~# cat test.sh
if [ `/usr/bin/rpm -q -f /usr/bin/rpm >/dev/null 2>&1; echo $?` != 0 ]; then
        echo "ERROR: This script should only be executed on a RPM based Operation System."
        exit 1
fi
root@fs2vm110:~# ./test.sh
ERROR: This script should only be executed on a RPM based Operation System.
root@fs2vm110:~#
```

### RPM based
```
[root@mid05tor12cn05 ~]# cat /etc/*release*
NAME="Red Hat Enterprise Linux Server"
VERSION="7.5 (Maipo)"
ID="rhel"
ID_LIKE="fedora"
VARIANT="Server"
VARIANT_ID="server"
VERSION_ID="7.5"
PRETTY_NAME="Red Hat Enterprise Linux Server 7.5 (Maipo)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:redhat:enterprise_linux:7.5:GA:server"
HOME_URL="https://www.redhat.com/"
BUG_REPORT_URL="https://bugzilla.redhat.com/"

REDHAT_BUGZILLA_PRODUCT="Red Hat Enterprise Linux 7"
REDHAT_BUGZILLA_PRODUCT_VERSION=7.5
REDHAT_SUPPORT_PRODUCT="Red Hat Enterprise Linux"
REDHAT_SUPPORT_PRODUCT_VERSION="7.5"
Red Hat Enterprise Linux Server release 7.5 (Maipo)
Red Hat Enterprise Linux Server release 7.5 (Maipo)
cpe:/o:redhat:enterprise_linux:7.5:ga:server
[root@mid05tor12cn05 ~]# cat test.sh
if [ `/usr/bin/rpm -q -f /usr/bin/rpm >/dev/null 2>&1; echo $?` != 0 ]; then
        echo "ERROR: This script should only be executed on a RPM based Operation System."
        exit 1
fi
[root@mid05tor12cn05 ~]# ./test.sh
[root@mid05tor12cn05 ~]#
```

**Comment by whowutwut** [comment]
@zet809  I made some changes based on our internal discussion, please take a review again. Thanks!

**Comment by zet809** [comment]
Good to me, I agree to merge, thx @whowutwut

**Comment by zet809** [comment]
Hi, @whowutwut , since the CI is broken, @xuweibj  is helping debug the CI problem, once it is done, we can merge this PR.

**Comment by robin2008** [comment]
close and reopen to trigger a new CI

**Comment by zet809** [comment]
CI passed, so I merge this PR. Thx @whowutwut and @robin2008

**Pull request merged**
