### PR TITLE
Assume that any bmc that has nmap response on the openbmc_port is a openbmc server

### PR DESCRIPTION
**Pull request by whowutwut**
If the openbmc console port is returned by nmap, assume that it's openbmc

Resolves the bmcdiscover command for #4011 

Otherwise if the nmap state is anything other than `open` then we will fall into IPMI code, which is confusing...

### CODE REVIEW

**Comment by xuweibj** [comment]
Hi @whowutwut , I think this modify will cause another issue. Even node that mgt is ipmi will return info.
```
# nmap 50.3.17.1 -p 2200 -Pn

Starting Nmap 6.40 ( http://nmap.org ) at 2017-09-27 03:10 EDT
Nmap scan report for 50.3.17.1
Host is up (0.071s latency).
PORT     STATE  SERVICE
2200/tcp closed ici
```
I think maybe we could use closed to filter, if ``closed``, consider it as ipmi.

**Comment by whowutwut** [comment]
👍 Thanks for that comment, @xuweibj  I will make some changes tomorrow.

**Comment by whowutwut** [comment]
@xuweibj  I've updated this pull request.

**Comment by cxhong** [comment]
one of system hit this issue, I modified their code with  this PR.  worked fine.  will merge it.

**Pull request merged**
