### PR TITLE
Fix Ubuntu 18.04 postscript problem

### PR DESCRIPTION
**Pull request by neo954**
The pull request will fix issue #5351

### CODE REVIEW

**Comment by immarvin** [comment]
agree to merge

**Comment by chuckbrazie** [comment]
I am out of the office until 07/16/2018.

I am out of the office until  Monday July 16.


Note: This is an automated response to your message  "Re: [xcat2/xcat-core]
Fix Ubuntu 18.04 postscript problem (#5356)" sent on 7/2/18 9:01:31 AM.

This is the only notification you will receive while this person is away.

**Comment by chuckbrazie** [comment]
I am out of the office until 07/16/2018.

I am out of the office until  Monday July 16.


Note: This is an automated response to your message  "Re: [xcat2/xcat-core]
Fix Ubuntu 18.04 postscript problem (#5356)" sent on 7/2/18 9:06:34 AM.

This is the only notification you will receive while this person is away.

**Comment by chuckbrazie** [comment]
I am out of the office until 07/16/2018.

I am out of the office until  Monday July 16.


Note: This is an automated response to your message  "Re: [xcat2/xcat-core]
Fix Ubuntu 18.04 postscript problem (#5356)" sent on 7/2/18 9:06:41 AM.

This is the only notification you will receive while this person is away.

**Comment by chuckbrazie** [comment]
I am out of the office until 07/16/2018.

I am out of the office until  Monday July 16.


Note: This is an automated response to your message  "[xcat2/xcat-core] Fix
Ubuntu 18.04 postscript problem (#5356)" sent on 7/2/18 8:58:13 AM.

This is the only notification you will receive while this person is away.

**Pull request merged**
