### PR TITLE
Add rest api for the node template

### PR DESCRIPTION
**Pull request by chenglch**
- Add --template option for mkdef
- Add GET interface to list/show the /templates/node resource

### CODE REVIEW

**Comment by daniceexi** [comment]
add baiyuan to review this change

**Comment by chenglch** [comment]
Hi @bybai , two reasons:
1. Currently only template for nodes is supported in restapi , but we may also support the other resource like osimage etc in the future.
2.  The template operation like `lsdef --template -a` or `lsdef --template <template name>` is not associate with <noderange>, no node resource should be specified in the URL.

**Comment by bybai** [comment]
Hi @chenglch , 
In you pull request you just support :1, ``lsdef -t node --template``, 2, ``lsdef --template -a`` ;   ``lsdef --template <template name>`` is not in your code ?

**Comment by chenglch** [comment]
Hi @bybai , definitely inside.

**Comment by bybai** [comment]
I am ok to merge.

**Pull request merged**
