### PR TITLE
Enable switches to run findme for autodiscovery (#2662)

### PR DESCRIPTION
**Pull request by mattaezell**
This lays some groundwork for the autodiscovery part of #2662

### CODE REVIEW

**Comment by cxhong** [comment]
Thanks @mattaezell 
How did u able to send request?  did u create xml file?

**Comment by mattaezell** [comment]
@cxhong I copied some code from dodiscovery in genesis, but simplified it because we don't need to handle BMCs, etc.

Draft version at:
https://gist.github.com/mattaezell/f385baa5bdccf6f63145489f3c172da2

Feel free to adapt that into your #3085 PR

**Comment by zet809** [comment]
Hi, @cxhong , seems to me that when the switch send out the 'findme' request, it need to have 'nodetype=switch' attribute set, then our find_mac subroutine will search only switch node for this request. 
But, you are right that how to send a request is not included, you are reference xCAT-genesis-scripts/bin/dodiscovery for how to generate the findme request and send it to xCAT server.

Thx @mattaezell , do you think 'productname=cumulus' more make sense?

**Comment by mattaezell** [comment]
Hello @zet809.  As you noticed, by default, *find_mac* skips switches.  If *discoverswitch* is true, then it does not skip the switches. *nodetype=switch* is generic and could be used for any type of switch, Cumulus, Mellanox (maybe through Puppet integration), or some future product.  *productname=cumulus* might be an additional element to send in the discovery packet.

**Comment by cxhong** [comment]
@mattaezell , thanks so much for the scripts.  I think we can use for autodiscover cumulus process.

@zet809 , currently, the switchdiscover command used find_mac has special value for switch
````
xCAT-server/lib/xcat/plugins/switchdiscover.pm:        my $node = $macmap->find_mac($mac,0,1);
````
so, I think ```nodeype=switch```  should be good enough.

**Pull request merged**
