### PR TITLE
Simplify the steps to update forked repository

### PR DESCRIPTION
**Pull request by daniceexi**
Refer to http://10.4.14.20/developers/github/syncing_forks.html

### CODE REVIEW

**Comment by whowutwut** [comment]
I'm ok to merge this

**Comment by whowutwut** [comment]
I was just following these steps and just saw i was in a different branch...  should we add a step "git checkout master" before the "git pull upstream/master"...  otherwise we may update the wrong branch..

**Comment by daniceexi** [comment]
@whowutwut Yes I agree to add the 'git checkout master' before pull from upstream.

Since it's a reviewed checkin, I just check it in directly. See https://github.com/daniceexi/xcat-core/commit/529a8ba7c97c412f442f814d8940a684195fe43c

**Comment by samveen** [comment]
It may be advisable to introduce the use of `git stash` in there as well, so that the `git checkout master` doesn't wipe any of the uncommitted work.

**Pull request merged**
