### PR TITLE
To fix issue #761, made a mistake that make certificate generate failed

### PR DESCRIPTION
**Pull request by xuweibj**

### CODE REVIEW

**Comment by daniceexi** [comment]
I am good with the change.

**Comment by whowutwut** [comment]
@xuweibj  you need to put the issue into the text of the description for GitHub to make the cross references, not just in the abstract.

**Comment by xuweibj** [comment]
@whowutwut  OK, I will add more information.
The problem is because I made a mistake when added subjectAltName into openssl.cnf, so that the certificate generated failed. Using the default of SSL_verify_mode of SSL_VERIFY_NONE for client
 is deprecated!

**Comment by daniceexi** [comment]
@xuweibj  Victor meant add the issue number in the description for cross reference. I put #761 in this comment, then this pull request will be seen in the issue page #761.

**Pull request merged**
