### PR TITLE
Rspconfig openbmc network

### PR DESCRIPTION
**Pull request by gurevichmark**
This pull request implements `rspconfig` command for openbmc to query `ip`, `netmask` and `gateway` values.
Network interfaces with multiple ip addresses are not supported.
Network interfaces with IPv6 addresses are not supported.
Vlan information currently not present in REST output, so `rspconfig` for now just displays "n/a"

Output:

1. Error message when network interface with multiple ip addresses is detected:
```
[root@stratton01 xcat]# rspconfig w5 ip gateway netmask vlan
[OpenBMC development support] Using this version of xCAT, ensure firmware level is at v1.99.6-0-r1, or higher.
w5: Interfaces with multiple IP addresses are not supported
[root@stratton01 xcat]#
```

2. Normal output:
```
[root@stratton01 xcat]# rspconfig w5 ip gateway netmask vlan
[OpenBMC development support] Using this version of xCAT, ensure firmware level is at v1.99.6-0-r1, or higher.
w5: BMC IP: 10.0.6.255
w5: BMC Netmask: 255.255.255.0
w5: BMC Gateway: 10.0.6.1 (default: n/a)
w5: BMC VLAN ID enabled: n/a
[root@stratton01 xcat]#
```

### CODE REVIEW

**Comment by xuweibj** [comment]
Hi, @gurevichmark , the code I think is OK.
But I run ``curl https://bmc/xyz/openbmc_project/network/enumerate`` against w5, I don't get URL has ``ipv4``. Is that the interface on w5 not the final version?
Another question, do we get the interface of setting network?

**Comment by gurevichmark** [comment]
Yes, it is hard to tell each time. The Austin "W" machines seem to change each day. @whowutwut wrote a script at /root/c910env/notes/openbmc/UT/Network/austin/list.sh. I run it each day to see which machines return needed network information. Today, w33 - 9.3.185.161 seems to return what I need, it appears to be running version `"v1.99.8-71-ge319c8c` of the BMC :

```
{
  "data": {
    "/xyz/openbmc_project/network/config": {
      "DefaultGateway": "9.3.185.1",
      "HostName": ""
    },
    "/xyz/openbmc_project/network/eth0": {
      "AutoNeg": 0,
      "DHCPEnabled": 0,
      "DomainName": [],
      "InterfaceName": "eth0",
      "MACAddress": "70:E2:84:14:20:30",
      "Nameservers": [],
      "Speed": 0
    },
    "/xyz/openbmc_project/network/eth0/ipv4/b10f1150": {
      "Address": "9.3.185.161",
      "Gateway": "0.0.0.0",
      "Origin": "xyz.openbmc_project.Network.IP.AddressOrigin.Static",
      "PrefixLength": 24,
      "Type": "xyz.openbmc_project.Network.IP.Protocol.IPv4"
    },
    "/xyz/openbmc_project/network/eth0/ipv6/9b2b0076": {
      "Address": "fe80::72e2:84ff:fe14:2030",
      "Gateway": "",
      "Origin": "xyz.openbmc_project.Network.IP.AddressOrigin.LinkLocal",
      "PrefixLength": 64,
      "Type": "xyz.openbmc_project.Network.IP.Protocol.IPv6"
    },
    "/xyz/openbmc_project/network/host0/intf": {
      "MACAddress": "00:00:00:00:00:00"
    },
    "/xyz/openbmc_project/network/host0/intf/addr": {
      "Address": "0.0.0.0",
      "Gateway": "0.0.0.0",
      "Origin": "xyz.openbmc_project.Network.IP.AddressOrigin.Static",
      "PrefixLength": 0,
      "Type": "xyz.openbmc_project.Network.IP.Protocol.IPv4"
    }
  },
  "message": "200 OK",
  "status": "ok"
}
```

**Comment by whowutwut** [comment]
@gurevichmark can you run the externals against that machine you posted above? i'd like to see the REST output compared with the rspconfig output.  My question why the Default Gateway is (n/a)...

**Comment by gurevichmark** [comment]
Not sure what the output of the `curl` command was at the time I got this output, but running this command to verify the data made me catch a bug which is fixed in the new pull request.

Next will attach the `curl` and `rspconfig` output together

**Comment by gurevichmark** [comment]
```
[root@stratton01 xcat]# rspconfig w5 ip gateway netmask
[OpenBMC development support] Using this version of xCAT, ensure firmware level is at v1.99.6-0-r1, or higher.
w5: BMC IP: 9.3.185.161
w5: BMC Netmask: 255.255.255.0
w5: BMC Gateway: 0.0.0.0 (default: 9.3.185.1)
[root@stratton01 xcat]#
```
```
{
  "data": {
    "/xyz/openbmc_project/network/config": {
      "DefaultGateway": "9.3.185.1",
      "HostName": ""
    },
    "/xyz/openbmc_project/network/eth0": {
      "AutoNeg": 0,
      "DHCPEnabled": 0,
      "DomainName": [],
      "InterfaceName": "eth0",
      "MACAddress": "70:E2:84:14:20:30",
      "Nameservers": [],
      "Speed": 0
    },
    "/xyz/openbmc_project/network/eth0/ipv4/b10f1150": {
      "Address": "9.3.185.161",
      "Gateway": "0.0.0.0",
      "Origin": "xyz.openbmc_project.Network.IP.AddressOrigin.Static",
      "PrefixLength": 24,
      "Type": "xyz.openbmc_project.Network.IP.Protocol.IPv4"
    },
    "/xyz/openbmc_project/network/eth0/ipv6/9b2b0076": {
      "Address": "fe80::72e2:84ff:fe14:2030",
      "Gateway": "",
      "Origin": "xyz.openbmc_project.Network.IP.AddressOrigin.LinkLocal",
      "PrefixLength": 64,
      "Type": "xyz.openbmc_project.Network.IP.Protocol.IPv6"
    },
    "/xyz/openbmc_project/network/host0/intf": {
      "MACAddress": "00:00:00:00:00:00"
    },
    "/xyz/openbmc_project/network/host0/intf/addr": {
      "Address": "0.0.0.0",
      "Gateway": "0.0.0.0",
      "Origin": "xyz.openbmc_project.Network.IP.AddressOrigin.Static",
      "PrefixLength": 0,
      "Type": "xyz.openbmc_project.Network.IP.Protocol.IPv4"
    }
  },
  "message": "200 OK",
  "status": "ok"
}
```

**Pull request merged**
