### PR TITLE
fix typo in if-clause in post.rhels7 

### PR DESCRIPTION
**Pull request by immarvin**
fix a typo in post.rhels7  to make it work as expected

### CODE REVIEW

**Comment by whowutwut** [comment]
Duplicate to Community Pull Request #3170

**Comment by whowutwut** [comment]
@hu-weihua This slipped through...  I added the label to it...  can we take a look at why we did not catch this issue? Could we have checked some return code and found errors?  The previous blame commit that touched this line seems from > 2 years ago?

**Comment by hu-weihua** [comment]
@whowutwut , test case just check the output and return code of command. Up to now, there is not a case catch error from log or console. That means if some script have error and throw error just into log or console, test case can't catch such error. 

But from other standpoint, if there is such error, our xcat command should return error code and show error information in STDOUT.  It is little hard for test case to go through log.  Maybe ``xCAT Probe`` can do it, than test case  leverage the output of ``xCAT Probe`` to do judgement.

For script syntax problem, maybe the CI project which we are doing will helpful.

**Comment by robin2008** [comment]
@hu-weihua we don't care the script of syntax, but the final result of the user requirement.  For example:   here xCAT want the Linked interfaces are onboot=yes.  Or for un-linked interfaces are not, etc.

BTW: the ifcfg file may be modified also by other postscripts, so our test case checking is focusing the e2e result,  and if possible to check some key checkpoints in the whole processing.

**Pull request merged**
