### PR TITLE
add consport and taggedvlan attributes in openbmc table

### PR DESCRIPTION
**Pull request by xuweibj**
add consport and taggedvlan attributes in openbmc table

### CODE REVIEW

**Comment by zet809** [comment]
Looks good to me, I agree to merge.

**Comment by whowutwut** [comment]
@xuweibj What's the purpose for the console port?  If it changes from 2200 to something else??

**Comment by zet809** [comment]
Hi, @whowutwut , your are right. For example, for the qemu simulated openbmc environment, there must be most than 1 qemu VM(represent one openbmc) started on one host, then console client need to access different port of the host to forward data to the qemu VM.

**Comment by gurevichmark** [comment]
Not sure if another PR was used, but changes to Schema.pm file cause `.pod` man pages to get generated and `.rst` files to be built. The `.rst` files need to be checked in.

**Pull request merged**
