### PR TITLE
Add test cases for check exit code when abnormal commands were performed

### PR DESCRIPTION
**Pull request by neo954**
Add 2 cases in this pull request
These 2 cases are for issue #2636 
This pull request is for task #2702

[case 1]
Case Name: nodestat_usage
description: Test the exit code when no command line argument is passed to nodestat

[case 2]
Case Name: xdsh_permission_denied
description: Test the exit code when command xdsh failed

### CODE REVIEW

**Comment by immarvin** [comment]
hi @neo954 , please follow the rules in https://github.com/xcat2/xcat-process/blob/master/basic-process/The%20Template%20of%20Pull%20Request%20of%20Test%20Case.rst

**Comment by neo954** [comment]
@immarvin, please help on review this patch.

**Comment by immarvin** [comment]
hi @neo954 , please add the 
````
[case 1]
Case Name: nodestat_usage
description: Test the exit code when no command line argument is passed to nodestat

[case 2]
Case Name: xdsh_permission_denied
description: Test the exit code when command xdsh failed
````

to the header of each case

**Comment by neo954** [comment]
@immarvin, Test cases updated. Thanks.

**Comment by immarvin** [comment]
i am ok with the change

**Pull request merged**
