### PR TITLE
Revise the man page of noderange. Describe the special characters need to be escaped more clear

### PR DESCRIPTION
**Pull request by neo954**
This pull request fix issue #3319

### CODE REVIEW

**Comment by immarvin** [comment]
i am ok with the change

**Comment by daniceexi** [comment]
Mostly this issue happens on which shell?

**Comment by neo954** [comment]
@daniceexi, I think on all popular used shells, user will be affected with issue #3319. The list will including original Bourne shell, Bash, Ksh, csh, Tcsh, Z shell. All these shells use `*` and `~` for pathname pattern matching. Except csh, all other shells use `[` and `]` for filename globbing.

**Comment by whowutwut** [comment]
This one i think missed running `create_man_pages.py` to update the .rst

**Pull request merged**
