### PR TITLE
Fix issue 4477, if has node-<mac> will not create node-<mtms> for the same node

### PR DESCRIPTION
**Pull request by xuweibj**
#4477 

If has node named "node-<mac>", update node-<mac> data but not create new node definition.

```
# bmcdiscover --range 172.11.139.2 -w
172.11.139.2: Detected openbmc, attempting to obtain system information...
Writing node-70e284142897 (172.11.139.2,8335-GTC,1318D3A,,,mp,bmc,,) to database...
```

### CODE REVIEW

**Comment by zet809** [comment]
Looks good to me, I agree to merge, thx!

**Comment by whowutwut** [comment]
@xuweibj Can you clarify the behavior... 

If there is already a `node-mac` in the xCAT database, we would update that with the information from bmcdiscover? 

What if there is no `node-mac` and we have MT and SN information?  It would write `node-MT-SN` instead?

**Comment by xuweibj** [comment]
@whowutwut 
The login as below:

1. There is no defined mtms_node and mac_node
    1.1 we get all information including mtms and mac, create mtms_node
    1.2 we get only mtms or mac information, create mtms_node or mac_node
2. There is defined mtms_node, only update mtms_node
3. There is defined mac_node, update the mac_node even we get mtms information
4. There are defined mtms_node and mac_node, update mtms_node

**Comment by whowutwut** [comment]
@xuweibj  
I think for 1.2, you mean "If we only get mac information, create mac_node"? 

Then for 4. I guess we will not fix this scenario right?  How will the clean up happen? 
If there is mtms_node and mac_node, and we update mtms_node and discovery will clean up mtms_node, we will still be left with mac_node right?


 I guess this is OK... :)  hopefully moving forward, this will prevent both nodes from showing up on the xCAT node definition.

**Comment by xuweibj** [comment]
@whowutwut  
Sorry, you are right, I made typo in 1.2.
For 4, if discovery success, will clean up all mtms_node and mac_node. This have been solved before.

**Comment by whowutwut** [comment]
Thanks!

**Pull request merged**
