### PR TITLE
Improve the content in the xCAT kit related command man page, better formatting on RTD 

### PR DESCRIPTION
**Pull request by whowutwut**
I'm working with some of the kit related commands so I spent some time to improve the format of the .pod files so they would render a little nicer on RTD. 

Also clean up some of the text wording

### CODE REVIEW

**Comment by whowutwut** [comment]
@bybai  If you cannot get around to review before your holiday, I will assign to Casandra.

**Comment by whowutwut** [comment]
@bybai, yes this is an issue that I have noticed when we are rendering man pages over on RTD.  @gurevichmark actually working on a fix for it where the ``create_man_pages.py`` script will apply a sed to the .rst files so that the double dash is rendered correctly.  I will let his changes fix the issues for all the man pages.

**Comment by whowutwut** [comment]
@cxhong  Can you review and merge if acceptable.  Regarding the comment @bybai  mentioned, Mark is working on a fix that will address all the pages.

**Comment by gurevichmark** [comment]
Double dash and other man page formatting problems have been fixed by pull requests 703, 710 and 717

**Pull request merged**
