### PR TITLE
add more debug information in the case

### PR DESCRIPTION
**Pull request by tingtli**
### The PR is to do task https://github.ibm.com/xcat2/task_management/issues/18

The UT 
```
******************************
------START::nodeset_cmdline::Time:Fri May 10 03:39:12 2019------

RUN:perl /opt/xcat/share/xcat/tools/autotest/testcase/genesis/genesistest.pl  -n c910f03c09k11  -g [Fri May 10 03:39:12 2019]
ElapsedTime:2 sec
RETURN rc = 0
OUTPUT:
20190510 2737 Notice: [2737]:Check if genesis packages are installed on mn...............
20190510 2737 Notice: genesis packages are installed
xcat management node is 10.3.9.9
CHECK:rc == 0	[Pass]

RUN:perl /opt/xcat/share/xcat/tools/autotest/testcase/genesis/genesistest.pl -n c910f03c09k11 -d [Fri May 10 03:39:14 2019]
ElapsedTime:353 sec
RETURN rc = 0
OUTPUT:
xcat management node is 10.3.9.9
20190510 2758 Notice: [2758]:Running runcmd test...............
20190510 2758 Notice: no runcmd scripts for test prepared.
The input parameter is 1
20190510 2758 Warning: try to run xdsh c910f03c09k11 to check the results again
20190510 2758 Notice: [2758]:Running runcmd test success...............
CHECK:rc == 0	[Pass]

RUN:perl /opt/xcat/share/xcat/tools/autotest/testcase/genesis/genesistest.pl  -n c910f03c09k11 -c [Fri May 10 03:45:07 2019]
ElapsedTime:51 sec
RETURN rc = 0
OUTPUT:
xcat management node is 10.3.9.9
20190510 2978 Notice: [2978]:clear genesis test enviroment...............
20190510 2978 Notice: [2978]:clear genesis test enviroment success...............
CHECK:rc == 0	[Pass]

RUN:cat /tmp/genesistestlog/* [Fri May 10 03:45:58 2019]
ElapsedTime:0 sec
RETURN rc = 0
OUTPUT:
20190510 2737 Notice: [2737]:Check if genesis packages are installed on mn...............
20190510 2737 Notice: genesis packages are installed
20190510 2758 Notice: [2758]:Running runcmd test...............
20190510 2758 Notice: no runcmd scripts for test prepared.
20190510 2758 Warning: try to run xdsh c910f03c09k11 to check the results again
20190510 2758 Notice: [2758]:Running runcmd test success...............
20190510 2978 Notice: [2978]:clear genesis test enviroment...............
20190510 2978 Notice: [2978]:clear genesis test enviroment success...............

------END::nodeset_cmdline::Passed::Time:Fri May 10 03:45:58 2019 ::Duration::406 sec------
------Total: 1 , Failed: 0------
```

### CODE REVIEW

**Comment by hu-weihua** [comment]
@tingtli, If you just print messages out which are written into ``/tmp/genesistestlog/*`` by function ``send_msg``,  why not add ``print`` into  ``send_msg`` directly?  It is a better way to implement what you want to do.

But these are not what task [18](https://github.ibm.com/xcat2/task_management/issues/18) plan to do. Even we did not change anything, the message you added have been logged into ``/tmp/genesistestlog/*``,  we have already got them in test case log. The log we want to get are more useful log. For example, if anyone else to read the log, he or she can know quickly what the case is testing and how it is going on. The original logs did not show any useful information. 

```
20190508 2715 Notice: [2715]:Check genesis file...............
20190508 2715 Notice: genesis file available
20190508 2736 Notice: [2736]:Running runcmd test...............
20190508 2736 Notice: no runcmd scripts for test prepared.
20190508 2736 Warning: try to run xdsh to check the results again
20190508 2736 Notice: [2736]:Running runcmd test success...............
20190508 2973 Notice: [2973]:clear genesis test enviroment...............
20190508 2973 Notice: [2973]:clear genesis test enviroment success...............
```
It is hard for reader to know the test logic and what happen during running. Could you make the log easier for reader to understand? thanks.

**Comment by tingtli** [comment]
@hu-weihua  sure, we can change the print message into send_msg function.
The log which saved under /tmp will be lost since the test machine is reused.

I also don't think the message is very helpful but i don't think it's easy to describe and indicate very easily what happened in the test with a sentence. 

The warning message's usage is to give indication that you can find the place where the error happens.

**Comment by hu-weihua** [comment]
@tingtli , in fact, the log has been printed by ``cmd:cat /tmp/genesistestlog/*``, that won't lost after test cluster destroyed.

What's the point of refining is to make the message more meaningful. You have taken the job of going through regression result every day. If we have no chance to rerun the failed case, how could you adjust what was going on of each failure depending on the logs?  I think that will help you to make sure what kind of information is useful.

**Comment by hu-weihua** [comment]
@tingtli , let merge it first. Maybe you can find what message will be helpful after maintaining automation test environment for a while.

**Pull request merged**
