### PR TITLE
Add support for the rvitals option for openbmc based on the defined API

### PR DESCRIPTION
**Pull request by whowutwut**
_Based on the OpenBMC Sensor API, complete the development code
for the supported options based on the possible values that are
currently allowed to be returned.  As more data is added, the code
should be able to handle the printing of the data automatically_

Adds support for `rvitals`, as part of issue #2816 

Looking at the [Value.yaml](https://github.com/openbmc/phosphor-dbus-interfaces/blob/fca9cc6df49f623126858ad7ec0a13ffae17c3f6/xyz/openbmc_project/Sensor/Value.interface.yaml) file as part of the openbmc/sensor API, complete the support for the options in `rvitals`

### External Interfaces supported based on the possible valid values: 

```
rvitals noderange [temp|voltage|wattage|fanspeed|power|length|all]
```

### Example output:

No options specified
```
[root@fs2vm110 ~]# rvitals p9euh02 
p9euh02: fan_tach/fan1: 7470 RPMS
p9euh02: temperature/pcie: 29.75 C
p9euh02: fan_tach/fan2: 7560 RPMS
p9euh02: fan_tach/fan0: 7440 RPMS
p9euh02: fan_tach/fan3: 7530 RPMS
```

Getting `temp` only
```
[root@fs2vm110 ~]# rvitals p9euh02 temp
p9euh02: temperature/pcie: 29.75 C
```

Getting `fanspeed` only:
```
[root@fs2vm110 ~]# rvitals p9euh02 fanspeed
p9euh02: fan_tach/fan1: 7440 RPMS
p9euh02: fan_tach/fan2: 7530 RPMS
p9euh02: fan_tach/fan0: 7500 RPMS
p9euh02: fan_tach/fan3: 7500 RPMS
```

### CODE REVIEW

**Comment by whowutwut** [comment]
@gurevichmark Can you double check the usage formatting. Should I fix for all the other server specific usage format?

**Comment by whowutwut** [comment]
Another question @gurevichmark @xuweibj , Should we be printing out all the info at line 1215:
```
     print "$node: DEBUG Processing command: rvitals $grep_string \n";
     print Dumper(%{$response_info->{data}}) . "\n";  <==== 
```

**Comment by gurevichmark** [comment]
@whowutwut Few comments:
1. I spoke to Brad yesterday on Slack. He said Witherspoon systems will only support 4 vitals: fan speed, temperature, power and voltage. So I think we should remove everything else from usage and only allow those 4 in the code.
2. I think the labels we display should be different. Currently code just displays a path we get back in response data, like `fan_tach/fan2`, but  we should replace it with something more readable, similar to `rvitals` for `ipmi` machines. For example:
```
[root@fs1 ~]# rvitals frame45cn07 fan
frame45cn07: Fan 1: 4300 RPM
frame45cn07: Fan 2: 4300 RPM
frame45cn07: Fan 3: 4300 RPM
frame45cn07: Fan 4: 4300 RPM
[root@fs1 ~]#
```
3. I suspect there will be more temperature vitals than the one we currently get back - `temperature/pcie`. For example, for the `ipmi` managed systems, we currently get 7 categories of temperature:
```
[root@fs1 ~]# rvitals frame45cn07 temp
frame45cn07: Ambient Temp: 27 C (81 F)
frame45cn07: CPU Core Temp 1: 51 C (124 F)
frame45cn07: CPU Diode 1: 35 C (95 F)
frame45cn07: CPU1 Temp: 54 C (129 F)
frame45cn07: DIMM1 Temp: 33 C (91 F)
frame45cn07: GPU Temp 1: 33 C (91 F)
frame45cn07: Mem Buf Temp 1: 45 C (113 F)
```
4. The purpose of `Dumper` on line 1215 is to display all the response data we get back from REST call. As more and more vitals are added, we will need to see what item paths are returned in order to convert them to more readable labels.

**Comment by whowutwut** [comment]
@gurevichmark  Some response

1) Yes, agreed.  But he also mentioned that if we wanted to generically support future machines that use openbmc, we could also do that. I think some of the options won't display anything, perhaps this is OK.  

2) Agree with this, but the way you have decided to implement this allows us to pass back anything that is exposed in the BMC without the need to have additional code to massage the output.  It would be better in the long run regarding maintainability to just leave the response as such. 

3) It seems like from the API all the temperatures are going to be reported back in DegreesC which is good, we don't need to handle different cases. 

4) I think if we choose not to massage the output and just pass the direct output back ... we don't need this dumper line... we could always add it back.    

I'll look to maybe make some additional changes tomorrow

**Comment by xuweibj** [comment]
The code is OK to me if the interface is right. 
For line 1215, I think we should only print it when we debug.

**Comment by whowutwut** [comment]
@xuweibj @gurevichmark Completed the code changes for this pull request, it's ready for merge after review again.  

With the latest changes I massaged the output a little more and just used the last word of the data to be the keyword of the sensor,  Now we do not have to care about what is returned and just simply pass through, formatted.  

Before changes: 
```
[root@stratton01 openbmc]# rvitals p9euh01
p9euh01: fan_tach/fan1: 7828 RPMS
p9euh01: temperature/pcie: 28.75 C
p9euh01: fan_tach/fan2: 7812 RPMS
p9euh01: fan_tach/fan0: 7828 RPMS
p9euh01: fan_tach/fan3: 7828 RPMS
```

After changes:
```
[root@fs2vm110 ~]# rvitals p9euh01
p9euh01: Fan0: 7845 RPMS
p9euh01: Fan1: 7828 RPMS
p9euh01: Fan2: 7828 RPMS
p9euh01: Fan3: 7861 RPMS
p9euh01: Pcie: 28.687 C
```

With the latest openbmc, we get additional values...  they are handled without and extra dev code!
```
[root@fs2vm110 ~]# rvitals p9euh02
p9euh02: Fan0: 0 RPMS
p9euh02: Fan1: 0 RPMS
p9euh02: Fan2: 0 RPMS
p9euh02: Fan3: 0 RPMS
p9euh02: Pcie: 28.812 C
p9euh02: Rail 1 Voltage: 5.54 Volts
p9euh02: Rail 2 Voltage: 0.291 Volts
p9euh02: Rail 3 Voltage: 1.153 Volts
p9euh02: Rail 4 Voltage: 0.19 Volts
p9euh02: Rail 5 Voltage: 0.1 Volts
p9euh02: Rail 6 Voltage: 0 Volts
p9euh02: Rail 7 Voltage: 0.163 Volts
p9euh02: Rail 8 Voltage: 0.1 Volts
p9euh02: Rail 9 Voltage: 0.1 Volts
p9euh02: Rail 10 Voltage: 0.3 Volts
p9euh02: Rail 11 Voltage: 0.163 Volts
p9euh02: Rail 12 Voltage: 0.164 Volts
p9euh02: Rail 13 Voltage: 0.1 Volts
p9euh02: Rail 14 Voltage: 0.2 Volts
p9euh02: Rail 15 Voltage: 0.1 Volts
p9euh02: Rail 16 Voltage: 0.1 Volts
```

**Comment by whowutwut** [comment]
In our meeting today, reviewing this pull request resulted in the following comments: 
* Change "length" to "altitude" to match API
* If there are 0 items, print out a message so that it doesn't look like an error.

**Pull request merged**
