### PR TITLE
Abandon ssl2 support

### PR DESCRIPTION
**Pull request by neo954**
This pull request fix issue #5351.

### CODE REVIEW

**Comment by neo954** [comment]
```
# openssl s_client -no_ssl3 -no_ssl2 -connect 10.3.1.9:3001 -rand /bin/nice
s_client: Option unknown option -no_ssl2
s_client: Use -help for summary.
```

**Comment by daniceexi** [comment]
@neo954 Gong Jie, it's find for the new version, but how about the old version?

**Comment by chuckbrazie** [comment]
I am out of the office until 07/16/2018.

I am out of the office until  Monday July 16.


Note: This is an automated response to your message  "Re: [xcat2/xcat-core]
Abandon ssl2 support (#5358)" sent on 7/2/18 10:12:33 AM.

This is the only notification you will receive while this person is away.

**Comment by chuckbrazie** [comment]
I am out of the office until 07/16/2018.

I am out of the office until  Monday July 16.


Note: This is an automated response to your message  "[xcat2/xcat-core]
Abandon ssl2 support (#5358)" sent on 7/2/18 10:04:32 AM.

This is the only notification you will receive while this person is away.

**Comment by chuckbrazie** [comment]
I am out of the office until 07/16/2018.

I am out of the office until  Monday July 16.


Note: This is an automated response to your message  "Re: [xcat2/xcat-core]
Abandon ssl2 support (#5358)" sent on 7/2/18 10:11:22 AM.

This is the only notification you will receive while this person is away.

**Comment by chuckbrazie** [comment]
I am out of the office until 07/16/2018.

I am out of the office until  Monday July 16.


Note: This is an automated response to your message  "Re: [xcat2/xcat-core]
Abandon ssl2 support (#5358)" sent on 7/2/18 10:09:51 AM.

This is the only notification you will receive while this person is away.

**Comment by chuckbrazie** [comment]
I am out of the office until 07/16/2018.

I am out of the office until  Monday July 16.


Note: This is an automated response to your message  "Re: [xcat2/xcat-core]
Abandon ssl2 support (#5358)" sent on 7/2/18 10:14:26 AM.

This is the only notification you will receive while this person is away.

**Comment by chuckbrazie** [comment]
I am out of the office until 07/16/2018.

I am out of the office until  Monday July 16.


Note: This is an automated response to your message  "Re: [xcat2/xcat-core]
Abandon ssl2 support (#5358)" sent on 7/2/18 3:01:39 PM.

This is the only notification you will receive while this person is away.

**Comment by neo954** [comment]
See #5365.

**Comment by chuckbrazie** [comment]
I am out of the office until 07/16/2018.

I am out of the office until  Monday July 16.


Note: This is an automated response to your message  "Re: [xcat2/xcat-core]
Abandon ssl2 support (#5358)" sent on 7/3/18 8:26:30 AM.

This is the only notification you will receive while this person is away.

**Comment by chuckbrazie** [comment]
I am out of the office until 07/16/2018.

I am out of the office until  Monday July 16.


Note: This is an automated response to your message  "Re: [xcat2/xcat-core]
Abandon ssl2 support (#5358)" sent on 7/3/18 8:09:35 AM.

This is the only notification you will receive while this person is away.

**Comment by daniceexi** [comment]
@immarvin thanks for your explanation. I thought the removing of ``-no_ssl2`` might just cause security issue, but you said it caused some failure on sles11.4, interesting.

**Comment by chuckbrazie** [comment]
I am out of the office until 07/16/2018.

I am out of the office until  Monday July 16.


Note: This is an automated response to your message  "Re: [xcat2/xcat-core]
Abandon ssl2 support (#5358)" sent on 7/3/18 10:36:25 AM.

This is the only notification you will receive while this person is away.

**Pull request merged**
