### PR TITLE
issue 1191: do retry when update dns record replies NOTAUTH

### PR DESCRIPTION
**Pull request by daniceexi**

### CODE REVIEW

**Comment by whowutwut** [comment]
@bybai  Can you provide a patch file for this change for xCAT 2.9.1? 
FYI @cxhong

**Comment by bybai** [comment]
Hi @whowutwut ,
I do not find upstream/2.9.1 from git. 
Another thing, the 'NOAUTH' issue from ESS can work well now. It is usage issue, not caused by code. I do not know they want to change their code or not.

**Comment by zet809** [comment]
@bybai What @whowutwut meaning is the upstream/2.9 branch. It shall be 2.9.4 right now.

**Comment by whowutwut** [comment]
@bybai Thanks, I see that in the email exchanges.  @zet809  ESS is using xCAT 2.9.1 version, so we cannot just apply the patch to 2.9.4 and then give them a patch file.. unless there are no conflicts..  But for now, I think we don't need to do anything here.

**Pull request merged**
