### PR TITLE
add support for multiple pkglist for ubuntu

### PR DESCRIPTION
**Pull request by immarvin**
fix issue https://github.com/xcat2/xcat-core/issues/756

### CODE REVIEW

**Comment by whowutwut** [comment]
@immarvin  Can we add some description to the pull requests? For example if we can have a small description describing the changes, it will be much easier for the reviewer to review the code with some context.  The issue describes the problem but does not talk about the intended solution.  In the issue we discuss about printing an error message, but it looks like this is not what is being done in this pull request.   If we can show the example ERROR preseed and what the preseed will look like after. 

If i understand the code right, we are going to parse through the include file and fix the error so that it's correct for Ubuntu preseed file?  I don't know if we should do that because it masks the format of a preseed file....

**Comment by immarvin** [comment]
hi @whowutwut , what do you mean by "masks the format of a preseed file"?

**Comment by daniceexi** [comment]
@immarvin I known in the xcat, it's not easy always to display an error/warning message in any code. But it's easy to call the **xCAT::MsgUtils->trace** to generate a message to xcat/cluster.log. Could you add some trace log for the code you changed?

**Comment by whowutwut** [comment]
@immarvin  Sorry, I'm not familiar with the preseed file for ubuntu..  so maybe my understanding is wrong.   In your comments in the issue...  you said that the user should create a new package list file, with multiple includes.   So this is what the code is parsing through right? 

How did we get into this scenario where xCAT leaves a line in the preseed file after nodeset? 
````
d-i pkgsel/include string #INCLUDE_DEFAULT_PKGLIST_PRESEED#
````

I think in that scenario we need to put out an error message.  I don't see that in the pull request.  Is this very different behavior than on RHEL/SLES?

**Comment by immarvin** [comment]
hi @whowutwut , I agree that we should throw a message out if the pkglists in osimage.pkglist or "#INCLUDE xxxxxxxxx#" does not exist.

My fix is to support multiple pkglist files in ubuntu. The osimage.pkglist can be a list of pkglist files seperated with ",". "nodeset" will expand the "#INCLUDE xxx#" entries in all the specified pkglist files, then  substitute  "#INCLUDE_DEFAULT_PKGLIST_PRESEED#" in preseed template with the package list specified in the pkglist files.  Error message will be thrown out when the specified pkglist cannot be opened.

**Comment by immarvin** [comment]
I have updated the code

**Comment by immarvin** [comment]
Currently, the multiple package list is not supported on Redhat and Sles, open a ticket https://github.com/xcat2/xcat-core/issues/851 for redhat and sles

**Comment by daniceexi** [comment]
@immarvin I am not sure the root cause why @chenglch made a new subroutine **debian_includefile** for the debian specific. Invite @chenglch to review this change.

**Comment by immarvin** [comment]
hi @daniceexi , is @cxhong made the change?

**Comment by daniceexi** [comment]
@immarvin right, the subroutine **debian_includefile** made by @chenglch.

**Comment by daniceexi** [comment]
@immarvin  @chenglch  Sorry, My fault, should be @cxhong!

**Comment by cxhong** [comment]
debian_includefile was a fix for this issue:
https://sourceforge.net/p/xcat/bugs/4475/

I will try to recreate this....

**Comment by daniceexi** [comment]
@cxhong Did you make any progress?

**Comment by cxhong** [comment]
I ran both diskfull and diskless test on my test environment: with current code , and didn't hit any issues with  this compute pkglist file :

````
# cat compute.pkg
bash
nfs-common
openssl
isc-dhcp-client
libc-bin
openssh-server
openssh-client
wget
vim
ntp
rsync
busybox-static
gawk
dnsutils
#INCLUDE:/tmp/include_pkg#
#INCLUDE:/tmp/include1_pkg#
````

**Comment by daniceexi** [comment]
@cxhong Thanks for your effort. If no issue found, we assume @immarvin 's change work for Ubuntu too.

@tingtli Could you confirm do we have test case to cover the #INCLUDE function in the pkglist?

**Comment by daniceexi** [comment]
Then I agree to merge it now.

**Pull request merged**
