### PR TITLE
support rhelhpc6.8 and 7.2 for ticket 1955

### PR DESCRIPTION
**Pull request by fenggaobj**
support  rhelhpc6.8 and 7.2
https://github.com/xcat2/xcat-core/issues/1955

### CODE REVIEW

**Comment by immarvin** [comment]
agree to merge

**Comment by whowutwut** [comment]
Does the copycds not automatically detect these versions?

**Comment by immarvin** [comment]
currently, rhelhpc release info are not detected automatically in anaconda.pm

**Comment by immarvin** [comment]
hi @whowutwut , I made some investigation and opened a ticket on this request, see https://github.com/xcat2/xcat-core/issues/2014

**Pull request merged**
