### PR TITLE
Early support for RHEL 8 Alpha Base OS diskful installation

### PR DESCRIPTION
**Pull request by neo954**
**Features**
* Diskful compute node deployment support
* xCAT partition file, partition script support
* Revised LVM partition scheme by default
* Use ext4 file system by default

**Limitations**
* The Kickstart post-installation script is blank now
* Only default installation is tested

### CODE REVIEW

**Comment by neo954** [comment]
Refer https://github.com/xcat2/xcat2-task-management/issues/216

**Comment by neo954** [comment]
See https://github.com/xcat2/xcat2-task-management/issues/219

**Comment by neo954** [comment]
The difference between `pre.rh.rhels7` and `pre.rhels8`
```diff
$ diff -u pre.rh.rhels7 pre.rhels8
--- pre.rh.rhels7	2018-03-05 13:33:44.000000000 +0800
+++ pre.rhels8	2018-06-27 16:50:59.000000000 +0800
@@ -1,27 +1,30 @@
 export XCATDEBUGMODE="#TABLEBLANKOKAY:site:key=xcatdebugmode:value#"
-if [ "$XCATDEBUGMODE" = "1" ] || [ "$XCATDEBUGMODE" = "2" ]; then
+
+case "$XCATDEBUGMODE" in
+"1"|"2")
     set -x
-fi
+    ;;
+esac

-if grep n8r /proc/cmdline > /dev/null 2>&1;
+if grep -q n8r /proc/cmdline >/dev/null 2>&1
 then
-  stty crtscts
+    stty crtscts
 fi
 for x in 0 1 2 3 4 5 6 7 8
 do
-	mknod /dev/vcs$x c 7 $x
-	mknod /dev/vcsa$x c 7 $[$x+128]
+    mknod /dev/vcs$x c 7 $x
+    mknod /dev/vcsa$x c 7 $[$x+128]
 done
-chmod 644 /dev/vcs*
-chown root /dev/vcs*
-if [ -r /tmp/updates/etc/pki/tls/certs/ca-bundle.crt ]; then
-        cp -f /tmp/updates/etc/pki/tls/certs/ca-bundle.crt /etc/pki/tls/certs/
-fi
-
+chmod 0644 /dev/vcs*
+chown root.tty /dev/vcs*

+if [ -r /tmp/updates/etc/pki/tls/certs/ca-bundle.crt ]
+then
+    cp -f /tmp/updates/etc/pki/tls/certs/ca-bundle.crt /etc/pki/tls/certs/
+fi

-cat >/tmp/baz.py <<EOF
-#!/usr/bin/python
+cat >/tmp/baz.py <<'EOF'
+#!/usr/bin/python3
 import socket
 import sys

@@ -37,10 +40,8 @@
 sock.close()
 EOF

-
-
-cat >/tmp/foo.py <<EOF
-#!/usr/bin/python
+cat >/tmp/foo.py <<'EOF'
+#!/usr/bin/python3

 import socket
 import os
@@ -128,24 +129,24 @@
 	sock.close()
 EOF

-chmod 755 /tmp/foo.py
-chmod 755 /tmp/baz.py
-
-NODESTATUS=#TABLEBLANKOKAY:site:key=nodestatus:value#
-
-if [ -z "$NODESTATUS" ] || [ "$NODESTATUS" != "0" -a   "$NODESTATUS" != "N"  -a  "$NODESTATUS" != "n" ]; then
-   /tmp/baz.py "installstatus installing" &
-fi
+chmod 0755 /tmp/foo.py
+chmod 0755 /tmp/baz.py

+NODESTATUS="#TABLEBLANKOKAY:site:key=nodestatus:value#"

+case "$NODESTATUS" in
+"0"|"N"|"n")
+    ;;
+*)
+    /tmp/baz.py "installstatus installing" &
+    ;;
+esac

 /tmp/foo.py >/foo.log 2>&1 &

-
-
-#time to ascertain fstype and PReP/UEFI/legacy
-#also, find first available block device (sda or vda likely)
-#TODO: pick a likely non-SAN target if possible
+# time to ascertain fstype and PReP/UEFI/legacy
+# also, find first available block device (sda or vda likely)
+# TODO: pick a likely non-SAN target if possible
 shopt -s nullglob

 #
@@ -157,48 +158,37 @@
     instdisk=`cat /tmp/xcat.install_disk`
 fi

-modprobe ext4 >& /dev/null
-modprobe ext4dev >& /dev/null
-if grep ext4dev /proc/filesystems > /dev/null; then
-	FSTYPE=ext3
-elif grep ext4 /proc/filesystems > /dev/null; then
-	FSTYPE=ext4
-else
-	FSTYPE=ext3
+BOOTFSTYPE=ext4
+FSTYPE=ext4
+EFIFSTYPE=efi
+
+echo "ignoredisk --only-use=$instdisk" >>/tmp/partitionfile
+case "$(uname -m)" in
+"ppc64"|"ppc64le")
+    echo "part prepboot --fstype=prepboot --asprimary --ondisk=$instdisk --size=8" >>/tmp/partitionfile
+    ;;
+esac
+if [ -d /sys/firmware/efi ]
+then
+    echo "part /boot/efi --fstype=$EFIFSTYPE --ondisk=$instdisk --size=250" >>/tmp/partitionfile
 fi
-BOOTFSTYPE=ext3
-EFIFSTYPE=vfat

-if uname -r|grep -q '^3.*el7'; then
-    BOOTFSTYPE=xfs
-    FSTYPE=xfs
-    EFIFSTYPE=efi
-fi
+# TODO: Ondisk detection, /dev/disk/by-id/edd-int13_dev80 for legacy maybe, and no idea about efi. At least maybe blacklist SAN if mptsas/mpt2sas/megaraid_sas seen...
+echo "part /boot --fstype=$BOOTFSTYPE --asprimary --ondisk=$instdisk --size=512" >>/tmp/partitionfile
+echo "part pv.000997 --grow --asprimary --ondisk=$instdisk --size=8192" >>/tmp/partitionfile
+echo "volgroup system --pesize=4096 pv.000997" >>/tmp/partitionfile
+echo "logvol / --fstype=$FSTYPE --name=root --vgname=system --grow --size=1024" >>/tmp/partitionfile
+echo "logvol swap --name=swap --vgname=system --recommended" >>/tmp/partitionfile

-echo "ignoredisk --only-use=$instdisk" >> /tmp/partitionfile
-if [ `uname -m` = "ppc64" -o `uname -m` = "ppc64le" ]; then
-	echo 'part None --fstype "PPC PReP Boot" --ondisk '$instdisk' --size 8' >> /tmp/partitionfile
-fi
-if [ -d /sys/firmware/efi ]; then
-    echo 'part /boot/efi --size 50 --ondisk '$instdisk' --fstype '$EFIFSTYPE >> /tmp/partitionfile
-fi
+# Specify "bootloader" configuration in "/tmp/partitionfile" if there is no user customized partition file
+BOOTLOADER="bootloader"

-#TODO: ondisk detection, /dev/disk/by-id/edd-int13_dev80 for legacy maybe, and no idea about efi.  at least maybe blacklist SAN if mptsas/mpt2sas/megaraid_sas seen...
-echo "part /boot --size 512 --fstype $BOOTFSTYPE --ondisk $instdisk" >> /tmp/partitionfile
-echo "part swap --recommended --ondisk $instdisk" >> /tmp/partitionfile
-echo "part pv.01 --size 1 --grow --ondisk $instdisk" >> /tmp/partitionfile
-echo "volgroup system pv.01" >> /tmp/partitionfile
-echo "logvol / --vgname=system --name=root --size 1 --grow --fstype $FSTYPE" >> /tmp/partitionfile
-
-#specify "bootloader" configuration in "/tmp/partitionfile" if there is no user customized partition file
-BOOTLOADER="bootloader "
-
-#Specifies which drive the boot loader should be written to
-#and therefore which drive the computer will boot from.
-[ -n "$instdisk" ] && BOOTLOADER=$BOOTLOADER" --boot-drive=$(basename $instdisk)"
+# Specifies which drive the boot loader should be written to
+# and therefore which drive the computer will boot from.
+[ -n "$instdisk" ] && BOOTLOADER="$BOOTLOADER --boot-drive=$(basename $instdisk)"
+
+echo "$BOOTLOADER" >>/tmp/partitionfile

-echo "$BOOTLOADER" >> /tmp/partitionfile
-
 #XCA_PARTITION_SCRIPT#

 #specify the kernel options which will be persistent after installation
@@ -208,25 +198,27 @@
     #append the persistent kernel options to the lines including "bootloader" without "--append"
     sed -i -e '/bootloader/{/append=/!s/$/& --append="#ENV:PERSKCMDLINE#" /}' /tmp/partitionfile
     #append the persistent kernel options to /tmp/partitionfile if it does not include "bootloader"
-    grep bootloader /tmp/partitionfile >/dev/null 2>&1|| echo -e "bootloader --append=\"#ENV:PERSKCMDLINE#\"" >>/tmp/partitionfile
+    grep -q bootloader /tmp/partitionfile >/dev/null 2>&1 || echo -e "bootloader --append=\"#ENV:PERSKCMDLINE#\"" >>/tmp/partitionfile
 fi

-#save the content of /tmp/partitionfile in /var/log/xcat/xcat.log
-#so that we can inspect the partition scheme after installation
-echo "=================The Partition Scheme================"
+# save the content of /tmp/partitionfile in /var/log/xcat/xcat.log
+# so that we can inspect the partition scheme after installation
+echo "================ The Partition Scheme ==============="
 cat /tmp/partitionfile
 echo "====================================================="

 # The following code is to generate the repository for the installation
 cat /proc/cmdline

-NEXTSERVER=`cat /proc/cmdline | grep http | head -n 1`
-NEXTSERVER=${NEXTSERVER#*http://}
-NEXTSERVER=${NEXTSERVER%%:*}
+NEXTSERVER="$(grep -m 1 http /proc/cmdline)"
+NEXTSERVER="${NEXTSERVER#*http://}"
+NEXTSERVER="${NEXTSERVER%%:*}"

-export nextserver=$NEXTSERVER
+export nextserver="$NEXTSERVER"
 #INSTALL_SOURCES_IN_PRE#

-if [ "$XCATDEBUGMODE" = "1" ] || [ "$XCATDEBUGMODE" = "2" ]; then
+case "$XCATDEBUGMODE" in
+"1"|"2")
     set +x
-fi
+    ;;
+esac
```

**Comment by robin2008** [comment]
This is all for new codes, I'd like this be merged in ASAP, so others could try it with the dailybuild.
But we need to change the title as now it is only for rhel8 diskful template.  Could we add the diskful service node package list too?

**Pull request merged**
