### PR TITLE
Linux diskfull installation test case - which can deploy a compute node with linux distro different from the manage node

### PR DESCRIPTION
**Pull request by neo954**
### The PR is for task https://github.com/xcat2/xcat2-task-management/issues/295

_##Feature description##_

This is a test case which can deploy a compute node with linux distro different from the manage node. Thus we can test RHEL7->RHEL8 or similar situation.

### CODE REVIEW

**Comment by neo954** [comment]
Hello @hu-weihua,

Please review these test cases when you have time.

**Comment by hu-weihua** [comment]
Do not need file ``rhels8_ppc64le_rhels7mn.bundle``. We can set these in project configuration page. We are trying to reduce dependence on the bundles shipped by ``xcattest``. So it is better to choose project configuration first.

**Comment by hu-weihua** [comment]
The general comment is if the main progress of ``install-linux-diskfull.sh`` or ``install-linux-diskless.sh`` are same as test case ``reg_linux_diskfull_installation_flat`` or  ``reg_linux_diskless_installation_flat``, why do not follow the test case format of ``xcattest`` support? The biggest different point is the maintenance effort.  If using test case format of ``xcattest`` support, the maintainer can easily get which step the case is doing and get the output of every  command from the ``xcattest`` log file, even the  maintainer did not read the case content before. But if coding like what ``install-linux-diskfull.sh`` does, the output of commands in the script, such like makedns, makedhcp...., will crowed together.  At same time, there is no way for maintainer  to get what the script is doing now.  It is very hard for maintainer. At same time, we do not get any benefit from this kind of change. 

The output of ``install-linux-diskfull.sh``:
```
[root@ test]# ./install-linux-diskfull.sh  --compute-node c910f03c09k08 --iso-file=/tmp/automation_mountpoint/iso/RHEL-7.6-Server-ppc64le-dvd1-stable.iso
Object name: c910f03c09k08
    arch=ppc64le
    cons=kvm
    consoleenabled=1
    currchain=boot
    currstate=boot
    groups=all
    id=8
    ip=10.3.9.8
    mac=42:01:0a:03:09:08|42:2f:0a:03:09:08!*NOIP*|42:02:0a:03:09:08!*NOIP*
    mgt=kvm
    netboot=grub2
    os=rhels8.0
    postbootscripts=otherpkgs
    postscripts=syslog,remoteshell,syncfiles
    profile=compute
    provmethod=rhels8.0-ppc64le-install-compute
    serialflow=hard
    serialport=0
    serialspeed=115200
    status=powering-off
    statustime=11-22-2018 13:33:22
    updatestatus=failed
    updatestatustime=11-22-2018 11:20:59
    vmcpus=4
    vmhost=c910f03c09
    vmmemory=8192
    vmnicnicmodel=virtio-net-pci
    vmnics=br10,br50,br4093
    vmstorage=phy:/dev/mapper/vdiskvg-vdisk00n08
1 object definitions have been created or modified.
Handling c910f03c09k03 in /etc/hosts.
Handling c910f03c09k06 in /etc/hosts.
Handling frame5u39 in /etc/hosts.
Handling f6u13k17 in /etc/hosts.
Handling c910f05c01bc04v04 in /etc/hosts.
Handling c910f03c09k08 in /etc/hosts.
s.
Handling c910f02c01p16 in /etc/hosts.
Handling localhost in /etc/hosts.
Handling testnode in /etc/hosts.
Ignoring host testnode, it does not belong to any nets defined in networks table or the net it belongs to is configured to use an external nameserver.
Handling c910f03c09k07 in /etc/hosts.
Handling f6u13k11 in /etc/hosts.
......
Handling c910f03c05k06 in /etc/hosts.
Handling c910f03c09k05 in /etc/hosts.
Getting reverse zones, this may take several minutes for a large cluster.
Completed getting reverse zones.
Updating zones.
Completed updating zones.
Restarting named
Restarting named complete
Updating DNS records, this may take several minutes for a large cluster.
Completed updating DNS records.
DNS setup is completed
Error: [c910f03c09k06]: Failed to send delete request.
Error: [c910f03c09k06]: Failed to send create request.
Error: [c910f03c09k06]: Failed to create console entry in goconserver.
Error: [c910f03c09k06]: goconserver is being used as the console service, did you mean: makegocons <noderange>? If not, stop goconserver and retry.
1 object definitions have been created or modified.
1 object definitions have been created or modified.
configuring management node: c910f03c09k06.
Renamed existing dhcp configuration file to  /etc/dhcp/dhcpd.conf.xcatbak
......
```
But the output of the test case using the format ``xcattest`` support:
```
RUN:chdef -t node -o c910f04x12v04 servicenode= monserver=c910f04x12v02 nfsserver=c910f04x12v02 tftpserver=c910f04x12v02  xcatmaster=c910f04x12v02 [Wed Sep 12 08:05:01 2018]
ElapsedTime:0 sec
RETURN rc = 0
OUTPUT:
1 object definitions have been created or modified.
CHECK:rc == 0   [Pass]

RUN:makedns -n [Wed Sep 12 08:05:01 2018]
ElapsedTime:6 sec
RETURN rc = 0
OUTPUT:
Handling c910hmc04 in /etc/hosts.
Handling c910f03fsp03v06.pok.stglabs.ibm.com in /etc/hosts.
Handling c910f02c01p10 in /etc/hosts.
Handling c910f03c03k27 in /etc/hosts.
Handling c910f02c09p04 in /etc/hosts.
Handling c910f02c07p30 in /etc/hosts.
Handling c910f02c07p18 in /etc/hosts.
......
Completed getting reverse zones.
Updating zones.
Completed updating zones.
Restarting named
Restarting named complete
Updating DNS records, this may take several minutes for a large cluster.
Completed updating DNS records.
DNS setup is completed
CHECK:rc == 0   [Pass]

RUN:makeconservercf [Wed Sep 12 08:05:07 2018]
ElapsedTime:0 sec
RETURN rc = 0
OUTPUT:
Warning: [c910f04x12v02]: makeconservercf is deprecrated as well as conserver, go to makegocons for more information about enabling goconserver.
CHECK:rc == 0   [Pass]

RUN:cat /etc/conserver.cf | grep c910f04x12v04 [Wed Sep 12 08:05:07 2018]
ElapsedTime:0 sec
RETURN rc = 0
OUTPUT:
#xCAT BEGIN c910f04x12v04 CONS
console c910f04x12v04 {
  exec /opt/xcat/share/xcat/cons/kvm c910f04x12v04;
#xCAT END c910f04x12v04 CONS
CHECK:output =~ c910f04x12v04   [Pass]
......
```

**Comment by hu-weihua** [comment]
And depending on our pull request policy, please paste the UT result when pull the request. thanks.

**Comment by neo954** [comment]
File `rhels8_ppc64le_rhels7mn.bundle` removed.

**Comment by neo954** [comment]
@hu-weihua,

Acturally, we can rewrite test case `install-linux-diskfull.sh`, and make it call the script `reg_linux_diskfull_installation_flat` to do the same thing.

There are a bunch of problems in the test case format which `xcattest` support. I list some of them below

* There is no way to use variables in test case.
* When shell if expression or looping is using in the test case, all the sentences have to be squeezed into one line. Which makes the code hard to read and maintenance.
* The syntax parsing is buggy. For example, if there is any `#` character appeared in a command line, it will be truncated. For example, the following line will fail. The actual command to be called is `sed -i -e '`, which is nonsense.
  ``cmd:sed -i -e 's#/path/to/foo#/path/to/bar#' /etc/some_config_file``
* There is no way to define function. This makes the code reuse even harder.
* When something went wrong in the middle of somewhere a test case was running. There is no way to skip the remaining part of the test case, and mark a FAIL. All the commands listed in the test case have to be run.

Conclusion, the test case format which `xcattest` support have a bunch of limitation. For a good test case design, it need the developer to pay close attention on those limitations. This make it even harder to read and maintenance the test case. And this is inefficiency.

Thus, whenever possible, I will write regular `bash` script and use it as test case. It makes the debugging more easier. Since, in this way, the test case can be run without `xcattest`.

**Comment by whowutwut** [comment]
Since there are conflicts here and @neo954  is not longer actively participating, let's close this for now and if needed, we can look at the PR and re-create the changes.  @cxhong if you think this is needed,  you can grab the changes to your own forked copy and create  a  new PR

**Pull request closed without merging**
