### PR TITLE
update hwinv table by updatenode -P geinv

### PR DESCRIPTION
**Pull request by xuweibj**
#5345 
Run ``updatenode`` with xcatdebugmode is 1
```
# updatenode c910f03c17k20 -P getinv
c910f03c17k20: vpdupdate is not supported on the pSeries KVM Guest platform
c910f03c17k20: updating VPD database
c910f03c17k20: trying to download postscripts...
c910f03c17k20: postscripts downloaded successfully
c910f03c17k20: trying to get mypostscript from 10.3.17.21...
c910f03c17k20: Wed Jul  4 02:38:48 EDT 2018 Running postscript: getinv
c910f03c17k20: + '[' -z '' ']'
c910f03c17k20: + XCATDEST=
c910f03c17k20: + '[' -z '' ']'
c910f03c17k20: + XCATDEST=10.3.17.21:3001
c910f03c17k20: + tmp_file=/tmp/invinfo.xml
c910f03c17k20: + '[' -r /sys/devices/virtual/dmi/id/product_name ']'
c910f03c17k20: + '[' -r /proc/device-tree/model ']'
c910f03c17k20: + grep -e '^cpu\s*:' /proc/cpuinfo
c910f03c17k20: + read line
c910f03c17k20: + echo cpu : POWER8E '(raw),' altivec supported
c910f03c17k20: + read line
c910f03c17k20: + echo cpu : POWER8E '(raw),' altivec supported
c910f03c17k20: + read line
c910f03c17k20: + echo cpu : POWER8E '(raw),' altivec supported
c910f03c17k20: + read line
c910f03c17k20: + echo cpu : POWER8E '(raw),' altivec supported
c910f03c17k20: + read line
c910f03c17k20: ++ cat /proc/cpuinfo
c910f03c17k20: ++ grep -e '^cpu\s*:'
c910f03c17k20: ++ wc -l
c910f03c17k20: + CPUCOUNT=4
c910f03c17k20: ++ cat /tmp/cpumod
c910f03c17k20: ++ awk -F: '{print $2}'
c910f03c17k20: ++ sed -e 's/^ //'
c910f03c17k20: + CPUTYPE='POWER8E (raw), altivec supported'
c910f03c17k20: ++ cat /proc/meminfo
c910f03c17k20: ++ awk '{printf "%.0fMB\n", $2/1024}'
c910f03c17k20: ++ grep MemTotal
c910f03c17k20: + MEMORY=6119MB
c910f03c17k20: ++ grep -v name /proc/partitions
c910f03c17k20: ++ awk 'BEGIN{sep=""} /[^0-9]$/{printf("%s%s:%.0fGB", sep, $4, $3/1024^2) ; sep=","}'
c910f03c17k20: ++ sort -g -k 1,2
c910f03c17k20: + DISKSIZE=sda:40GB
c910f03c17k20: + echo '<xcatrequest>'
c910f03c17k20: + echo '<command>updatehwinv</command>'
c910f03c17k20: + echo '<cpucount>4</cpucount>'
c910f03c17k20: + echo '<cputype>POWER8E (raw), altivec supported</cputype>'
c910f03c17k20: + echo '<memory>6119MB</memory>'
c910f03c17k20: + echo '<disksize>sda:40GB</disksize>'
c910f03c17k20: + echo '</xcatrequest>'
c910f03c17k20: + xml_file=/tmp/hwinv.xml
c910f03c17k20: + rm -f /tmp/hwinv.xml
c910f03c17k20: + '[' '!' -f /tmp/hwinv.xml ']'
c910f03c17k20: + '[' -f /tmp/hwinv.xml ']'
c910f03c17k20: + '[' -f /etc/xcat/cert.pem -a -f /etc/xcat/certkey.pem ']'
c910f03c17k20: + cat /tmp/invinfo.xml
c910f03c17k20: + openssl s_client -connect 10.3.17.21:3001 -quiet
c910f03c17k20: + '[' '!' -f /tmp/hwinv.xml ']'
c910f03c17k20: + grep error /tmp/hwinv.xml
c910f03c17k20: + rm /tmp/cpumod
c910f03c17k20: + rm /tmp/invinfo.xml
c910f03c17k20: postscript: getinv exited with code 0
c910f03c17k20: Running of postscripts has completed.
```
result:
```
# tabdump hwinv
#node,cputype,cpucount,memory,disksize,comments,disable
"c910f03c17k20","POWER8E (raw), altivec supported","4","6119MB","sda:40GB",,
```

### CODE REVIEW

**Comment by chuckbrazie** [comment]
I am out of the office until 07/16/2018.

I am out of the office until  Monday July 16.


Note: This is an automated response to your message  "[xcat2/xcat-core]
update hwinv table by updatenode -P geinv (#5371)" sent on 7/4/18 7:07:26
AM.

This is the only notification you will receive while this person is away.

**Comment by chuckbrazie** [comment]
I am out of the office until 07/16/2018.

I am out of the office until  Monday July 16.


Note: This is an automated response to your message  "Re: [xcat2/xcat-core]
update hwinv table by updatenode -P geinv (#5371)" sent on 7/4/18 7:09:56
AM.

This is the only notification you will receive while this person is away.

**Comment by zet809** [comment]
Good to me, I agree to merge, thx @xuweibj

**Comment by chuckbrazie** [comment]
I am out of the office until 07/16/2018.

I am out of the office until  Monday July 16.


Note: This is an automated response to your message  "Re: [xcat2/xcat-core]
update hwinv table by updatenode -P geinv (#5371)" sent on 7/5/18 7:55:55
AM.

This is the only notification you will receive while this person is away.

**Comment by chuckbrazie** [comment]
I am out of the office until 07/16/2018.

I am out of the office until  Monday July 16.


Note: This is an automated response to your message  "Re: [xcat2/xcat-core]
update hwinv table by updatenode -P geinv (#5371)" sent on 7/5/18 7:55:38
AM.

This is the only notification you will receive while this person is away.

**Comment by chuckbrazie** [comment]
I am out of the office until 07/16/2018.

I am out of the office until  Monday July 16.


Note: This is an automated response to your message  "Re: [xcat2/xcat-core]
update hwinv table by updatenode -P geinv (#5371)" sent on 7/5/18 7:56:01
AM.

This is the only notification you will receive while this person is away.

**Comment by robin2008** [comment]
@xuweibj  @zet809 
Do you really consider the security here?  to add `allow` policy here without any ACL (client IP) means everyone could send the data to xcat DB from everywhere. 

And here you plugin is to modify DB with any checking, it is very dangerous.  For example,  I just run below from one server which does not in your cluster, and I can update your table
```
tabdump hwinv
#node,cputype,cpucount,memory,disksize,comments,disable
"c910f03c17k20","POWER8E (raw), altivec supported","4","6119MB","sda:40GB",,
"c910f03c05k30","$CPUTYPE",,,,,   <====  here is my insertion.
```

So, please remove the default policy rule for "updatehwinv", if user want to use this feature,  he can enable it with more strict ACL to make sure it is secured enough.

**Comment by chuckbrazie** [comment]
I am out of the office until 07/16/2018.

I am out of the office until  Monday July 16.


Note: This is an automated response to your message  "Re: [xcat2/xcat-core]
update hwinv table by updatenode -P geinv (#5371)" sent on 7/6/18 6:07:48
AM.

This is the only notification you will receive while this person is away.

**Pull request merged**
