### PR TITLE
Sync up some bundle files after combining xcatd test cases

### PR DESCRIPTION
**Pull request by hu-weihua**
Due to some xcatd test cases were combined as below,  so update related bundle files.

``xcatd_start_systemd`` was combined to ``xcatd_start``.

``xcatd_restart_systemd`` was combined to ``xcatd_restart``.

``run_command_with_XCATBYPASS_systemd`` was combined to ``run_command_with_XCATBYPASS``.

``disable_root_permission_in_policy_table_systemd`` was combined to ``disable_root_permission_in_policy_table``.

``assign_certain_command_permission_systemd`` was combined to ``disable_root_permission_in_policy_table``.

### CODE REVIEW

**Comment by tingtli** [comment]
I think under bundle directory, we have more than 4 files which has systems test cases. Have you update  all the bundle files?

**Comment by chuckbrazie** [comment]
I am out of the office until 07/16/2018.

I am out of the office until  Monday July 16.


Note: This is an automated response to your message  "Re: [xcat2/xcat-core]
Sync up some bundle files after combining xcatd test cases (#5370)" sent on
7/4/18 8:43:40 AM.

This is the only notification you will receive while this person is away.

**Comment by chuckbrazie** [comment]
I am out of the office until 07/16/2018.

I am out of the office until  Monday July 16.


Note: This is an automated response to your message  "Re: [xcat2/xcat-core]
Sync up 4 bundle files after combining xcatd test cases (#5370)" sent on
7/4/18 7:46:41 AM.

This is the only notification you will receive while this person is away.

**Comment by chuckbrazie** [comment]
I am out of the office until 07/16/2018.

I am out of the office until  Monday July 16.


Note: This is an automated response to your message  "[xcat2/xcat-core]
Sync up 4 bundle files after combining xcatd test cases (#5370)" sent on
7/4/18 7:03:13 AM.

This is the only notification you will receive while this person is away.

**Comment by chuckbrazie** [comment]
I am out of the office until 07/16/2018.

I am out of the office until  Monday July 16.


Note: This is an automated response to your message  "Re: [xcat2/xcat-core]
Sync up some bundle files after combining xcatd test cases (#5370)" sent on
7/4/18 8:43:44 AM.

This is the only notification you will receive while this person is away.

**Comment by chuckbrazie** [comment]
I am out of the office until 07/16/2018.

I am out of the office until  Monday July 16.


Note: This is an automated response to your message  "Re: [xcat2/xcat-core]
Sync up 4 bundle files after combining xcatd test cases (#5370)" sent on
7/4/18 7:06:33 AM.

This is the only notification you will receive while this person is away.

**Comment by chuckbrazie** [comment]
I am out of the office until 07/16/2018.

I am out of the office until  Monday July 16.


Note: This is an automated response to your message  "Re: [xcat2/xcat-core]
Sync up some bundle files after combining xcatd test cases (#5370)" sent on
7/4/18 10:40:39 AM.

This is the only notification you will receive while this person is away.

**Pull request merged**
