### PR TITLE
update for test vm

### PR DESCRIPTION
**Pull request by tingtli**

### CODE REVIEW

**Comment by daniceexi** [comment]
This is a workaround for the rmvm issue in the automation. It looks ok for merge.

**Comment by whowutwut** [comment]
I'm not sure why we do that instead of listing out the images dir? To see what it looks like before running any commands. Otherwise we are just guessing on what to run...

Also...should just remove the code instead of commenting out

**Comment by whowutwut** [comment]
@tingtli can you include the issue number in the description that it is resolving?

**Comment by whowutwut** [comment]
Adding reference to Issue #1958

**Comment by tingtli** [comment]
@whowutwut  i make some some updates according to your comments. See PR #2033 
And for the hold operation which I mentioned in the mail, this is a xcatjktest operation which will pending on the failed case.

**Comment by whowutwut** [comment]
Ok, thanks @tingtli ! I see it now

**Pull request merged**
