### PR TITLE
Support for Oracle Linux 7 and Oracle Linux 8

### PR DESCRIPTION
**Pull request by viniciusferrao**
### The modification include

	modified:   perl-xCAT/xCAT/data/discinfo.pm
	new file:   xCAT-server/share/xcat/install/ol/compute.ol7.pkglist
	new file:   xCAT-server/share/xcat/install/ol/compute.ol7.tmpl
	new file:   xCAT-server/share/xcat/install/ol/compute.ol8.pkglist
	new file:   xCAT-server/share/xcat/install/ol/compute.ol8.tmpl
	new file:   xCAT-server/share/xcat/netboot/ol/compute.ol7.x86_64.exlist
	new file:   xCAT-server/share/xcat/netboot/ol/compute.ol7.x86_64.pkglist
	new file:   xCAT-server/share/xcat/netboot/ol/compute.ol7.x86_64.postinstall
	new file:   xCAT-server/share/xcat/netboot/ol/compute.ol8.x86_64.exlist
	new file:   xCAT-server/share/xcat/netboot/ol/compute.ol8.x86_64.pkglist
	new file:   xCAT-server/share/xcat/netboot/ol/compute.ol8.x86_64.postinstall
	new file:   xCAT-server/share/xcat/netboot/ol/dracut_047
	new file:   xCAT-server/share/xcat/netboot/ol/geninitrd
	modified:   xCAT-server/share/xcat/netboot/rh/genimage

### CODE REVIEW

**Comment by gurevichmark** [comment]
@viniciusferrao Thank you for your contribution.

I am trying to validate that this works in our environment.

I am running into problem when provisioning diskfull VM with either OL8.3 or OL7.9
The problem appears to be `%include /tmp/repos` line in OL `.tmpl` file. 

Same line is there for RHEL8 `.tmpl` file.
When provisioning RHEL8, there is a file `/tmp/repos` on the node with this content:
```
# cat /tmp/repos
url --url http://<xCATMN>:80//install/rhels8.3.0/x86_64
#
```
But when OL8 or OL7 is being provisioned, no such file is on the and it fails with:
```
An error occurred during reading the kickstart file: Unable to open input kickstart file: Error opening file: [Errno 2] No such file or directory: '/tmp/repos'
```
I can comment that line out from the OL `.tmpl` file and provisioning succeeds.
Did you see a similar problem on your systems ?

**Comment by viniciusferrao** [comment]
> I can comment that line out from the OL `.tmpl` file and provisioning succeeds.
> Did you see a similar problem on your systems ?

I didn't tested with stateful nodes... I will do some testing with stateful to replicate the issue.

**Comment by viniciusferrao** [comment]
@gurevichmark I think I've found the issue, it's probably on `xCAT-server/lib/perl/xCAT/Template.pm` in line 302:

`if ($platform =~ /^(rh|SL|centos|fedora)$/) {`

Instead of removing it from the kickstart file, I think it's better to just fix the template file and keep things persistent between EL releases.

**Comment by viniciusferrao** [comment]
Hi @gurevichmark, I've tested the last commit with Legacy BIOS and UEFI:

image

```
[root@cabecudo ~]# lsdef -t node n01 | grep install
    currstate=install ol8.3-x86_64-compute
    provmethod=ol8.3-x86_64-install-compute
    status=installing
[root@cabecudo ~]# lsdef -t node n02 | grep install
    currstate=install ol8.3-x86_64-compute
    provmethod=ol8.3-x86_64-install-compute
    status=installing
```

Both are working now:

image

```
[root@cabecudo ~]# lsdef -t node n01 | egrep "install|status"
    provmethod=ol8.3-x86_64-install-compute
    status=booted
    statustime=04-16-2021 18:01:10
[root@cabecudo ~]# lsdef -t node n02 | egrep "install|status"
    provmethod=ol8.3-x86_64-install-compute
    status=booted
    statustime=04-16-2021 18:02:12
```

Something went messy with the CI/CD again, can you retry it?

**Review by gurevichmark — APPROVED** [review]

**Pull request merged**
