### PR TITLE
Improvements to install guide address issues from #290

### PR DESCRIPTION
**Pull request by whowutwut**
Addresses comments brought up with issue 290, and completed
missing documents for installing SLES and Ubuntu for the install-guide

Address the comments brought up with #290 

http://10.2.5.2/issue290/

### CODE REVIEW

**Comment by whowutwut** [comment]
@caomengmeng  ,please spend some time to review and merge this pull request, as we are asking others to start reviewing the pages and would like it to be as complete as possible

**Comment by caomengmeng** [comment]
I just review all the changed issue.
Except some logical details are very complicated for me, I just check the spelling and meaning.
All the others are OK.
So I will merge this PR.

**Comment by whowutwut** [comment]
Thanks I resolved the conflicts

**Comment by caomengmeng** [comment]
@whowutwut 
How do you think the user's->users?
-#. Make sure xCAT commands are in the user's path ::
+#. Make sure xCAT commands are in the users path ::


Maybe the former user's is right for both files: 
docs/source/advanced/hamn/setup_xcat_high_available_management_node_in_softlayer.rst
docs/source/advanced/webservices/set_up_ws.rst

**Comment by whowutwut** [comment]
Yea I agree we should write it "users"

**Comment by whowutwut** [comment]
@caomengmeng , I think those occurrences of user's -> users can be made directly into the document.  

Feel free to make those changes directly to xcat2/xcat-core.  You can do that from RTD clicking on the "Edit in GitHub" link.     @daniceexi  can help if needed.  I don't plan to make those changes in this pull request.

**Comment by whowutwut** [comment]
Also, I see you are in the "advanced" section of the document, please merge the pull request if you are done reviewing the fixes made from Issue #290...   @cxhong  was trying to follow the guides for Ubuntu and they are still missing in the docs because the pull request is still pending.   So it's better to have these sections into the document so more people can review. .. the sooner the better...

**Comment by whowutwut** [comment]
Sorry, i misread your user's vs users comment.   I'm not sure...  :-) 
http://forum.wordreference.com/threads/user%E2%80%99s-users-or-users.1474044/

That link above seems to indicate that users is okay

**Comment by whowutwut** [comment]
@daniceexi @caomengmeng, Normally there is not this kind of urgency to merge this pull request, but we have many people working on documentation improvements and now this pull request is blocking  #342 and #324 .  I need @junxiawang  and @hu-weihua to redo their changes based on the new files that this pull request adds to the install guides.

**Pull request merged**
