### PR TITLE
Add test case to check exit code when syncfiles failing

### PR DESCRIPTION
**Pull request by neo954**
Add one cases in this pull request
This test case is for issue #2560
This pull request is for task #2929

[case 1]
Case Name: updatenode_diskful_syncfiles_failing
description: Test exit code when syncfiles failing.

### CODE REVIEW

**Comment by neo954** [comment]
@immarvin, please help on review this patch.

**Comment by immarvin** [comment]
hi @neo954 , according to the FVT test case process , the following lines should be added to the beginning of the test case itself
````
[case 1]
Case Name: updatenode_diskful_syncfiles_failing
description: Test exit code when syncfiles failing.
````

**Comment by neo954** [comment]
@immarvin, test case updated.

**Comment by immarvin** [comment]
i am ok with the change

**Pull request merged**
