### PR TITLE
Some important fixs about xcatd for 2.9

### PR DESCRIPTION
**Pull request by chenglch**
issue: #1219 #537

### CODE REVIEW

**Comment by whowutwut** [comment]
Moving to 2.9.4 milestone.  Is there a plan to cherry pick to master, or already in the master branch?

**Comment by daniceexi** [comment]
Yes, it has been checked in to master. But someone wanted the fixes to 2.9 branch, so we created this pull request. But code change is risky. So my idea is if user cannot give a strong justification, we won't check in this pull request to 2.9 branch.

**Comment by whowutwut** [comment]
@daniceexi If we are not going to merge, should we close this?

**Comment by daniceexi** [comment]
It was kept open to wait for the people to confirm whether this pull request is really necessary.

Did not get feedback, so we can close it now.

**Pull request closed without merging**
