### PR TITLE
openbmc python refactor

### PR DESCRIPTION
**Pull request by robin2008**
1, new directory layout
```
├── agent.py
├── client.py
├── common 
│   ├── __init__.py
│   ├── exceptions.py
│   ├── rest.py
│   ├── task.py
│   └── utils.py
├── hwctl                 (This directory is responsible to handle core hw control business )
│   ├── __init__.py
│   ├── openbmc.py
│   ├── power.py
│   └── task.py
└── xcatagent        (this directory is responsible to communicate with xcat plugin)
    ├── __init__.py
    ├── base.py
    ├── openbmc.py          <=== Only have OpenBMCManager to handle the requests from xcatd
    ├── openbmc_rest.py  <=== will be removed
    └── server.py
```
2, 3 layer 
Client:  (xcatd , CLI, REST service, Ironic driver)
HW control abstraction: ( class *Manager and calss *Task)
BMC client: (openbmc, redfish, etc...)

### CODE REVIEW

**Comment by robin2008** [comment]
UT:

```
[root@c910f03c05k20 agent]# XCAT_OPENBMC_PYTHON=YES rpower fake1 stat
Wed Jan 31 03:40:42 2018 fake1: [openbmc_debug] login curl -k -c cjar -b cjar -X POST -H "Content-Type: application/json" https://10.6.17.100/login -d '{"data": ["root", "xxxxxx"]}'
Wed Jan 31 03:40:43 2018 fake1: [openbmc_debug] login 200 OK
Wed Jan 31 03:40:43 2018 fake1: [openbmc_debug] list_power_states curl -k -c cjar -b cjar -X GET -H "Content-Type: application/json" https://10.6.17.100/xyz/openbmc_project/state/enumerate
Wed Jan 31 03:40:44 2018 fake1: [openbmc_debug] list_power_states 200 OK
fake1: on
[root@c910f03c05k20 agent]# XCAT_OPENBMC_PYTHON=YES rpower fake1 bmcstate
Wed Jan 31 03:40:57 2018 fake1: [openbmc_debug] login curl -k -c cjar -b cjar -X POST -H "Content-Type: application/json" https://10.6.17.100/login -d '{"data": ["root", "xxxxxx"]}'
Wed Jan 31 03:40:57 2018 fake1: [openbmc_debug] login 200 OK
Wed Jan 31 03:40:57 2018 fake1: [openbmc_debug]  curl -k -c cjar -b cjar -X GET -H "Content-Type: application/json" https://10.6.17.100/xyz/openbmc_project/state/bmc0/attr/CurrentBMCState
Wed Jan 31 03:40:58 2018 fake1: [openbmc_debug]  200 OK
fake1: BMC Ready
[root@c910f03c05k20 agent]# XCAT_OPENBMC_PYTHON=YES rpower fake1 off
Wed Jan 31 03:41:08 2018 fake1: [openbmc_debug] login curl -k -c cjar -b cjar -X POST -H "Content-Type: application/json" https://10.6.17.100/login -d '{"data": ["root", "xxxxxx"]}'
Wed Jan 31 03:41:09 2018 fake1: [openbmc_debug] login 200 OK
Wed Jan 31 03:41:09 2018 fake1: [openbmc_debug] set_power_state curl -k -c cjar -b cjar -X PUT -H "Content-Type: application/json" https://10.6.17.100/xyz/openbmc_project/state/chassis0/attr/RequestedPowerTransition -d '{"data": "xyz.openbmc_project.State.Chassis.Transition.Off"}'
Wed Jan 31 03:41:10 2018 fake1: [openbmc_debug] set_power_state 200 OK
fake1: off
[root@c910f03c05k20 agent]# XCAT_OPENBMC_PYTHON=YES rpower fake1 status
Wed Jan 31 03:41:22 2018 fake1: [openbmc_debug] login curl -k -c cjar -b cjar -X POST -H "Content-Type: application/json" https://10.6.17.100/login -d '{"data": ["root", "xxxxxx"]}'
Wed Jan 31 03:41:23 2018 fake1: [openbmc_debug] login 200 OK
Wed Jan 31 03:41:23 2018 fake1: [openbmc_debug] list_power_states curl -k -c cjar -b cjar -X GET -H "Content-Type: application/json" https://10.6.17.100/xyz/openbmc_project/state/enumerate
Wed Jan 31 03:41:23 2018 fake1: [openbmc_debug] list_power_states 200 OK
fake1: off
[root@c910f03c05k20 agent]# XCAT_OPENBMC_PYTHON=YES rpower fake1 reset
Wed Jan 31 03:41:29 2018 fake1: [openbmc_debug] login curl -k -c cjar -b cjar -X POST -H "Content-Type: application/json" https://10.6.17.100/login -d '{"data": ["root", "xxxxxx"]}'
Wed Jan 31 03:41:30 2018 fake1: [openbmc_debug] login 200 OK
Wed Jan 31 03:41:30 2018 fake1: [openbmc_debug] list_power_states curl -k -c cjar -b cjar -X GET -H "Content-Type: application/json" https://10.6.17.100/xyz/openbmc_project/state/enumerate
Wed Jan 31 03:41:30 2018 fake1: [openbmc_debug] list_power_states 200 OK
fake1: Off
[root@c910f03c05k20 agent]# XCAT_OPENBMC_PYTHON=YES rpower fake1 boot
Wed Jan 31 03:43:29 2018 fake1: [openbmc_debug] login curl -k -c cjar -b cjar -X POST -H "Content-Type: application/json" https://10.6.17.100/login -d '{"data": ["root", "xxxxxx"]}'
Wed Jan 31 03:43:29 2018 fake1: [openbmc_debug] login 200 OK
Wed Jan 31 03:43:29 2018 fake1: [openbmc_debug] list_power_states curl -k -c cjar -b cjar -X GET -H "Content-Type: application/json" https://10.6.17.100/xyz/openbmc_project/state/enumerate
Wed Jan 31 03:43:30 2018 fake1: [openbmc_debug] list_power_states 200 OK
Wed Jan 31 03:43:30 2018 fake1: [openbmc_debug] set_power_state curl -k -c cjar -b cjar -X PUT -H "Content-Type: application/json" https://10.6.17.100/xyz/openbmc_project/state/host0/attr/RequestedHostTransition -d '{"data": "xyz.openbmc_project.State.Host.Transition.On"}'
Wed Jan 31 03:43:30 2018 fake1: [openbmc_debug] set_power_state 200 OK
fake1: powering-on
[root@c910f03c05k20 agent]# XCAT_OPENBMC_PYTHON=YES rpower fake1 state
Wed Jan 31 03:48:46 2018 fake1: [openbmc_debug] login curl -k -c cjar -b cjar -X POST -H "Content-Type: application/json" https://10.6.17.100/login -d '{"data": ["root", "xxxxxx"]}'
Wed Jan 31 03:48:47 2018 fake1: [openbmc_debug] login 200 OK
Wed Jan 31 03:48:47 2018 fake1: [openbmc_debug] list_power_states curl -k -c cjar -b cjar -X GET -H "Content-Type: application/json" https://10.6.17.100/xyz/openbmc_project/state/enumerate
Wed Jan 31 03:48:48 2018 fake1: [openbmc_debug] list_power_states 200 OK
fake1: on
[root@c910f03c05k20 agent]# XCAT_OPENBMC_PYTHON=YES rpower fake1 boot
Wed Jan 31 03:48:53 2018 fake1: [openbmc_debug] login curl -k -c cjar -b cjar -X POST -H "Content-Type: application/json" https://10.6.17.100/login -d '{"data": ["root", "xxxxxx"]}'
Wed Jan 31 03:48:54 2018 fake1: [openbmc_debug] login 200 OK
Wed Jan 31 03:48:54 2018 fake1: [openbmc_debug] list_power_states curl -k -c cjar -b cjar -X GET -H "Content-Type: application/json" https://10.6.17.100/xyz/openbmc_project/state/enumerate
Wed Jan 31 03:48:55 2018 fake1: [openbmc_debug] list_power_states 200 OK
Wed Jan 31 03:48:55 2018 fake1: [openbmc_debug] set_power_state curl -k -c cjar -b cjar -X PUT -H "Content-Type: application/json" https://10.6.17.100/xyz/openbmc_project/state/chassis0/attr/RequestedPowerTransition -d '{"data": "xyz.openbmc_project.State.Chassis.Transition.Off"}'
Wed Jan 31 03:48:55 2018 fake1: [openbmc_debug] set_power_state 200 OK
Wed Jan 31 03:48:55 2018 fake1: [openbmc_debug] list_power_states curl -k -c cjar -b cjar -X GET -H "Content-Type: application/json" https://10.6.17.100/xyz/openbmc_project/state/enumerate
Wed Jan 31 03:49:05 2018 fake1: [openbmc_debug] list_power_states 200 OK
Wed Jan 31 03:49:05 2018 fake1: [openbmc_debug] set_power_state curl -k -c cjar -b cjar -X PUT -H "Content-Type: application/json" https://10.6.17.100/xyz/openbmc_project/state/host0/attr/RequestedHostTransition -d '{"data": "xyz.openbmc_project.State.Host.Transition.On"}'
Wed Jan 31 03:49:07 2018 fake1: [openbmc_debug] set_power_state 200 OK
fake1: powering-on
```

**Comment by robin2008** [comment]
Updated the codes to address the output for `'rpower <> boot/reset', 'rpower <> bmcreboot/bmcstate'`

```
XCAT_OPENBMC_PYTHON=YES rpower fake1 bmcreboot
Thu Feb  1 00:29:09 2018 fake1: [openbmc_debug] login curl -k -c cjar -b cjar -X POST -H "Content-Type: application/json" https://10.6.17.100/login -d '{"data": ["root", "xxxxxx"]}'
Thu Feb  1 00:29:10 2018 fake1: [openbmc_debug] login 200 OK
Thu Feb  1 00:29:10 2018 fake1: [openbmc_debug] bmc_reset curl -k -c cjar -b cjar -X PUT -H "Content-Type: application/json" https://10.6.17.100/xyz/openbmc_project/state/bmc0/attr/RequestedBMCTransition -d '{"data": "xyz.openbmc_project.State.BMC.Transition.Reboot"}'
Thu Feb  1 00:29:10 2018 fake1: [openbmc_debug] bmc_reset 200 OK
fake1: BMC reboot
[root@c910f03c05k20 agent]# XCAT_OPENBMC_PYTHON=YES rpower fake1 bmcstate
Thu Feb  1 00:29:20 2018 fake1: [openbmc_debug] login curl -k -c cjar -b cjar -X POST -H "Content-Type: application/json" https://10.6.17.100/login -d '{"data": ["root", "xxxxxx"]}'
Thu Feb  1 00:29:26 2018 fake1: [openbmc_debug] login Error: BMC did not respond. Validate BMC configuration and retry the command.
fake1: BMC NotReady
```

```
XCAT_OPENBMC_PYTHON=YES rpower fake1 boot
Thu Feb  1 00:36:44 2018 fake1: [openbmc_debug] login curl -k -c cjar -b cjar -X POST -H "Content-Type: application/json" https://10.6.17.100/login -d '{"data": ["root", "xxxxxx"]}'
Thu Feb  1 00:36:44 2018 fake1: [openbmc_debug] login 200 OK
Thu Feb  1 00:36:44 2018 fake1: [openbmc_debug] list_power_states curl -k -c cjar -b cjar -X GET -H "Content-Type: application/json" https://10.6.17.100/xyz/openbmc_project/state/enumerate
Thu Feb  1 00:36:45 2018 fake1: [openbmc_debug] list_power_states 200 OK
Thu Feb  1 00:36:45 2018 fake1: [openbmc_debug] set_power_state curl -k -c cjar -b cjar -X PUT -H "Content-Type: application/json" https://10.6.17.100/xyz/openbmc_project/state/chassis0/attr/RequestedPowerTransition -d '{"data": "xyz.openbmc_project.State.Chassis.Transition.Off"}'
Thu Feb  1 00:36:45 2018 fake1: [openbmc_debug] set_power_state 200 OK
Thu Feb  1 00:36:45 2018 fake1: [openbmc_debug] list_power_states curl -k -c cjar -b cjar -X GET -H "Content-Type: application/json" https://10.6.17.100/xyz/openbmc_project/state/enumerate
Thu Feb  1 00:36:55 2018 fake1: [openbmc_debug] list_power_states 200 OK
Thu Feb  1 00:36:57 2018 fake1: [openbmc_debug] list_power_states curl -k -c cjar -b cjar -X GET -H "Content-Type: application/json" https://10.6.17.100/xyz/openbmc_project/state/enumerate
Thu Feb  1 00:36:57 2018 fake1: [openbmc_debug] list_power_states 200 OK
Thu Feb  1 00:36:59 2018 fake1: [openbmc_debug] list_power_states curl -k -c cjar -b cjar -X GET -H "Content-Type: application/json" https://10.6.17.100/xyz/openbmc_project/state/enumerate
Thu Feb  1 00:36:59 2018 fake1: [openbmc_debug] list_power_states 200 OK
Thu Feb  1 00:36:59 2018 fake1: [openbmc_debug] set_power_state curl -k -c cjar -b cjar -X PUT -H "Content-Type: application/json" https://10.6.17.100/xyz/openbmc_project/state/host0/attr/RequestedHostTransition -d '{"data": "xyz.openbmc_project.State.Host.Transition.On"}'
Thu Feb  1 00:36:59 2018 fake1: [openbmc_debug] set_power_state 200 OK
```

```
XCAT_OPENBMC_PYTHON=YES rpower fake1 off
Thu Feb  1 00:37:46 2018 fake1: [openbmc_debug] login curl -k -c cjar -b cjar -X POST -H "Content-Type: application/json" https://10.6.17.100/login -d '{"data": ["root", "xxxxxx"]}'
Thu Feb  1 00:37:47 2018 fake1: [openbmc_debug] login 200 OK
Thu Feb  1 00:37:47 2018 fake1: [openbmc_debug] set_power_state curl -k -c cjar -b cjar -X PUT -H "Content-Type: application/json" https://10.6.17.100/xyz/openbmc_project/state/chassis0/attr/RequestedPowerTransition -d '{"data": "xyz.openbmc_project.State.Chassis.Transition.Off"}'
Thu Feb  1 00:37:47 2018 fake1: [openbmc_debug] set_power_state 200 OK
fake1: off
[root@c910f03c05k20 agent]# XCAT_OPENBMC_PYTHON=YES rpower fake1 stat
Thu Feb  1 00:37:55 2018 fake1: [openbmc_debug] login curl -k -c cjar -b cjar -X POST -H "Content-Type: application/json" https://10.6.17.100/login -d '{"data": ["root", "xxxxxx"]}'
Thu Feb  1 00:37:56 2018 fake1: [openbmc_debug] login 200 OK
Thu Feb  1 00:37:56 2018 fake1: [openbmc_debug] list_power_states curl -k -c cjar -b cjar -X GET -H "Content-Type: application/json" https://10.6.17.100/xyz/openbmc_project/state/enumerate
Thu Feb  1 00:37:56 2018 fake1: [openbmc_debug] list_power_states 200 OK
fake1: off
[root@c910f03c05k20 agent]# XCAT_OPENBMC_PYTHON=YES rpower fake1 reset
Thu Feb  1 00:38:02 2018 fake1: [openbmc_debug] login curl -k -c cjar -b cjar -X POST -H "Content-Type: application/json" https://10.6.17.100/login -d '{"data": ["root", "xxxxxx"]}'
Thu Feb  1 00:38:03 2018 fake1: [openbmc_debug] login 200 OK
Thu Feb  1 00:38:03 2018 fake1: [openbmc_debug] list_power_states curl -k -c cjar -b cjar -X GET -H "Content-Type: application/json" https://10.6.17.100/xyz/openbmc_project/state/enumerate
Thu Feb  1 00:38:03 2018 fake1: [openbmc_debug] list_power_states 200 OK
fake1: off
```

**Comment by robin2008** [comment]
For `rpower <> boot`, the output is `reset` instead of `boot`
```
XCAT_OPENBMC_PYTHON=YES rpower fake1 boot
Thu Feb  1 00:50:34 2018 fake1: [openbmc_debug] login curl -k -c cjar -b cjar -X POST -H "Content-Type: application/json" https://10.6.17.100/login -d '{"data": ["root", "xxxxxx"]}'
Thu Feb  1 00:50:34 2018 fake1: [openbmc_debug] login 200 OK
Thu Feb  1 00:50:34 2018 fake1: [openbmc_debug] list_power_states curl -k -c cjar -b cjar -X GET -H "Content-Type: application/json" https://10.6.17.100/xyz/openbmc_project/state/enumerate
Thu Feb  1 00:50:35 2018 fake1: [openbmc_debug] list_power_states 200 OK
Thu Feb  1 00:50:35 2018 fake1: [openbmc_debug] set_power_state curl -k -c cjar -b cjar -X PUT -H "Content-Type: application/json" https://10.6.17.100/xyz/openbmc_project/state/host0/attr/RequestedHostTransition -d '{"data": "xyz.openbmc_project.State.Host.Transition.On"}'
Thu Feb  1 00:50:35 2018 fake1: [openbmc_debug] set_power_state 200 OK
fake1: reset
```

**Comment by xuweibj** [comment]
Looks good to me. Thanks @robin2008 .

**Pull request merged**
