### PR TITLE
add compute.ubuntu14.04.3.x86_64.pkglist file and compute.ubuntu14.04.3.ppc64el.pkglist to support ubuntu14.04.3 on x86_64 and ppc64le architecture

### PR DESCRIPTION
**Pull request by penguhyang**
add xCAT-server/share/xcat/netboot/ubuntu/compute.ubuntu14.04.3.x86_64.pkglist
file to support ubuntu14.04.3 on x86_64.

### CODE REVIEW

**Comment by daniceexi** [comment]
I saw you just checked in one file, there should be at least another pkglist file for LE.

You should create pull request for the whole task so that the review could have the overview of your change. It's inefficient that create pull request for each check in.

**Comment by ligc** [comment]
Xiao Peng, I already created the pkglist file for LE.

**Comment by penguhyang** [comment]
add xCAT-server/share/xcat/netboot/ubuntu/compute.ubuntu14.04.3.ppc64el.pkglist and it's soft link file to support ubuntu14.04.3 on ppc64le.

**Comment by daniceexi** [comment]
I am good with the change. 
@immarvin If you agree with the change, could merge this pull request?

**Pull request merged**
