### PR TITLE
[Draft] go-release - A tool for the xCAT release process checking

### PR DESCRIPTION
**Pull request by neo954**
For task #4549

### CODE REVIEW

**Comment by neo954** [comment]
The screen shot below will give you a basic idea of how this tool works.

screen shot 2017-12-27 at 16 31 36

**Comment by daniceexi** [comment]
@neo954 👍 Good to have a tool to reduce the human effort.

**Comment by neo954** [comment]
A new screen shot. Add more checkings.

screen shot 2017-12-29 at 18 28 17

**Comment by neo954** [comment]
This script end up with too much internal information. I will close this pull request, and submit it elsewhere in an internal repository.

**Pull request closed without merging**
