### PR TITLE
Add makeroutes and setroute doc

### PR DESCRIPTION
**Pull request by bybai**
For #3070 

UT link:

http://10.4.41.1/install/routes/xcat-core/docs/build/html/guides/admin-guides/manage_clusters/ppc64le/diskless/customize_image/network/index.html

http://10.4.41.1/install/routes/xcat-core/docs/build/html/guides/admin-guides/manage_clusters/ppc64le/diskful/customize_image/network/cfg_routes.html

### CODE REVIEW

**Comment by bybai** [comment]
Hi @whowutwut and @gurevichmark , could you help review this doc? Thanks

**Comment by cxhong** [comment]
the doc looks good to me.  
do u think we should add a section for verification? after ran `setroute` or `makeroutes` command, where we can check to verify the command is successfully ran.

**Comment by bybai** [comment]
Hi @cxhong , I added "check result" section, please review.

**Comment by cxhong** [comment]
@bybai thanks.

**Pull request merged**
