### PR TITLE
Stop repeating domains in domain-search

### PR DESCRIPTION
**Pull request by loz-hurst**
Fixes issue #246

### CODE REVIEW

**Comment by whowutwut** [comment]
Hi Laurence (@loz-hurst)  Thanks for  your interest in contributing to xCAT, we really appreciate it!  

Before we can accept code to the project, can you just verify that you have signed the CLA or if you are under a corporate CAL, just need the name of the company that had provided the CCLA. The agreements can be found here: http://xcat-docs.readthedocs.org/en/latest/developers/license/contributors.html

If not, could you print out, sign, scan and email a copy to xcat-legal@lists.sourceforge.net.

Thanks and welcome!

**Comment by loz-hurst** [comment]
Hi @whowutwut - I've taken this up with my manager.  Although I have written confirmation that there is no issue with me informally contributing fixes developed in the course of my work back to opensource projects, which I have done a number of times in the past, corporately signing up to grant an permanent irrevocable licence for copyright & patents pertaining to all current and future contributions is a huge ask.  I'll get back to you when I have an answer.

**Comment by loz-hurst** [comment]
Hi @whowutwut,

Sorry for the delay - I had to get the CCLA document past our intellectual property office and then the legal office.  I now have a completed and signed document for the organisation I work for (University of Birmingham, UK) and have sent it to xcat-legal@lists.sourceforce.net, as requested.  If you could keep an eye out for it and merge the request when it's been accepted/approved/whatever-the-process-is-at-your-end?

Thanks,

Laurence

**Comment by whowutwut** [comment]
@loz-hurst  We received the CCLA, thanks!

@daniceexi, let's look to merge this next week as we froze the pull request for this week for an internal release.

**Comment by daniceexi** [comment]
I have reviewed the change and agree to merge.

**Pull request merged**
