### PR TITLE
correct doc for word and syntax

### PR DESCRIPTION
**Pull request by penguhyang**
I found some word and syntax needs to correct.
Test doc link: http://10.2.9.4/overview/index.html

### CODE REVIEW

**Comment by whowutwut** [comment]
Did something happen to this pull request?  Intended to be closed?

**Comment by penguhyang** [comment]
This pull request is not in the right way because it has two mixed up commits. 
@whowutwut Is there some kind of method to delete the invalid pull request ?

**Comment by daniceexi** [comment]
@whowutwut 
@penguhyang closed 293 and opened 294 to submit this change.
I think close an unmerged pull request should not make any harm.

**Comment by whowutwut** [comment]
Ok, yep, I think it's okay,
I didn't  know if it was accidentally closed or if we should review it. :-)

**Pull request closed without merging**
