### PR TITLE
retry in rpower reset when get 'Connection aborted' [ DO NOT MERGE ]

### PR DESCRIPTION
**Pull request by xuweibj**
https://github.ibm.com/vhu/c910env/issues/346

During ``rpower reset``, if got "SelfServerException" when list state or power on, retry.

UT:
```
Thu Aug 30 20:59:02 2018 mid05tor12cn03: [openbmc_debug] login curl -k -c cjar -b cjar -X POST -H "Content-Type: application/json" https://172.11.139.3/login -d '{"data": ["root", "xxxxxx"]}'
Thu Aug 30 20:59:02 2018 mid05tor12cn05: [openbmc_debug] login curl -k -c cjar -b cjar -X POST -H "Content-Type: application/json" https://172.11.139.5/login -d '{"data": ["root", "xxxxxx"]}'
Thu Aug 30 20:59:02 2018 mid05tor12cn03: [openbmc_debug] login 200 OK
Thu Aug 30 20:59:02 2018 mid05tor12cn03: [openbmc_debug] list_power_states curl -k -c cjar -b cjar -X GET -H "Content-Type: application/json" https://172.11.139.3/xyz/openbmc_project/state/enumerate
Thu Aug 30 20:59:02 2018 mid05tor12cn05: [openbmc_debug] login 200 OK
Thu Aug 30 20:59:02 2018 mid05tor12cn05: [openbmc_debug] list_power_states curl -k -c cjar -b cjar -X GET -H "Content-Type: application/json" https://172.11.139.5/xyz/openbmc_project/state/enumerate
Thu Aug 30 20:59:02 2018 mid05tor12cn03: [openbmc_debug] list_power_states 200 OK
Thu Aug 30 20:59:02 2018 mid05tor12cn03: [openbmc_debug] set_power_state curl -k -c cjar -b cjar -X PUT -H "Content-Type: application/json" https://172.11.139.3/xyz/openbmc_project/state/chassis0/attr/RequestedPowerTransition -d '{"data": "xyz.openbmc_project.State.Chassis.Transition.Off"}'
Thu Aug 30 20:59:02 2018 mid05tor12cn05: [openbmc_debug] list_power_states 200 OK
Thu Aug 30 20:59:02 2018 mid05tor12cn05: [openbmc_debug] set_power_state curl -k -c cjar -b cjar -X PUT -H "Content-Type: application/json" https://172.11.139.5/xyz/openbmc_project/state/chassis0/attr/RequestedPowerTransition -d '{"data": "xyz.openbmc_project.State.Chassis.Transition.Off"}'
Thu Aug 30 20:59:03 2018 mid05tor12cn03: [openbmc_debug] set_power_state 200 OK
Thu Aug 30 20:59:03 2018 mid05tor12cn03: [openbmc_debug] list_power_states curl -k -c cjar -b cjar -X GET -H "Content-Type: application/json" https://172.11.139.3/xyz/openbmc_project/state/enumerate
Thu Aug 30 20:59:03 2018 mid05tor12cn05: [openbmc_debug] set_power_state 200 OK
Thu Aug 30 20:59:03 2018 mid05tor12cn05: [openbmc_debug] list_power_states curl -k -c cjar -b cjar -X GET -H "Content-Type: application/json" https://172.11.139.5/xyz/openbmc_project/state/enumerate
Thu Aug 30 20:59:13 2018 mid05tor12cn03: [openbmc_debug] list_power_states 200 OK
Thu Aug 30 20:59:13 2018 mid05tor12cn03: [openbmc_debug] list_power_states curl -k -c cjar -b cjar -X GET -H "Content-Type: application/json" https://172.11.139.3/xyz/openbmc_project/state/enumerate
Thu Aug 30 20:59:14 2018 mid05tor12cn03: [openbmc_debug] list_power_states 200 OK
Thu Aug 30 20:59:14 2018 mid05tor12cn03: [openbmc_debug] set_power_state curl -k -c cjar -b cjar -X PUT -H "Content-Type: application/json" https://172.11.139.3/xyz/openbmc_project/state/host0/attr/RequestedHostTransition -d '{"data": "xyz.openbmc_project.State.Host.Transition.On"}'
Thu Aug 30 20:59:14 2018 mid05tor12cn03: [openbmc_debug] set_power_state 200 OK
mid05tor12cn03: reset
Thu Aug 30 20:59:20 2018 mid05tor12cn05: [openbmc_debug] list_power_states 200 OK
Thu Aug 30 20:59:20 2018 mid05tor12cn05: [openbmc_debug] list_power_states curl -k -c cjar -b cjar -X GET -H "Content-Type: application/json" https://172.11.139.5/xyz/openbmc_project/state/enumerate
Thu Aug 30 20:59:20 2018 mid05tor12cn05: [openbmc_debug] list_power_states BMC did not respond. Validate BMC configuration and retry the command. (Connection reset by peer)
Thu Aug 30 20:59:20 2018 mid05tor12cn05: [openbmc_debug] list_power_states curl -k -c cjar -b cjar -X GET -H "Content-Type: application/json" https://172.11.139.5/xyz/openbmc_project/state/enumerate
Thu Aug 30 20:59:21 2018 mid05tor12cn05: [openbmc_debug] list_power_states 200 OK
Thu Aug 30 20:59:21 2018 mid05tor12cn05: [openbmc_debug] set_power_state curl -k -c cjar -b cjar -X PUT -H "Content-Type: application/json" https://172.11.139.5/xyz/openbmc_project/state/host0/attr/RequestedHostTransition -d '{"data": "xyz.openbmc_project.State.Host.Transition.On"}'
Thu Aug 30 20:59:21 2018 mid05tor12cn05: [openbmc_debug] set_power_state 200 OK
mid05tor12cn05: reset
```

### CODE REVIEW

**Comment by gurevichmark** [comment]
Just the Python change ? Not needed for Perl ?

**Comment by whowutwut** [comment]
I change the title to [DO NOT MERGE] I think we want to ensure that we cannot re-create this before we merge the pull request to really know that it's doing what is intended.

**Comment by xuweibj** [comment]
Hi @whowutwut , I reproduced that error and have verified this modification is OK. The UT result is in description.

@gurevichmark , I did not reproduce it using perl code, just guess will receive "503" error, but not sure. So have not modified perl code.

**Comment by xuweibj** [comment]
Hi @whowutwut , the modification has been verified, shall we merge this pull request?

**Comment by whowutwut** [comment]
@xuweibj So maybe we should merge this so we get some better run time with it.  I have not verified any of this PR manually but I noticed today... after an install of my sandbox build which does not contain your fix., I hit this the first command that I execute.. .

```
...
...

  Verifying  : 4:xCAT-probe-2.14.3-snap201808130615.noarch                                                                                                                                                18/20
  Verifying  : 4:xCAT-test-2.14.3-snap201808130615.noarch                                                                                                                                                 19/20
  Verifying  : 4:xCAT-server-2.14.3-snap201808130615.noarch                                                                                                                                               20/20

Updated:
  perl-xCAT.noarch 4:2.14.4-snap201809061722                   xCAT.ppc64le 0:2.14.4-snap201809061722                                  xCAT-buildkit.noarch 4:2.14.4-snap201809061722
  xCAT-client.noarch 4:2.14.4-snap201809061722                 xCAT-genesis-scripts-ppc64.noarch 1:2.14.4-snap201809061722             xCAT-genesis-scripts-x86_64.noarch 1:2.14.4-snap201809061722
  xCAT-openbmc-py.noarch 1:2.14.4-snap201809061723             xCAT-probe.noarch 4:2.14.4-snap201809061722                             xCAT-server.noarch 4:2.14.4-snap201809061722
  xCAT-test.noarch 4:2.14.4-snap201809061722

Complete!
[root@briggs01 xcat-core]# rpower mid05tor12cn05 reset
mid05tor12cn05: [briggs01]: Error: BMC did not respond. Validate BMC configuration and retry the command.
[root@briggs01 xcat-core]# rpower mid05tor12cn05 reset
mid05tor12cn05: off
[root@briggs01 xcat-core]# rpower mid05tor12cn05 state
mid05tor12cn05: off
[root@briggs01 xcat-core]# rpower mid05tor12cn05 on
mid05tor12cn05: on
[root@briggs01 xcat-core]#
```
Does a install of xCAT affect this code? Is something cached?

**Comment by whowutwut** [comment]
@gurevichmark can you review this PR and merge if OK

**Comment by whowutwut** [comment]
Kick off travis

**Comment by xuweibj** [comment]
Hi @whowutwut , it seems ``xCAT-openbmc-py.noarch 1:2.14.4-snap201809061723`` has been updated, and there is no "try" in code, so get that error the same as before.

**Pull request merged**
