### PR TITLE
Explicitly calling python3 instead of python on shebangs

### PR DESCRIPTION
**Pull request by viniciusferrao**
### The modification include

	modified:   xCAT-openbmc-py/lib/python/agent/agent.py
	modified:   xCAT-openbmc-py/lib/python/agent/client.py
	modified:   xCAT-probe/scripts/dbstats.py
	modified:   xCAT-server/xCAT-wsapi/xcatws-test.py

### CODE REVIEW

**Comment by besawn** [comment]
@viniciusferrao Thank you for your interest in contributing to the xCAT project. We require all contributors to submit a Contributor License Agreement before we can accept any contributions. 

Are you interested in becoming a formal contributor? If so, please feel out the Contributor License Agreement available here: https://xcat-docs.readthedocs.io/en/latest/developers/license/contributors.html and submit the completed form to the xcat-legal mailing list (instructions are included in the document).

**Comment by viniciusferrao** [comment]
Hi @besawn I've sent the signed document to xcat-legal address. Please let me know if anything else if needed.

**Comment by besawn** [comment]
@viniciusferrao I have received your CLA and everything is in order, thank you. The maintainer team will review this pull request in more detail soon.

**Comment by viniciusferrao** [comment]
CI seems to have been failed. Which systems I should check if compilation works perfectly? I'm testing against EL 8.3.

**Comment by gurevichmark** [comment]
Try closing this PR, then reopen after 5 seconds. That should cause CI to rerun.
There are some xCAT CI regression tests that sometimes fail for unknown reasons.

**Comment by gurevichmark** [comment]
Closing this PR, instead #7143 and #7170 were used

**Pull request closed without merging**
