### PR TITLE
mini refine for genesis script doxcat to have it run into bash if no …

### PR DESCRIPTION
**Pull request by zet809**
…NIC with IP facing xcat MN found

### CODE REVIEW

**Comment by zet809** [comment]
@gurevichmark Hi, mark, will you pls help to review this pull request and merge it? Thx!

**Comment by gurevichmark** [comment]
Before we would check every 2 seconds to see if we can ping MN on a NIC.
The new code will only check once. Is there a possibility that initially, on the first check,  MN is not pingable, but some short time later it would be ?

**Comment by zet809** [comment]
@gurevichmark Thx very much for your comment, I have modified to wait 20 seconds more for NICs to get IP address. Pls help to verify.

**Comment by gurevichmark** [comment]
Looks good to me.

**Pull request merged**
