### PR TITLE
add xCAT REST API for nodels

### PR DESCRIPTION
**Pull request by bybai**
for https://github.com/xcat2/xcat2-task-management/issues/38
UT:
```
[root@bybc0602 ws]# curl -X GET -k 'https://bybc0602.cluster.com/xcatws/nodes/node1-node3/nodels?userName=wsuser&userPW=cluster&pretty=1'
[
   "node1",
   "node2",
   "node3"
]

[root@bybc0602 ws]# curl -X GET -k 'https://bybc0602.cluster.com/xcatws/nodes/all/nodels?userName=wsuser&userPW=cluster&pretty=1'
[
   "bybc0605",
   "bybc0609",
   "c699login01",
   "hpcmn-test",
   "node01",
   "node1",
   "node2",
   "node3",
   "s01r1b01",
   "sn4b",
   "test01",
   "testnode1"
]
```

### CODE REVIEW

**Comment by gurevichmark** [comment]
@bybai Can you show the output of this API:
```
curl -X GET -k 'https://bybc0602.cluster.com/xcatws/nodes/node[1-3]/nodels?userName=wsuser&userPW=cluster&pretty=1'
```

**Comment by bybai** [comment]
Hi @gurevichmark , I noticed that you mentioned "There seems to be a difference in the output depending on the way the noderange is specified (comma reparated vs. [])", I think it is usage error.
"node[1-3]" format is not correct in the command like this:
```
 curl -X GET -k 'https://bybc0602.cluster.com/xcatws/nodes/node[1-3]/nodels?userName=wsuser&userPW=cluster&pretty=1'
```
The correct format should be like this, and can get correct results:
```
[root@briggs01 ws]# curl -X GET -k 'https://briggs01/xcatws/nodes/mid05tor12cn0\[1-3\]/nodels?userName=wsuser&userPW=cluster_rest&pretty=1'
[
   "mid05tor12cn01",
   "mid05tor12cn02",
   "mid05tor12cn03"
]
```
So the "nodestat" correct command is:
```
[root@briggs01 ws]# curl -X GET -k 'https://briggs01/xcatws/nodes/mid05tor12cn0\[1-3\]/nodestat?userName=wsuser&userPW=cluster_rest&pretty=1'
{
   "mid05tor12cn01":{
      "nodestat":"noping"
   },
   "mid05tor12cn02":{
      "nodestat":"noping"
   },
   "mid05tor12cn03":{
      "nodestat":"noping"
   }
}
```

**Comment by gurevichmark** [comment]
@bybai Ok, good. Thanks for the explanation.
Also, is there way to specify a regular expression, like this:
```
[root@briggs01 ~]# nodels /mid05tor12cn.*
mid05tor12cn01
mid05tor12cn02
mid05tor12cn02k02
mid05tor12cn03
mid05tor12cn04
mid05tor12cn05
mid05tor12cn06
mid05tor12cn07
mid05tor12cn08
mid05tor12cn09
mid05tor12cn10
mid05tor12cn11
mid05tor12cn12
mid05tor12cn13
mid05tor12cn14
mid05tor12cn15
mid05tor12cn16
mid05tor12cn17
mid05tor12cn18
[root@briggs01 ~]#
```

I tried something like this with REST, but it did not work:
```
[gurevich@c910loginx01 xcat-core]$ curl -X GET -k 'https://briggs01/xcatws/nodes/\/mid05tor12cn\.\*/nodestat?userName=wsuser&userPW=cluster_rest&pretty=1'
{
   "errorcode":"2",
   "error":"Unspported resource."
}

[gurevich@c910loginx01 xcat-core]$
```

**Comment by bybai** [comment]
Hi @gurevichmark , I think "/" is special for URL, multiple "/" is the sample effect with "/" in URL, for example "http://xcat-docs.readthedocs.io/en/stable/" is the same page with "http://xcat-docs.readthedocs.io/en/////stable/".  
So here xcatws.cgi does not support regular expression start with "/", in xcatws.cgi code, you can find:
```
        nodestat => {
            desc => "[URI:/nodes/{noderange}/nodestat}] - The attributes resource for the node {noderange}",
            matcher => '^/nodes/[^/]*/nodestat$',    =========> / is exclude
```
So `/mid05tor12cn.*` cannot match `matcher`.

**Comment by gurevichmark** [comment]
So that means that not all noderange formats supported by CLI will work in REST API.

Perhaps, as part of this PR, you should add an example of the new "nodels" usage to http://xcat-docs.readthedocs.io/en/stable/advanced/restapi/restapi_resource/restapi_reference.html#node-resources and list the noderanges that are not supported ?

**Pull request merged**
