### PR TITLE
Update README file

### PR DESCRIPTION
**Pull request by gurevichmark**
Update README file for building xCAT documentation

### CODE REVIEW

**Comment by daniceexi** [comment]
@gurevichmark What's the update/upgrade for? Is there any new feature of Sphinx required by xCAT?

**Comment by gurevichmark** [comment]
@daniceexi There are no new features on Sphinx required by xCAT that I know of. 
I just thought it would be useful to tell the user how to get to the latest level, in case there are some bug fixes in future levels of Sphinx.

**Comment by daniceexi** [comment]
@gurevichmark Thanks for the explanation. I am OK with the change.

**Comment by whowutwut** [comment]
Thanks will merge

**Pull request merged**
