### PR TITLE
Add reseat to rpower man page

### PR DESCRIPTION
**Pull request by aduffy19**
Add reseat to rpower man page, under "Blade specific" sections. Also add
definition.

### CODE REVIEW

**Comment by whowutwut** [comment]
Hi @aduffy19 We have a utility `create_man_pages.py` the generates the .rst files for the documentation on RTD.. can you run that an also include the generated rst files in the Pull request?

**Comment by whowutwut** [comment]
Also welecome!  We thank you for your interest.  To participate in xCAT project, we require a CLA or CCLA signed. if you are covered under a corpoarate CLA, can you provide the company,  I couldn't tell from your github profile.  http://xcat-docs.readthedocs.io/en/stable/developers/license/index.html

**Comment by jjohnson42** [comment]
I'm surprised that someone modifying a man page should have to run that, rather than that being part of building releases...

**Comment by aduffy19** [comment]
I'm at Lenovo -- would I be covered?

**Comment by aduffy19** [comment]
Did this wrong, closing this request and opening a new one.

**Comment by whowutwut** [comment]
@aduffy19 yes you are good. Thanks. I thought I shad seen stuff from the past

@jjohnson42 yea let me look into that... I forget what blocked it in the past

**Pull request closed without merging**
