### PR TITLE
issue 1149: add ntpdate in the pkglist for ubuntu16.04

### PR DESCRIPTION
**Pull request by daniceexi**

### CODE REVIEW

**Comment by daniceexi** [comment]
Fix issue for #1149 that has not ``ntpdate`` to be installed for ubuntu 16.04 diskful and diskless compute node.
``ntpdate`` was installed by default, now for ubuntu 16.04, we have to require it explicitly.

**Comment by immarvin** [comment]
agree to merge

**Comment by whowutwut** [comment]
Why do we still update the base compute.pkglist file? Which version of Ubuntu should use that?

**Comment by daniceexi** [comment]
all the x86_64 for ubuntu will share this pkglist file

**Pull request merged**
