### PR TITLE
`xcatd` improvements

### PR DESCRIPTION
**Pull request by samveen**
This is a pull request to do a cleanup of the `xCAT-Server/sbin/xcatd` code to better match xcat code formatting guidelines, along with minor improvements as I find them.

Please do not merge just yet.

### CODE REVIEW

**Comment by samveen** [comment]
@whowutwut @daniceexi @jjohnson42 I was planning on running perl-tidy on `xCAT-Server/sbin/xcatd`. Please let me know if anyone has any issues with the following:
```
perltidy -w -syn -g -opt -i=4 -nt -io -nbbc -kbl=2 -pscf=-c  xcat-core/xCAT-server/sbin/xcatd
```
ref: http://perltidy.sourceforge.net/perltidy.html

**Comment by daniceexi** [comment]
@samveen I am fine with the code reformat with perltidy, please do that add the changed file for review.

**Comment by samveen** [comment]
@daniceexi @whowutwut Please review.

**Comment by samveen** [comment]
@daniceexi @whowutwut Please review.

**Comment by whowutwut** [comment]
I pulled down the changes because the diff doesn't work in GitHub, the formatting looks nice and neat... I'm okay to merge this.  @daniceexi  if no objections, let's merge it in.

**Comment by samveen** [comment]
Removed `[WIP]` from title post review.

**Comment by daniceexi** [comment]
I am Ok with the change. Thanks @samveen

**Pull request merged**
