### PR TITLE
Fix issue of packimage -m txc

### PR DESCRIPTION
**Pull request by penguhyang**
1. redefine the packimage code to make distint
2. fix issue of packimage -m txc

### CODE REVIEW

**Comment by immarvin** [comment]
please make sure the commit only include the modification on the problem you fix

**Comment by daniceexi** [comment]
@penguhyang Please make one commit to focus on a specific purpose so that reviewer can easily figure out your change.

**Comment by immarvin** [comment]
hi @penguhyang , please make sure ``xz`` is added into initrd,  check whether ``xz`` is installed on MN. if not, you need to prompt user on this.
The ``packimage`` manpage does not include the description on ``-m``, you need to add this

**Comment by immarvin** [comment]
agree to.merge

**Comment by immarvin** [comment]
the previos PR: https://github.com/xcat2/xcat-core/pull/699

**Comment by daniceexi** [comment]
As we discussed today, we need figure out a way to improve the performance of compressing the image.

**Comment by immarvin** [comment]
please refer to this issue: https://github.com/xcat2/xcat-core/issues/922

**Pull request merged**
