### PR TITLE
Support http repos for otherpkgs #4042

### PR DESCRIPTION
**Pull request by immarvin**
fix issue https://github.com/xcat2/xcat-core/issues/4042:

UT:

````
[root@c910f03c05k21 xcat-core]# lsdef -t osimage -o rhels7.3-ppc64le-install-service
Object name: rhels7.3-ppc64le-install-service
    imagetype=linux
    osarch=ppc64le
    osdistroname=rhels7.3-ppc64le
    osname=Linux
    osvers=rhels7.3
    otherpkgdir=/install/post/otherpkgs/rhels7.3/ppc64le,http://aaa/xyz,http://bbb/xyz
    otherpkglist=/opt/xcat/share/xcat/install/rh/service.rhels7.ppc64le.otherpkgs.pkglist
    pkgdir=/install/rhels7.3/ppc64le
    pkglist=/opt/xcat/share/xcat/install/rh/service.rhels7.ppc64le.pkglist
    postscripts=servicenode
    profile=service
    provmethod=install
    template=/opt/xcat/share/xcat/install/rh/service.rhels7.tmpl
[root@c910f03c05k21 ~]# updatenode c910f03c05k27 -P otherpkgs -V
...
[root@c910f03c05k21 xcat-core]# ssh c910f03c05k27 cat /etc/yum.repos.d/xCAT-otherpkgs*.repo
[xcat-otherpkgs0]
name=xcat-otherpkgs0
baseurl=file:///install/post/otherpkgs/rhels7.3/ppc64le/xcat/xcat-core
enabled=1
gpgcheck=0
[xcat-otherpkgs1]
name=xcat-otherpkgs1
baseurl=http://aaa/xyz
enabled=1
gpgcheck=0
[xcat-otherpkgs2]
name=xcat-otherpkgs2
baseurl=http://bbb/xyz
enabled=1
gpgcheck=0
````

UT for diskless:
````
[root@c910f03c05k21 ~]# lsdef -t osimage -o  rhels7.3-ppc64le-netboot-compute
Object name: rhels7.3-ppc64le-netboot-compute
    addkcmdline= uftp=true uftpdelay=30 uftpport=1044 md5sum=3cd1b6109a74ba924d2720beffd7423e
    exlist=/opt/xcat/share/xcat/netboot/rh/compute.rhels7.ppc64le.exlist
    imagetype=linux
    osarch=ppc64le
    osdistroname=rhels7.3-ppc64le
    osname=Linux
    osvers=rhels7.3
    otherpkgdir=/install/post/otherpkgs/rhels7.3/ppc64le,http://aa.com/bb,http://aa.com/cc
    otherpkglist=/tmp/list
    permission=755
    pkgdir=/install/rhels7.3/ppc64le
    pkglist=/opt/xcat/share/xcat/netboot/rh/compute.rhels7.ppc64le.pkglist
    postinstall=/opt/xcat/share/xcat/netboot/rh/compute.rhels7.ppc64le.postinstall
    profile=compute
    provmethod=netboot
    rootimgdir=/install/netboot/rhels7.3/ppc64le/compute

[root@c910f03c05k21 ~]# cat /tmp/genimage.8886.yum.conf
[rhels7.3-ppc64le-0]
name=rhels7.3-ppc64le-0
baseurl=file:///install/rhels7.3/ppc64le
gpgpcheck=0

[otherpkgs1]
name=otherpkgs1
baseurl=http://aa.com/bb
gpgpcheck=0

[otherpkgs2]
name=otherpkgs2
baseurl=http://aa.com/cc
gpgpcheck=0

[otherpkgs3]
name=otherpkgs3
baseurl=file:///install/post/otherpkgs/rhels7.3/ppc64le/xcat
gpgpcheck=0
````

### CODE REVIEW

**Comment by mattaezell** [comment]
Thanks @immarvin.  Will you show a UT for running `genimage` with these http repos enabled?  We really need these packages installed in our image, not installed to the node at each boot.  Thanks!

**Comment by immarvin** [comment]
HI @mattaezell , I looked into the code, seems internet urls in otherpkgdir for redhat diskless has been supported before this PR, any problem when you used it?

this PR covers the diskful installation.

**Comment by mattaezell** [comment]
Hi @immarvin.  The [docs](http://xcat-docs.readthedocs.io/en/stable/guides/admin-guides/references/man5/linuximage.5.html?highlight=otherpkgdir) say:
> Only 1 local directory supported at present.

I haven't tried it with http repos or comma-separated.  I can try tomorrow, but when I looked in the code, I didn't see where it was handling that.

**Comment by bybai** [comment]
@immarvin , could you update the ``linuximage`` man page about otherpkgdir at the same time ? http://xcat-docs.readthedocs.io/en/stable/guides/admin-guides/references/man5/linuximage.5.html?highlight=otherpkgdir

**Comment by immarvin** [comment]
hi @mattaezell . sorry, I made a mistake to check the src code, rh/genimage covers internet repos in pkgdirs instead  of otherpkgdir, please forget my last comments. I will refine the PR to support the  internet repos for rh/genimage

**Comment by immarvin** [comment]
hi @bybai , the code is updated

**Comment by bybai** [comment]
Hi @immarvin , Could you paste genimage UT result here? Thanks

**Comment by immarvin** [comment]
hi @bybai , the UT result for diskless is supplemented

**Comment by bybai** [comment]
I am ok to merge it.

**Pull request merged**
