### PR TITLE
modify upload location to xcat.org

### PR DESCRIPTION
**Pull request by tingtli**
modify xcat packages upload location to xcat.org

### CODE REVIEW

**Comment by tingtli** [comment]
@whowutwut  Hi victor, please help review the code. Thanks!
I know you are using the build machine for the autobuild environment. Please let me know when I can use it. I will verify the new code on the build machine.

**Comment by whowutwut** [comment]
I am ok with the changes

**Comment by whowutwut** [comment]
@tingtli  

You can use the build machine at any time... the autobuild environment is self contained in ``/media/xcat/build/xcat2_autobuild`` and ``/media/xcat/build/xcat2_autobuild_daily_builds``.
The old build environment is at: ``/media/xcat/build/old/linux/xcat2/build``

**Comment by whowutwut** [comment]
This pull request is in reference to Issue #252

**Pull request merged**
