### PR TITLE
fix xcatprobe osdeploy performance bugs

### PR DESCRIPTION
**Pull request by xuweibj**
fix issue #2497 #2489 #2482

### CODE REVIEW

**Comment by xuweibj** [comment]
Hi @gurevichmark , 
Could you help to review the output message(especially from 702 to 707)? 
Thank you.

**Comment by gurevichmark** [comment]
@xuweibj Can you please explain when the lines 702-707 will be shown and what they will look like in the output ?

**Comment by xuweibj** [comment]
Hi @gurevichmark , when use -p phase, output will be like this:
```
# xcatprobe -w osdeploy -n c910f03c17k20 -p phase
The install NIC in current server is enp0s1                                                                       [INFO]
All nodes to be deployed are valid                                                                                [ OK ]
-------------------------------------------------------------
Start capturing every message during OS provision process....
-------------------------------------------------------------

[c910f03c17k20] 20:55:04 Use command rpower to reboot node c910f03c17k20
[c910f03c17k20] 20:55:07 Node status is changed to powering-on
[c910f03c17k20] 20:55:12 Receive DHCPDISCOVER via enp0s1
[c910f03c17k20] 20:55:12 Send DHCPOFFER on 10.3.17.20 back to 42:d0:0a:03:11:14 via enp0s1
[c910f03c17k20] 20:55:12 DHCPREQUEST for 10.3.17.20 (10.3.5.4) from 42:d0:0a:03:11:14 via enp0s1
.......
[c910f03c17k20] 21:04:01 Node status is changed to booted
[c910f03c17k20] 21:04:01 provision completed.(c910f03c17k20)
[c910f03c17k20] 21:04:01 provision completed                                                                      [ OK ]
All nodes specified to monitor, have finished OS provision process                                                [ OK ]
======================  Summary  =====================
All nodes provisioned successfully                                                                                [ OK ]
------------------------------------------------------------------------
|                           Time for Phases                            |
------------------------------------------------------------------------
| NODE          | SVRBOOT  | INSTALL  | POST     | POSTBOOT | ELAPSED  |
| c910f03c17k20 | 00:00:08 | 00:02:29 | 00:00:19 | 00:00:00 | 00:08:57 |
------------------------------------------------------------------------
SVRBOOT  : Time from rpower to CN get ip
INSTALL  : Time from download first rpm/deb package to the last
POST     : Time for running postscript
POSTBOOT : Time for running postbootscript
ELAPSED  : Time for provision
```

**Comment by hu-weihua** [comment]
I have reviewed the change and agree to merge, thanks @xuweibj

**Pull request merged**
