### PR TITLE
Update Utils.pm

### PR DESCRIPTION
**Pull request by pravinpawar1987**
### The modification include

_##item1_

_##item2_

### The UT result
`##The UT output##`

# Please remove this line and below if fix issue

# Please remove this line and above for tasks or features

### The PR is for task _#xxx_ or to implement feature #xxx

_##Feature description##_

### The content of the PR:
* [ ] _##The mini-design link_
* [ ] _##The basic code logic_

### The UT result
`##The UT output##`

### CODE REVIEW

**Comment by pravinpawar1987** [comment]
Alma Linux support added

**Comment by pravinpawar1987** [comment]
Alma Linux support Added

**Comment by gurevichmark** [comment]
@pravinpawar1987

* Thanks for your contribution and support of the xCAT project. Before merging any pull requests, we require all users to first submit a Contributor License Agreement (CLA). The license agreement can be found here: https://xcat-docs.readthedocs.io/en/latest/developers/license/contributors.html
* Your change on line 2474 includes a string `3727` which is probably a typo of the next line number you were updating. Can you please submit another commit fixing that typo.

**Comment by besawn** [comment]
This pull request has been incorporated into #7314.

**Pull request closed without merging**
