### PR TITLE
Port Generic CentOS check from Lenovo tree

### PR DESCRIPTION
**Pull request by jjohnson42**
This will do a more generic check if a discid is not found.

### CODE REVIEW

**Comment by cxhong** [comment]
@jjohnson42 , `copycds` still failed with this fix
```
# diff anaconda.pm anaconda.pm.orig
2067,2068d2066
<     } elsif ($desc and $desc =~ /CentOS Linux (.*)/) {
<           $distname = "centos" . $1;

]# copycds CentOS-7-power9-Minimal-1810.iso
Error: [f6u13k13]: copycds could not identify the ISO supplied, you may wish to try -n <osver>
```

**Comment by cxhong** [comment]
The `CentOS-7-power9-Minimal-1810.iso`  doesn't contain `.discinfo`,  that's why failed.

with @jjohnson42  fixes, and if iso file contains .discinfo,  the `copycds` works
```
# ls -ltr .discinfo
-r--r--r-- 1 root root 44 Aug 15 17:51 .discinfo
# cat .discinfo
1565905914.062055
CentOS Linux 8
x86_64
ALL
````

**Comment by jjohnson42** [comment]
What does discinfo look like on that CentOS-7-power9-Minimal?

Does it work on x86 centos 8?

**Comment by cxhong** [comment]
somehow, `CentOS-7-power9-Minimal-1810.iso` doesn't contain `.discinfo` file.  not sure where we downloaded before.  
`CentOS-8-x86_64-1905-dvd1.iso` has `.discinfo` file,  copycds works with your fixes.

**Comment by bybai** [comment]
I think CentOS-7-power9-Minimal-1810.iso does not have wget in its repo, which can cause diskfull installation failure, how do you handle this problem?

**Pull request merged**
