### PR TITLE
add documents about Set Up Web Service for REST API and Mixed Cluster

### PR DESCRIPTION
**Pull request by penguhyang**
http://10.2.9.7
see more details

### CODE REVIEW

**Comment by whowutwut** [comment]
Just a general comment, to avoid the "merge remote branch 'upstream/master'"  commits that you have in your pull request, you can work on the changes in a separate branch created off of your master.   Then the pull request can be done using the separate branch and you don't need to merge the upstream changes since they don't affect any of the files you are working with. 

Also while you wait for the pull request to be reviewed, you not cannot work on another item using your master branch because any changes you commit will automatically go into this pull request.

**Comment by whowutwut** [comment]
Also the URL link above should not be added to this.. since that URL is private to our development environment and cannot be accessed from outside the intranet.  :)

**Comment by daniceexi** [comment]
@whowutwut Regarding the IBM internal web server that offered by @penguhyang, xCAT team members in IBM can access it. It's useful to improve the efficiency to review the doc change. 

Since most of the doc change is reviewed by xCAT team members in IBM, it's useful. If someone out of IBM wants to review the doc change, just use the original way.

**Comment by penguhyang** [comment]
@whowutwut I will close this pull request and use the new branch.

**Pull request closed without merging**
