### PR TITLE
update for xCAT 2.14.2 release

### PR DESCRIPTION
**Pull request by tingtli**
update for xCAT 2.14.2 release

### CODE REVIEW

**Comment by chuckbrazie** [comment]
I am out of the office until 07/16/2018.

I am out of the office until  Monday July 16.


Note: This is an automated response to your message  "Re: [xcat2/xcat-core]
update for xCAT 2.14.2 release (#5385)" sent on 7/10/18 2:35:53 AM.

This is the only notification you will receive while this person is away.

**Comment by chuckbrazie** [comment]
I am out of the office until 07/16/2018.

I am out of the office until  Monday July 16.


Note: This is an automated response to your message  "[xcat2/xcat-core]
update for xCAT 2.14.2 release (#5385)" sent on 7/10/18 2:33:16 AM.

This is the only notification you will receive while this person is away.

**Comment by tingtli** [comment]
Since we have some discussion for this PR, i will close this pr and open a new one when we make the decision.

**Comment by chuckbrazie** [comment]
I am out of the office until 07/16/2018.

I am out of the office until  Monday July 16.


Note: This is an automated response to your message  "Re: [xcat2/xcat-core]
update for xCAT 2.14.2 release (#5385)" sent on 7/10/18 8:51:10 AM.

This is the only notification you will receive while this person is away.

**Pull request closed without merging**
