### PR TITLE
Fix issue 1638: Genesis not wait long enough time to have NICs get IP…

### PR DESCRIPTION
**Pull request by zet809**
… address
Fix issue #1638

### CODE REVIEW

**Comment by daniceexi** [comment]
@whowutwut could you confirm that the top of rack switch has NTP enabled?

**Comment by gurevichmark** [comment]
Changes look good to me.

**Comment by whowutwut** [comment]
Sorry, was merged before I got a chance to comment.  

One thought that I had here is whether we should keep the existing code and simply add another fail over test...  The behavior right now is that we simply do not get an IP address because we did not wait long enough.  

However, I think there are problems even after Genesis regarding port-fast, so I think maybe we should have left the existing code. If it fails to get an IP address, print a message to inform the user of possible options to resolve it.  I think if genesis gets the IP address in HW discovery,  it doesn't necessarily mean that the OS will be able to get the IP address unless some configuration is fixed on the switch side.

**Comment by daniceexi** [comment]
@whowutwut Do you mean we can recreate this issue even when the **STP** on the edge switch is disabled. If so I think we need figure out why this happens first.

**Pull request merged**
