### PR TITLE
Resolve issues with xCAT-genesis-builder rpm to more easily create the xCAT-genesis-base

### PR DESCRIPTION
**Pull request by whowutwut**
Some issues with the xCAT-genesis-builder. 

* On a clean node, the `buildrpm` always fails the first time because the rpmbuild directories are not created 
* The dependencency rpms that are required to successful build the xCAT-genesis-base are not pulled in automatically. 

This pull request attempts to resolve the issues above. 

Even with the changes, I'm unable to resolve the following errors: 
```
[root@fs2vm112 ~]# /opt/xcat/share/xcat/netboot/genesis/builder/buildrpm
cp: omitting directory ‘/opt/xcat/share/xcat/netboot/genesis/builder/debian’
Creating the initramfs in /tmp/xcatgenesis.16102.rfs using dracut ...

dracut-install: ERROR: installing 'vconfig'
/usr/lib/dracut/dracut-install -D /var/tmp/dracut.Miu97D/initramfs -a mkswap df brctl vconfig ifenslave ssh-keygen scp clear dhclient lldpad
dracut-install: ERROR: installing 'ntp-wait'
/usr/lib/dracut/dracut-install -D /var/tmp/dracut.Miu97D/initramfs -a poweroff ntpq ntpd ntp-wait hwclock date /usr/share/terminfo/x/xterm /usr/share/terminfo/s/screen /etc/nsswitch.conf /etc/services
dracut-install: ERROR: installing 'mkreiserfs'
dracut-install: ERROR: installing 'reiserfstune'
/usr/lib/dracut/dracut-install -D /var/tmp/dracut.Miu97D/initramfs -a killall logger nc nslookup bc chown chroot dd expr kill mkdosfs parted rsync shutdown sort ssh-keygen tr blockdev findfs insmod kexec lvm mdadm mke2fs pivot_root sshd swapon tune2fs mkreiserfs reiserfstune pvcreate lvremove vgremove vgcreate lvcreate lvscan lvchange vgchange pvdisplay lvdisplay vgdisplay blkid dmsetup sfdisk
Expanding the initramfs into /tmp/xcatgenesis.16102/opt/xcat/share/xcat/netboot/genesis/ppc64/fs ...
204348 blocks
Adding perl libary /usr/share/perl5
Adding perl libary /usr/lib64/perl5
Adding kernel /boot/vmlinuz-ppc64 ...
/root
Tarring /tmp/xcatgenesis.16102/opt into /root/rpmbuild/SOURCES/xCAT-genesis-base-ppc64.tar.bz2 ...
Building xCAT-genesis-base rpm from /root/rpmbuild/SOURCES/xCAT-genesis-base-ppc64.tar.bz2 and /opt/xcat/share/xcat/netboot/genesis/builder/xCAT-genesis-base.spec ...
error: Failed build dependencies:
        /usr/sbin/ntp-wait is needed by xCAT-genesis-base-ppc64-2:2.13.7-snap201709121408.noarch
```

### CODE REVIEW

**Comment by whowutwut** [comment]
@zet809 Can you help take a look at the above and let me know what is missing?

**Comment by zet809** [comment]
Hi, @whowutwut , I am sorry that not applied a PR for xCAT-genesis-builder, I had copied my modifications under fs2vm112:/opt/xcat/share/xcat/netboot/genesis/builder_zet/, pls reference.
And, for `ntp-wait`, there is no such package on RH or Pegas, we need to implement it in xCAT-genesis-scripts.

**Comment by zet809** [comment]
Oh, it seems the ntp-perl package that ship ntp-wait is included in the Optional repo, need to install it before building xCAT-genesis-base 
```
./Server-optional/ppc64le/os/Packages/ntp-perl-4.2.6p5-25.el7_3.2.noarch.rpm
```

**Comment by whowutwut** [comment]
@zet809 Thanks for the info.  With the latest commit, I added in your changes and put the `ntp-wait` Requires back into the spec file.  So if that optional pkg is not there, it will fail to install the builder.  But this prevents the `buildrpm` from failing later down... 
```
[root@fs2vm112 ~]# yum install xCAT-genesis-builder-2.13.7-snap000000000000.noarch.rpm
Loaded plugins: product-id, search-disabled-repos, subscription-manager
This system is not registered with an entitlement server. You can use subscription-manager to register.
Examining xCAT-genesis-builder-2.13.7-snap000000000000.noarch.rpm: 1:xCAT-genesis-builder-2.13.7-snap000000000000.noarch
Marking xCAT-genesis-builder-2.13.7-snap000000000000.noarch.rpm to be installed
Resolving Dependencies
--> Running transaction check
---> Package xCAT-genesis-builder.noarch 1:2.13.7-snap000000000000 will be installed
--> Processing Dependency: ntp-perl for package: 1:xCAT-genesis-builder-2.13.7-snap000000000000.noarch
--> Finished Dependency Resolution
Error: Package: 1:xCAT-genesis-builder-2.13.7-snap000000000000.noarch (/xCAT-genesis-builder-2.13.7-snap000000000000.noarch)
           Requires: ntp-perl
 You could try using --skip-broken to work around the problem
 You could try running: rpm -Va --nofiles --nodigest
[root@fs2vm112 ~]#
```

Then on a new machine with a dev build of the changes, I've added the rpm here and install with yum.

```
[root@fs2vm111 ~]# ls -ltr
total 240
-rw-------. 1 root root 86012 Sep 12 14:12 original-ks.cfg
-rw-------. 1 root root 87513 Sep 12 14:12 anaconda-ks.cfg
-rw-r--r--  1 root root 25948 Sep 13 22:47 xCAT-genesis-builder-2.13.7-snap000000000000.noarch.rpm
-rw-r--r--  1 root root 37104 Sep 13 22:47 ntp-perl-4.2.6p5-25.el7_3.2.noarch.rpm
[root@fs2vm111 ~]# yum -y install ./*.rpm
...
```

Then execute the genesis builder: `/opt/xcat/share/xcat/netboot/genesis/builder/buildrpm` 

The build successfully completes without any ERRORs... and the resulting xCAT-genesis-base is located here:

```
[root@fs2vm111 ~]# ls -ltr /root/rpmbuild/RPMS/noarch/xCAT-genesis-base-ppc64-2.13.7-snap201709132251.noarch.rpm
-rw-r--r-- 1 root root 39770624 Sep 13 22:52 /root/rpmbuild/RPMS/noarch/xCAT-genesis-base-ppc64-2.13.7-snap201709132251.noarch.rpm
```

**Comment by zet809** [comment]
Thx, @whowutwut , I will merge it.

**Pull request merged**
