### PR TITLE
add diskdiscover script

### PR DESCRIPTION
**Pull request by bybai**
Add diskdiscover script into xCAT-genesis-scripts;

My unit test:
x41 ~]# xdsh p8euh "diskdiscover 1014:034a"
p8euh: PCI_ID=1014:034a
p8euh: ----------------------------------------------------------------------------
p8euh: PCI_SLOT_NAME Resource_Path Device Description   Status
p8euh: ------------- ------------- ------ -----------   ---------------------------
p8euh: 0001:08:00.0  0:0:0:0       sg0    0 Array Member Active
p8euh: 0001:08:00.0  0:0:1:0       sg1    Function Disk Active
p8euh: ---------------------------------------------------------------------------
p8euh: Get ipr RAID arrays by PCI_SLOT_NAME: 0001:08:00.0
p8euh: ---------------------------------------------------------------------------
p8euh: Name   PCI/SCSI Location         Description               Status
p8euh: ------ ------------------------- ------------------------- -----------------
p8euh: sda    0001:08:00.0/0:2:0:0       RAID 0 Disk Array         Optimized
x41 ~]#
x41 ~]#
x41 ~]# xdsh p8euh "diskdiscover"
p8euh: --------------------------------------------------------------------------
p8euh: PCI_ID     PCI_SLOT_NAME  Resource_Path  Device  Description   Status
p8euh: ------     -------------  -------------  ------  -----------   ----------------
p8euh: 1014:034a  0001:08:00.0   0:0:0:0        sg0     0 Array Member Active
p8euh: 1014:034a  0001:08:00.0   0:0:1:0        sg1     Function Disk Active
p8euh: -------------------------------------------------------------------
p8euh: Get ipr RAID arrays by PCI_SLOT_NAME: 0001:08:00.0
p8euh: -------------------------------------------------------------------
p8euh: Name   PCI/SCSI Location         Description               Status
p8euh: ------ ------------------------- ------------------------- -----------------
p8euh: sda    0001:08:00.0/0:2:0:0       RAID 0 Disk Array         Optimized
x41 ~]#
x41 ~]#
x41 ~]# xdsh p8euh "diskdiscover 7987987"
p8euh: PCI_ID=7987987
p8euh: There is no PCI_SLOT_NAME for PCI_ID:7987987.
x41 ~]#
x41 ~]#
x41 ~]# xdsh p8euh "diskdiscover -h"
p8euh: Usage: diskdiscover <PCI_ID>
p8euh:        If input parameter is <PCI_ID>, return devices and RAID arrays info by PCI_ID.
p8euh:        If there is no value for <PCI_ID>, return all af/jbod disks and RAID arrays info.

### CODE REVIEW

**Comment by bybai** [comment]
Code structure:
diskdiscover===========> user command to do disk discover, it handles input flags.
raidutils       ===========> all function workers, it does not contain any iprconfig command, it is used by diskdiscover and configraid.
raidcmd     ===========> functions for iprconfig command, it is used by raidutils.

**Comment by daniceexi** [comment]
Added several comments, could you fix them first?

**Comment by bybai** [comment]
@daniceexi  Modified all the details your comments.

**Comment by daniceexi** [comment]
@bybai 
You forget to change the Examples message in the beginning part of the script after unify the output when sepcify the pci id or not.

**Comment by daniceexi** [comment]
I have reviewed the change and agree to check in.

**Pull request merged**
