### PR TITLE
Remove references to sourceforge in xcat-core

### PR DESCRIPTION
**Pull request by whowutwut**
This is a initial pass for removing the references to SF in the xcat-core code

Ran the following command:
``git grep sourceforge  | grep -v "xcat-users@" ``

There still are a bunch of references but I think we need to handle them once the documentation is updated to be more complete

Also removed the getxcatdocs command and simply printing out a message to go to readthedocs to get the documentation

### CODE REVIEW

**Comment by whowutwut** [comment]
@daniceexi  we may not want to merge this pull request until after the build this week.

**Comment by whowutwut** [comment]
I updated based on the review comments,

**Comment by whowutwut** [comment]
@daniceexi  is okay to merge?

**Comment by daniceexi** [comment]
I have reviewed the change and agree to merge.

**Pull request merged**
