### PR TITLE
Proper handle the -no_ssl2 argument of openssl s_client

### PR DESCRIPTION
**Pull request by neo954**
Fix github issue #5365.

### CODE REVIEW

**Comment by immarvin** [comment]
agree to merge

**Comment by chuckbrazie** [comment]
I am out of the office until 07/16/2018.

I am out of the office until  Monday July 16.


Note: This is an automated response to your message  "Re: [xcat2/xcat-core]
Proper handle the -no_ssl2 argument of openssl s_client (#5369)" sent on
7/4/18 5:50:21 AM.

This is the only notification you will receive while this person is away.

**Comment by chuckbrazie** [comment]
I am out of the office until 07/16/2018.

I am out of the office until  Monday July 16.


Note: This is an automated response to your message  "[xcat2/xcat-core]
Proper handle the -no_ssl2 argument of openssl s_client (#5369)" sent on
7/4/18 5:47:53 AM.

This is the only notification you will receive while this person is away.

**Comment by chuckbrazie** [comment]
I am out of the office until 07/16/2018.

I am out of the office until  Monday July 16.


Note: This is an automated response to your message  "Re: [xcat2/xcat-core]
Proper handle the -no_ssl2 argument of openssl s_client (#5369)" sent on
7/4/18 6:48:34 AM.

This is the only notification you will receive while this person is away.

**Comment by chuckbrazie** [comment]
I am out of the office until 07/16/2018.

I am out of the office until  Monday July 16.


Note: This is an automated response to your message  "Re: [xcat2/xcat-core]
Proper handle the -no_ssl2 argument of openssl s_client (#5369)" sent on
7/4/18 7:10:21 AM.

This is the only notification you will receive while this person is away.

**Pull request merged**
