### PR TITLE
Add the -u and -p option back into the man page for bmcdiscover

### PR DESCRIPTION
**Pull request by whowutwut**
Fixes Issue #938

### CODE REVIEW

**Comment by daniceexi** [comment]
* I think we should skip to use {} in the man page for xCAT command . We was using {} to express the parameter is mandatory. But in the Linux, without any bracket  means mandatory. 

* Put the mandatory parameter at end of the **SYNOPSIS** (refer to the **man man**). Even in xcat cmd, we always put the mandatory **noderange** as the first parameter. 

So I recommend the synopsis changes from 

~~~~
B<bmcdiscover> [B<-s> I<scan_method>] B<--range> I<ip_ranges> [{B<-u>|B<--bmcuser>} I<bmc_username> {B<-p>|B<--bmcpasswd>}] [B<-z>] [B<-w>] [B<-t>]
~~~~

to (P.S: I don't like to have both short and long format for one option. It's not necessary.)
~~~~
B<bmcdiscover> [B<-s> I<scan_method>] [B<-u> I<bmc_username> B<-p> I<bmc_password>] [B<-z>] [B<-w>] [B<-t>] B<--range> I<ip_ranges>
~~~~

**Comment by gurevichmark** [comment]
Yes, no brackets means mandatory, [ ] means optional, and { } means "one of".
So technically,  {-i | --bmcip} means either -i or --bmcip needs to be specified. But these 2 options are really the same. So perhaps SYNOPSIS should only list the short version of the option and then in the DESCRIPTION, both short and long can be shown. This way we can get rid of { } for this command.

Also, on the third line of SYNOPSIS, is the "bmc_password" missing following **{-p|--bmcpasswd}**

Finally the SYNOPSIS section does not list -c option only --check. The DESCRIPTION section lists both.

**Comment by whowutwut** [comment]
Propose the following usage: 

```
# bmcdiscover -h

bmcdiscover - Discover BMC (Baseboard Management Controller) using the specified scan method

Usage:
	bmcdiscover [-?|-h|--help]
	bmcdiscover [-v|--version]
	bmcdiscover [-s scan_method] [-u bmc_user] [-p bmc_passwd] [-z] [-w] [-t] --range ip_range

	Check BMC administrator User/Password:

		bmcdiscover -u bmc_user -p bmc_password -i bmc_ip --check

	Check the BMC IP configuration:

		bmcdiscover [-u bmc_user] [-p bmc_passwd] -i bmc_ip --ipsource
```

I'm also going to make changes to have -u and -p optional except for --check option where we are checking the user and password.  In the other case, we should pick up the defaults from the passwd table and overwrite it if the user specifies -u or -p.

**Comment by whowutwut** [comment]
I updated the pull request with the changes

**Comment by daniceexi** [comment]
I have reviewed the change and agree to merge.

**Pull request merged**
