### PR TITLE
Clean up logger messages for xcatroot in diskless boot

### PR DESCRIPTION
**Pull request by whowutwut**
Initial changes to clean up some of the log messages that are being generated during diskless provisioning to attempt to have some log messages to time the process.

### CODE REVIEW

**Comment by whowutwut** [comment]
@zet809  Do you think we should merge this for 2.13..  or possibly wait until the next release?

**Comment by immarvin** [comment]
The modification might impact the diskless provision on rhels6.x, rhels7.x and sles12+, we'd better put off the merge after we release 2.13.

**Comment by zet809** [comment]
@whowutwut Hi, victor, it is last week for xcat2.13 release, I didn't see there is too much goodness to merge it, so I think we can merge it after 2.13 release.

**Comment by whowutwut** [comment]
Ok @zet809  I agree.

**Comment by zet809** [comment]
HI, @whowutwut , I think the modification is OK, once the Conflict is resolved, it can be merged into master branch.

**Comment by samveen** [comment]
Victor, There are some `echo`s in ` xCAT-server/share/xcat/netboot/rh/dracut_033/xcatroot ` which probably should be converted to `logger`s or atleast augmented with `logger`s. A good example would be all the `you are dead` messages.

**Comment by whowutwut** [comment]
@samveen Thanks for pointing that out. I'll take a look at it. 

@zet809 I am going to create another PR because I can't seem to rebase this branch ... the commit with the tab/space cleanup got a little too messy.

**Comment by whowutwut** [comment]
Created a new pull request, closing this one

**Pull request closed without merging**
