### PR TITLE
NextScale NX360 M5 support: add description of -u and -p for rsetboot;patch pasu with the latest version

### PR DESCRIPTION
**Pull request by immarvin**

### CODE REVIEW

**Comment by immarvin** [comment]
hi @daniceexi @whowutwut , would you please review the code ASAP, so that we can make a 2.10.1 snapshot  build  and perform FVT.

**Comment by immarvin** [comment]
updated

**Comment by immarvin** [comment]
@daniceexi ,seems [-V| --verbose] was not processed in rsetboot code. But I think we can keep it there to reserve for future enhancement.

**Comment by daniceexi** [comment]
@immarvin If rsetboot does not support -V, we should remove it from the usage message. It's not reasonable to have a unimplemented flag in the usage.

**Comment by immarvin** [comment]
-V|--verbose removed

**Comment by daniceexi** [comment]
I have reviewed the change and agree to merge.

**Pull request merged**
