### PR TITLE
updatenode -F not work in hierachy env as the user name is FQDN of MN

### PR DESCRIPTION
**Pull request by robin2008**
updatenode -F not work in hierachy env (#4455)
when run `updatenode -F`, we will get the user name in request and set it to `xdcp` via `DSH_FROM_USERID`.

UT:
1, updatenode -F from MN
```
# updatenode c910f03c09k05 -F -V
Running command on c910f03c09k03.pok.stglabs.ibm.com: ip -4 --oneline addr show |awk -F ' ' '{print $4}'|awk -F '/' '{print $1}' 2>&1

Running command on c910f03c09k03.pok.stglabs.ibm.com: chmod -R a+r /install/postscripts 2>&1

  c910f03c09k03.pok.stglabs.ibm.com: Internal call command: xdcp c910f03c09k05 --nodestatus -F /tmp/sync.list
Running internal xCAT command: xdcp ...

Running command on c910f03c09k03.pok.stglabs.ibm.com: ip -4 --oneline addr show |awk -F ' ' '{print $4}'|awk -F '/' '{print $1}' 2>&1

Running command on c910f03c09k03.pok.stglabs.ibm.com: rm /tmp/xdcpsynclist.30297 2>&1
File synchronization has completed for nodes.
```
2, updatenode -F from SN
```
# updatenode c910f03c09k05 -F -V
Running command on c910f03c09k04.pok.stglabs.ibm.com: ip -4 --oneline addr show |awk -F ' ' '{print $4}'|awk -F '/' '{print $1}' 2>&1

Running command on c910f03c09k04.pok.stglabs.ibm.com: chmod -R a+r /install/postscripts 2>&1

  c910f03c09k04.pok.stglabs.ibm.com: Internal call command: xdcp c910f03c09k05 --nodestatus -F /tmp/sync.list
Running internal xCAT command: xdcp ...

Running command on c910f03c09k04.pok.stglabs.ibm.com: ip -4 --oneline addr show |awk -F ' ' '{print $4}'|awk -F '/' '{print $1}' 2>&1

File synchronization has completed for nodes.
```
3, updatenode -F from MN for the node not behind SN
```
# chdef c910f03c09k05 servicenode=
1 object definitions have been created or modified.

# updatenode c910f03c09k05 -F -V
Running command on c910f03c09k03.pok.stglabs.ibm.com: ip -4 --oneline addr show |awk -F ' ' '{print $4}'|awk -F '/' '{print $1}' 2>&1

Running command on c910f03c09k03.pok.stglabs.ibm.com: chmod -R a+r /install/postscripts 2>&1

  c910f03c09k03.pok.stglabs.ibm.com: Internal call command: xdcp c910f03c09k05 --nodestatus -F /tmp/sync.list
Running internal xCAT command: xdcp ...

Running command on c910f03c09k03.pok.stglabs.ibm.com: ip -4 --oneline addr show |awk -F ' ' '{print $4}'|awk -F '/' '{print $1}' 2>&1

File synchronization has completed for nodes.
```

### CODE REVIEW

**Comment by kcgthb** [comment]
Fixes #4455 for me.

**Comment by immarvin** [comment]
hi @robin2008 , seems the fix does not work well for `updatenode` run by non-root user
```
[testme@c910f03c05k04 /]$ updatenode c910f03c17k20 -F
c910f03c17k17: Permission denied, please try again.

c910f03c17k17: Permission denied, please try again.

c910f03c17k17: Permission denied (publickey,gssapi-keyex,gssapi-with-mic,password).

c910f03c17k17: Permission denied, please try again.

c910f03c17k17: Permission denied, please try again.

c910f03c17k17: Permission denied (publickey,gssapi-keyex,gssapi-with-mic,password).

c910f03c17k17: rsync: connection unexpectedly closed (0 bytes received so far) [sender]
c910f03c17k17: rsync error: unexplained error (code 255) at io.c(605) [sender=3.0.9]
c910f03c17k17: Permission denied, please try again.

c910f03c17k17: Permission denied, please try again.

c910f03c17k17: Permission denied (publickey,gssapi-keyex,gssapi-with-mic,password).

c910f03c17k17: rsync: connection unexpectedly closed (0 bytes received so far) [sender]
c910f03c17k17: rsync error: unexplained error (code 255) at io.c(605) [sender=3.0.9]

The following servicenodes: c910f03c17k17, have errors and cannot be updated
 Until the error is fixed, xdcp will not work to nodes serviced by these service nodes.
File synchronization has completed for nodes.
```

**Comment by robin2008** [comment]
```
updatenode c910f03c17k20 -F
File synchronization has completed for nodes.
id
uid=1001(testme) gid=1002(testme) groups=1002(testme)
```
Now `updatenode -F` could work even with the user does not exist on SN or CN.  It always to use `root`, the same behavior as `updatenode -P`

**Comment by robin2008** [comment]
UT:
- root user 
```
updatenode c910f03c05k30 -F -V
Running command on c910f03c05k20: ip -4 --oneline addr show |awk -F ' ' '{print $4}'|awk -F '/' '{print $1}' 2>&1

Running command on c910f03c05k20: chmod -R a+r /install/postscripts 2>&1

  c910f03c05k20: Internal call command: xdcp c910f03c05k30 --nodestatus -F /tmp/sync.list -T
Running internal xCAT command: xdcp ...

Running command on c910f03c05k20: ip -4 --oneline addr show |awk -F ' ' '{print $4}'|awk -F '/' '{print $1}' 2>&1

Running command on c910f03c05k20: rm /tmp/xdcpsynclist.8799 2>&1
TRACE:Default context is XCAT.
TRACE:Fanout Value is 64.
TRACE:Timeout Value is .
 TRACE: Executing Command:/bin/sh -c /tmp/rsync_c910f03c05k30
c910f03c05k30: + /usr/bin/ssh root@c910f03c05k30 '/bin/mkdir -p /etc'
c910f03c05k30: + /usr/bin/rsync --rsync-path /usr/bin/rsync -Lprogtz /var/xcat/syncfiles/etc/hosts /var/xcat/syncfiles/etc/motd root@c910f03c05k30:/etc
File synchronization has completed for nodes.
```
 - non-root user
1, create `testme` in MN, SN and CN
2, setup client for the user and add it into `policy` table
3, and setup key for the user.
```
su - testme
xdsh service -K
xdsh compute -K

updatenode c910f03c05k30 -F -V
Running command on c910f03c05k20: ip -4 --oneline addr show |awk -F ' ' '{print $4}'|awk -F '/' '{print $1}' 2>&1

Running command on c910f03c05k20: chmod -R a+r /install/postscripts 2>&1

  c910f03c05k20: Internal call command: xdcp c910f03c05k30 --nodestatus -F /tmp/sync.list -T
Running internal xCAT command: xdcp ...

Running command on c910f03c05k20: ip -4 --oneline addr show |awk -F ' ' '{print $4}'|awk -F '/' '{print $1}' 2>&1

Running command on c910f03c05k20: rm /tmp/xdcpsynclist.8880 2>&1
TRACE:Default context is XCAT.
TRACE:Fanout Value is 64.
TRACE:Timeout Value is .
 TRACE: Executing Command:/bin/sh -c /tmp/rsync_c910f03c05k30
c910f03c05k30: + /usr/bin/ssh testme@c910f03c05k30 '/bin/mkdir -p /etc'
c910f03c05k30: + /usr/bin/rsync --rsync-path /usr/bin/rsync -Lprogtz /var/xcat/syncfiles/etc/hosts /var/xcat/syncfiles/etc/motd testme@c910f03c05k30:/etc
File synchronization has completed for nodes.
```

**Comment by immarvin** [comment]
agree to merge

**Comment by jjohnson42** [comment]
So while this works, I fear it's a bit relaxed.  Effectively, it lets any valid xcat user impersonate root.

What was supposed to happen (digging in now) was 'trusted' in the policy table was to allow xcatd to set request->{username}, and the plugins be none the wiser about the difference.  validate in xcatd should be doing that, but trying to figure out why it isn't...

**Comment by jjohnson42** [comment]
Confirmed, for a command like 'rpower', then:
          'username' => [
                        'root'
                      ],

For the xdcp spawned by updatenode, the username is not passed correctly.  This is the real root cause...

**Comment by jjohnson42** [comment]
See my proposed solution at https://github.com/xcat2/xcat-core/pull/5013

**Comment by robin2008** [comment]
@jjohnson42 It seems we still hit the issue with non-root user.

**Pull request merged**
