### PR TITLE
Add xcatprobe testcase

### PR DESCRIPTION
**Pull request by gurevichmark**
Added `xcattest` testcase to test `xcatprobe` with a label to make it execute during Travis CI run.

### CODE REVIEW

**Comment by hu-weihua** [comment]
@gurevichmark Thank you very very much for add test case for ``xcatprobe``. That is great!

One comment for this case. ``xcatprobe -l`` is used to list all sub-commands under ``/opt/xcat/probe/subcmds/``. So in this case, I think just match message ``Supported sub commands are:`` is not enough. Could you help to check if the sub-commands listed by ``xcatprobe -l`` match totally the scripts saved under ``/opt/xcat/probe/subcmds/``.

We has a task about this case https://github.ibm.com/xcat2/task_management/issues/105. Since you have started this job, I assigned this task for you.

**Comment by tingtli** [comment]
It's interesting that when i run xcatprobe -l on the latest build. it has following result. Do you think it is a bug? Is there anything that i need to configure more?
```
# xcatprobe -l
Supported sub commands are:
```

**Comment by hu-weihua** [comment]
@tingtli , this issue was triggered by PR #6281 and has been fixed in PR  #6297.
I suppose ``xcatprobe -l`` will work in tomorrow daily build.

**Comment by gurevichmark** [comment]
@hu-weihua Good suggestion, I added another commit.

**Comment by hu-weihua** [comment]
@gurevichmark, Thanks for you commit.

Due to sub-commands of xcatprobe will be added or deleted at any time (depending on customer's requirement). If we hard code the sub-command name in test case, that means once the sub-command change, we have to update test case at same time. That is not good option.

How about use below code.
```
cmd:mkdir -p /tmp/xcatprobe_l
cmd:xcatprobe -l
check:output=~Supported sub commands are:
cmd:xcatprobe -l|grep -v "Supported sub commands are" |awk  '/^[[:graph:]]/ {print $1}'|sort > /tmp/xcatprobe_l/subcmd_from_xcatprobe_l
cmd:ls -l /opt/xcat/probe/subcmds/ |awk '/^-/ {print $9}'|sort > /tmp/xcatprobe_l/subcmd_under_subcmds_dir
cmd:diff -y /tmp/xcatprobe_l/subcmd_from_xcatprobe_l  /tmp/xcatprobe_l/subcmd_under_subcmds_dir
check:rc==0
cmd:rm -rf /tmp/xcatprobe_l
```
If you can implement this logic with higher effective code, that will be great. thanks.

**Comment by gurevichmark** [comment]
@hu-weihua Yes, you are right, the list of subcommands can change in the future.
Since this test it to check basic `xcatprobe` problems, to make sure it is not completely broken, what if we just check if `xcatmn` subcommand is displayed ? Since it is the most important `xcatprobe` subcommad, I think we can assume it will always be there.

**Comment by hu-weihua** [comment]
@gurevichmark when ``xcatprobe`` script to load sub-command, it will check the syntax of each sub-command. It also check if the interface of sub-command satisfy the framework of xCAT Probe. If any sub-command has problem, the loading of this sub-command will fail. So ``xcatprobe -l`` can reflect a lot of problem. If this case failed, we will find syntax problem of any sub-command quickly. So I think It is better to include the logic I listed in above comment.

**Comment by gurevichmark** [comment]
New commit added to verify output `xcatprobe -l` matches contents of `/opt/xcat/probe/subcmds/` directory.

**Comment by hu-weihua** [comment]
@gurevichmark, thank you a lot for new commit. I noticed you added ``ci_test`` label for this case. But in CI environment, there is no ``xcatprobe`` installed. That was why this test case failed in CI. 

Due to CI test failed, the ``merge pull request`` bottom is disable, so I can not merge this pull request. 

Two solutions:

* 1 Could you modify ``travis.pl`` to install ``xcatprobe`` ahead? Then let CI test pass. 

* 2 Move out ``ci_test`` label. In this way, ``xcatprobe_work`` won't run and block CI test.  If we enhance ``travis.pl`` to support ``xcatprobe`` later, we can add ``ci_test`` label back. 

Of cause, if you can choose option 1, I appreciate for it.  That is great help.

**Comment by gurevichmark** [comment]
@hu-weihua I chose choice 1 to add `xcatprobe` to the CI.
But while testing this, I found the following issue -
`apt-get` installs `xcat-probe` and we can run `xcatprobe -l`. But the list of subcommands displayed is missing `switch_macmap`. The reason is because the needed file `/opt/xcat/probe/subcmds/bin/switchprobe` is missing, even if there is a directory `/opt/xcat/probe/subcmds/switch_macmap`
This `/opt/xcat/probe/subcmds/bin/switchprobe` file is linked during `%post` in `xCAT-probe/xCAT-probe.spec`. Do you know if this `.spec` file is used during install of `xcat-probe` on Ubuntu ?

**Comment by hu-weihua** [comment]
@gurevichmark, Thanks for you great help.

It seemed you have found a bug about xcatprobe in ubuntu. 
```
root@c910f04x12v05:/opt/xcat/probe/subcmds# lsxcatd -a
Version 2.15 (git commit 7873494d3c00a9232745990bee2f2f442198d4ef, built Tue May 14 06:21:19 EDT 2019)
This is a Management Node
dbengine=SQLite

root@c910f04x12v05:/opt/xcat/probe/subcmds# cat /etc/*release*
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=16.04
DISTRIB_CODENAME=xenial
DISTRIB_DESCRIPTION="Ubuntu 16.04.5 LTS"
NAME="Ubuntu"
VERSION="16.04.5 LTS (Xenial Xerus)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 16.04.5 LTS"
VERSION_ID="16.04"
HOME_URL="http://www.ubuntu.com/"
SUPPORT_URL="http://help.ubuntu.com/"
BUG_REPORT_URL="http://bugs.launchpad.net/ubuntu/"
VERSION_CODENAME=xenial
UBUNTU_CODENAME=xenial

root@c910f04x12v05:/opt/xcat/probe/subcmds# pwd
/opt/xcat/probe/subcmds

root@c910f04x12v05:/opt/xcat/probe/subcmds#  ./switch_macmap c910f04x12v06
[debug]  :sh: /opt/xcat/probe/subcmds/bin/switchprobe: No such file or directory
```
xcatprobe sub-command ``switch_macmap`` depending on a script ``/opt/xcat/probe/subcmds/bin/switchprobe`` which is a link to  ``/opt/xcat/bin/xcatclient``. In xcat RPM version, this setting is configured in Spec file. But in ubuntu, we forgot to add it into ``...xcat-core/xCAT-probe/debian/rules``. This is build script in ubuntu. So that is a bug.

**Comment by gurevichmark** [comment]
Yes, I will work on issue #6313

**Comment by hu-weihua** [comment]
@gurevichmark  Thanks a million for all you have done.

**Pull request merged**
