### PR TITLE
Add a better label to display in the boot loader to identify genesis boot

### PR DESCRIPTION
**Pull request by whowutwut**
"xCAT" label is used whenever doing network boot.  It's hard to differentiate whether we are doing OS provisioning or booting to Genesis to do hardware discovery.   Added more info to the label to differentiate when the network boot is doing Genesis. 

Before:
```
[root@fs1 p]# cat *
default xCAT
   label xCAT
   kernel http://10.3.29.2:80//tftpboot/xcat/genesis.kernel.ppc64
   initrd http://10.3.29.2:80//tftpboot/xcat/genesis.fs.ppc64.gz
   append "quiet xcatd=10.3.29.2:3001 "
default xCAT
   label xCAT
   kernel http://127.0.0.1:80//tftpboot/xcat/genesis.kernel.ppc64
   initrd http://127.0.0.1:80//tftpboot/xcat/genesis.fs.ppc64.gz
   append "quiet xcatd=127.0.0.1:3001 "
default xCAT
   label xCAT
   kernel http://192.168.3.29:80//tftpboot/xcat/genesis.kernel.ppc64
   initrd http://192.168.3.29:80//tftpboot/xcat/genesis.fs.ppc64.gz
   append "quiet xcatd=192.168.3.29:3001 "
default xCAT
   label xCAT
   kernel http://50.3.29.1:80//tftpboot/xcat/genesis.kernel.ppc64
   initrd http://50.3.29.1:80//tftpboot/xcat/genesis.fs.ppc64.gz
   append "quiet xcatd=50.3.29.1:3001 "
```
After 
```
[root@fs1 p]# mknb ppc64
Creating genesis.fs.ppc64.gz in /tftpboot/xcat
[root@fs1 p]# cat *
default xCAT
   label xCAT Genesis (10.3.29.2)
   kernel http://10.3.29.2:80//tftpboot/xcat/genesis.kernel.ppc64
   initrd http://10.3.29.2:80//tftpboot/xcat/genesis.fs.ppc64.gz
   append "quiet xcatd=10.3.29.2:3001 "
default xCAT
   label xCAT Genesis (127.0.0.1)
   kernel http://127.0.0.1:80//tftpboot/xcat/genesis.kernel.ppc64
   initrd http://127.0.0.1:80//tftpboot/xcat/genesis.fs.ppc64.gz
   append "quiet xcatd=127.0.0.1:3001 "
default xCAT
   label xCAT Genesis (192.168.3.29)
   kernel http://192.168.3.29:80//tftpboot/xcat/genesis.kernel.ppc64
   initrd http://192.168.3.29:80//tftpboot/xcat/genesis.fs.ppc64.gz
   append "quiet xcatd=192.168.3.29:3001 "
default xCAT
   label xCAT Genesis (50.3.29.1)
   kernel http://50.3.29.1:80//tftpboot/xcat/genesis.kernel.ppc64
   initrd http://50.3.29.1:80//tftpboot/xcat/genesis.fs.ppc64.gz
   append "quiet xcatd=50.3.29.1:3001 "
```

Here's an example in petitboot:

image

### CODE REVIEW

**Comment by whowutwut** [comment]
@zet809  I didn't actually run this on an x86_64 environment, i will do that tomorrow but I would like to just get your opinion or comments about this change...

**Comment by zet809** [comment]
@whowutwut Looks great to me, thx.
A small comment that the string "xCAT" after default maybe need to be the same string "xCAT Genesis (x.x.x.x)" as after "label".
BTW, do you have plan to modify normal netboot configuration file with a similar label?

**Comment by whowutwut** [comment]
@zet809  can you explain what the default label is for if we only have 1 entry? 

I ran some more testing on this, turns out that my changes causes petitboot to NOT count down and automatically boot into Genesis... It's very puzzling, so until we figure this out, let's not merge this.  

I've tried today to add quotes around the label and force a delay=10...
```
 [root@fs1 xCAT_plugin]# diff mknb.pm mknb.pm.orig 
257c257
< 	 print $cfg "   label=\"xCAT Genesis (".$normnets->{$_}.")\"\n";
---
> 	 print $cfg "   label=\"xCAT Genesis\"\n";
274,275c274
<          print $cfgfile "   delay=10\n";
<          print $cfgfile "   label \"xCAT Genesis (".$normnets->{$_}.")\"\n";
---
>          print $cfgfile "   label xCAT\n";
312,313c311
<          print $cfgfile "   delay=10\n";
<          print $cfgfile "   label \"xCAT Genesis (".$normnets->{$_}.")\"\n";
---
>          print $cfgfile "   label xCAT\n";
```

Nothing worked. When I restored it to a single label, it counted down and booted into genesis.  any thoughts?

**Comment by zet809** [comment]
@whowutwut Hi, victor
 # cat /tftpboot/pxelinux.cfg/p/192.168.0.0_16
default xCAT-Genesis-(192.168.3.29)   --> This is the default label I mean.
   delay=10
   label "xCAT-Genesis-(192.168.3.29)"
   kernel http://192.168.3.29:80//tftpboot/xcat/genesis.kernel.ppc64
   initrd http://192.168.3.29:80//tftpboot/xcat/genesis.fs.ppc64.gz
   append "quiet xcatd=192.168.3.29:3001 "
And for your issue, it seems space can not be included in label. The default label above "xCAT-Genesis-(192.168.3.29)" works.

**Comment by whowutwut** [comment]
@zet809 Are you saying that we need to put the label in the default line? I can give that a try..

**Comment by whowutwut** [comment]
@zet809  Thanks for the advice,  It's working now...  I've made a few more changes and cleaned up some of the code in another commit.  

Please review when you have some time.  Thanks!

**Comment by zet809** [comment]
Looks good to me, I agree to merge.

**Pull request merged**
