### PR TITLE
2.12 pcm

### PR DESCRIPTION
**Pull request by mavscjb**

### CODE REVIEW

**Comment by whowutwut** [comment]
@bybai was this also put into the master branch?

**Comment by whowutwut** [comment]
Should this be cherry-picked into master branch?  @bybai @daniceexi ?

**Comment by daniceexi** [comment]
Yes, the changes should be cherry-picked to master branch. @bybai

**Comment by daniceexi** [comment]
@whowutwut Looks like the changes have been merged to master branch by pull request #1340 .
@bybai could you confirm?

**Comment by bybai** [comment]
@whowutwut and @daniceexi , pull request #1340 and #1360  are the same content. I have merged all the same code in both master and 2.12-pcm branch.

**Pull request merged**
