### PR TITLE
release information for 2.14.2

### PR DESCRIPTION
**Pull request by zet809**
Release information update for 2.14.2 release.

### CODE REVIEW

**Comment by hu-weihua** [comment]
It is ok for me, thanks @zet809 .

**Comment by chuckbrazie** [comment]
I am out of the office until 07/16/2018.

I am out of the office until  Monday July 16.


Note: This is an automated response to your message  "Re: [xcat2/xcat-core]
release information for 2.14.2 (#5388)" sent on 7/10/18 8:43:56 AM.

This is the only notification you will receive while this person is away.

**Comment by chuckbrazie** [comment]
I am out of the office until 07/16/2018.

I am out of the office until  Monday July 16.


Note: This is an automated response to your message  "[xcat2/xcat-core]
release information for 2.14.2 (#5388)" sent on 7/10/18 8:40:47 AM.

This is the only notification you will receive while this person is away.

**Comment by chuckbrazie** [comment]
I am out of the office until 07/16/2018.

I am out of the office until  Monday July 16.


Note: This is an automated response to your message  "Re: [xcat2/xcat-core]
release information for 2.14.2 (#5388)" sent on 7/10/18 8:43:29 AM.

This is the only notification you will receive while this person is away.

**Pull request merged**
