### PR TITLE
Support OS install on nvme disk

### PR DESCRIPTION
**Pull request by gurevichmark**
### The PR is to fix issue _#6346_

* Detect `nvme` disk partition format (use `case` instead if `if`. `if` works on RH but fails on Ubuntu. `case` works on both)
* Remember the failure of the `umount` command and do not remove mounted directory as it might wipe out contents of the still mounted disk
* Minor comment changes

RHEL 8.2 or Ubuntu 18.4 provision on nvme disk:
```
[get_install_disk]Contents of /proc/partitions:
major minor  #blocks  name

 259        0 1562813784 nvme0n1
 259        1       8192 nvme0n1p1
 259        2    1048576 nvme0n1p2
 259        3 1561755648 nvme0n1p3
   8       16  976762584 sdb
   8        0  976762584 sda
   7        0     515336 loop0
   7        1    3145728 loop1
   7        2   33554432 loop2
 253        0    3145728 dm-0
 253        1    3145728 dm-1
 253        2 1557557248 dm-2
 253        3    4194304 dm-3

[get_install_disk]Check the partition nvme0n1p1.
mount: /tmp/xcat.getinstalldisk/xcat.getinstalldisk.mount: wrong fs type, bad option, bad superblock on /dev/nvme0n1p1, missing codepage or helper program, or other error.
[get_install_disk]    Partition nvme0n1p1 mount failed or the partition is swap.
[get_install_disk]Check the partition nvme0n1p2.
[get_install_disk]    Partition nvme0n1p2 mount success.
[get_install_disk]    The partition nvme0n1p2 has kernel file.
[get_install_disk]Check the partition nvme0n1p3.
mount: /tmp/xcat.getinstalldisk/xcat.getinstalldisk.mount: unknown filesystem type 'LVM2_member'.
[get_install_disk]    Partition nvme0n1p3 mount failed or the partition is swap.
[get_install_disk]The disks which have kernel:
[get_install_disk]    nvme0n1

[get_install_disk]The disk nvme0n1 information:
[get_install_disk]    disk_wwn=eui.34364a304e1002090025384500000003
[get_install_disk]    disk_path=/devices/pci0030:00/0030:00:00.0/0030:01:00.0/nvme/nvme0/nvme0n1
[get_install_disk]    disk_driver=nvme
[get_install_disk]    Add disk: nvme0n1 eui.34364a304e1002090025384500000003 into wwn thirdchoicedisks
[get_install_disk]The install_disk is /dev/nvme0n1 by sorting wwn and DRIVER.
```

### CODE REVIEW

**Comment by besawn** [comment]
In an AC922 server with both a spinning disk and nvme, does this PR change end up selecting the spinning disk or nvme as the default install disk?

Can the user choose which disk gets used somehow?

**Comment by gurevichmark** [comment]
I could not find anything in xCAT that allows user to indicate install disk.

The logic of `getinstdisk` is to find the disk that had a kernel installed on it previously. If such disk found, that disk is used for installation. If no disk found with previously installed kernel or multiple disks with previously installed kernels are found, the disk with lowest WWN is used for installation. If all of the above fails, `sda` is chosen. 
In all cases, the chosen disk is repartitioned, so no previously installed kernel is used.

**Comment by gurevichmark** [comment]
@besawn Correction to the above statement.

In the `getinstdisk` script, disks are not sorted simply by WWN numbers. They are first sorted by driver type.
First choice preference is given to disks whose drivers are ` "ata_piix"*|"PMC MaxRAID"|"ahci"|"megaraid_sas"`
Second choice preference is given to disks whose drivers are `"mptsas"|"mpt2sas"|"mpt3sas"`
Third choice preference is given to disks whose drivers are everything else other than above, which includes `nvme`.

The `sd` disks in our P9 machines are `ahci`

So `nvme` disk will be chosen for installation if:
a) OS was previously installed on it
b) There are no other disks with drivers  ` "ata_piix"*|"PMC MaxRAID"|"ahci"|"megaraid_sas"|"mptsas"|"mpt2sas"|"mpt3sas"`

**Comment by ruixingw** [comment]
Hi, just curious if this PR will be merged into master soon and included in the next release?

**Comment by besawn** [comment]
@ruixingw Yes, the plan is to merge this PR soon to be included in the next release.

**Comment by ruixingw** [comment]
It seems that this fix does not work with CentOS-8.3.2011-x86_64-dvd1.iso.
I have a single NVMe ssd installed in my compute nodes. I install xCAT on my management node and then manually download this fix getinstdisk and overwrite the one in the system. This was working without a problem when I was using CentOS-8.2.2004-x86_64-dvd1.iso to provision compute nodes. 

Yesterday I updated the osimage to CentOS 8.3. The OS installation failed, complaining that a disk cannot be found (default to /dev/sda in the end, which is not available). I tried the following:
1. I changed the line $install_disk=""$ in /install/autoinst/cn1 to $install_disk=/dev/nvme0n1$ and the installation is then successful, so the problem should be in this file $getinstdisk$. 
2. I tried to go back to the CentOS 8.2 iso (by removing the original image with $rmdef -t osimage$ and then $copycds CentOS-8.2.2004-x86_64-dvd1.iso$.) Without changing the script in /install/autoinst, the installation proceed smoothly. 

Could you please check what's going on?

**Comment by gurevichmark** [comment]
@ruixingw Do you mean in `1.`, you made changes in this block:
```
# Cannot find proper disk for OS install, select the default one "/dev/sda"
if [ -z "$install_disk" ]; then
    install_disk="/dev/sda"
    echo "[get_install_disk]The default install_disk is $install_disk."
fi
```

Perhaps the partition naming for nvme disk is different on CentOS 8.3. Can you run `lsblk` on compute node after installing it with 8.3, using your change in `1.`

**Review by runcong — DISMISSED** [review]

**Comment by gurevichmark** [comment]
Verified with SLES15:
```
mid08tor03cn01:~ # hostnamectl
   Static hostname: linux.local
Transient hostname: mid08tor03cn01
         Icon name: computer
        Machine ID: 4474a12d463c4b8f92d1af78ab3d4480
           Boot ID: f7546f5d334a4db1839f3052da82b828
  Operating System: SUSE Linux Enterprise Server 15
       CPE OS Name: cpe:/o:suse:sles:15
            Kernel: Linux 4.12.14-23-default
      Architecture: ppc64-le
mid08tor03cn01:~ #

mid08tor03cn01:~ # lsblk
NAME        MAJ:MIN RM   SIZE RO TYPE MOUNTPOINT
sda           8:0    1 931.5G  0 disk
sdb           8:16   1 931.5G  0 disk
nvme0n1     259:1    0   1.5T  0 disk
├─nvme0n1p1 259:2    0    40G  0 part /
├─nvme0n1p2 259:3    0 939.2G  0 part /home
└─nvme0n1p3 259:4    0 511.2G  0 part [SWAP]
mid08tor03cn01:~ #

mid08tor03cn01:~ # df -TH
Filesystem     Type      Size  Used Avail Use% Mounted on
devtmpfs       devtmpfs  261G     0  261G   0% /dev
tmpfs          tmpfs     275G     0  275G   0% /dev/shm
tmpfs          tmpfs     275G   34M  275G   1% /run
tmpfs          tmpfs     275G     0  275G   0% /sys/fs/cgroup
/dev/nvme0n1p1 btrfs      43G  2.5G   41G   6% /
/dev/nvme0n1p2 xfs       1.1T  1.1G  1.1T   1% /home
/dev/nvme0n1p1 btrfs      43G  2.5G   41G   6% /var
/dev/nvme0n1p1 btrfs      43G  2.5G   41G   6% /tmp
/dev/nvme0n1p1 btrfs      43G  2.5G   41G   6% /srv
/dev/nvme0n1p1 btrfs      43G  2.5G   41G   6% /.snapshots
/dev/nvme0n1p1 btrfs      43G  2.5G   41G   6% /opt
/dev/nvme0n1p1 btrfs      43G  2.5G   41G   6% /root
/dev/nvme0n1p1 btrfs      43G  2.5G   41G   6% /usr/local
tmpfs          tmpfs      55G     0   55G   0% /run/user/0
mid08tor03cn01:~ #
```

**Comment by gurevichmark** [comment]
@ruixingw Were you able to resolve the issue of installing CentOS-8.3 on NVMe ?

We are getting ready to merge this PR and want to make sure there are no outstanding problems.

**Comment by ruixingw** [comment]
> @ruixingw Were you able to resolve the issue of installing CentOS-8.3 on NVMe ?
> 
> We are getting ready to merge this PR and want to make sure there are no outstanding problems.

I scp'ed /tmp/pre-install.log to my management machine during the installation, see attached. 

[8.2.log](https://github.com/xcat2/xcat-core/files/6066334/8.2.log)
[8.3.log](https://github.com/xcat2/xcat-core/files/6066335/8.3.log)

When I was using CentOS 8.2 image, it can recognize my ssd (/dev/nvme0n1), but fails when I use CentOS 8.3 image (install disk defaults to /dev/sda).

**Comment by ruixingw** [comment]
As a workaround to provision CentOS 8.3 to compute nodes, I changed install_disk from the beginning (line 21: 
install_disk="/dev/nvme0n1"). 
After the installation, here the output of "lsblk" from compute node:
```
[root@hq17 ~]# lsblk
NAME            MAJ:MIN RM  SIZE RO TYPE MOUNTPOINT
nvme0n1         259:0    0  477G  0 disk
├─nvme0n1p1     259:1    0    1G  0 part /boot
└─nvme0n1p2     259:2    0  476G  0 part
  ├─xcatvg-root 253:0    0  472G  0 lvm  /
  └─xcatvg-swap 253:1    0    4G  0 lvm  [SWAP]
```

**Comment by ruixingw** [comment]
I have located the problem originates from the ```udevadm``` command used in line 48 of the script to get ```DEVSIZE```:
```
DEVSIZE=$(udevadm info --attribute-walk --name=$entry|grep size| sed -e 's/[^"]*"//' -e 's/"//'|tail -n 1)
```

On CentOS 8.3, there is an extra attr named ```sqsize``` for SSDs (but not for HDDs). 
```
[root@storage1 ~]# cat /etc/redhat-release
CentOS Linux release 8.3.2011
[root@storage1 ~]# udevadm info --attribute-walk /dev/sda | grep size
    ATTR{size}=="15628053168"
[root@storage1 ~]# udevadm info --attribute-walk /dev/nvme0n1 | grep size
    ATTR{size}=="1000215216"
    ATTRS{sqsize}=="1023"
```
```DEVSIZE``` thus captured that very small value, so all drives and partitions are skipped. 

whereas on CentOS 8.2, there's no ```sqsize```. 
```
[root@hq18 ~]# cat /etc/redhat-release
CentOS Linux release 8.2.2004 (Core)
[root@hq18 ~]# udevadm info --attribute-walk /dev/nvme0n1 | grep size
    ATTR{size}=="1000215216"
```

To fix this, we may could change the grep expression to ```grep \{size```:
```
[root@storage1 ~]# udevadm info --attribute-walk /dev/nvme0n1 | grep \{size
    ATTR{size}=="1000215216"
```
but I am not sure if this works for other distributions as well.

**Comment by besawn** [comment]
@ruixingw Thank you for the quick feedback and root cause analysis.

@gurevichmark Probably a good idea to make the grep for `size` as specific as possible. Expanding on the suggestion @ruixingw made, perhaps something like:
```
udevadm info --attribute-walk /dev/nvme0n1 | grep \{size\}
```
to protect both the start and end of the size attribute?

**Comment by gurevichmark** [comment]
Updated with the `grep \{size\}` suggestion above.

Verified on: RHEL7.6, RHEL8.2, RHEL8.3, SLES15, Ubuntu18

**Review by besawn — APPROVED** [review]
Looks good, thanks.

**Pull request merged**
