### PR TITLE
add discinfo for rhels6.8

### PR DESCRIPTION
**Pull request by immarvin**
fix https://github.com/xcat2/xcat-core/issues/1054
add discinfo for rherls6.8.
The discinfo is from .discinfo of rhels6.8-RC1 iso

### CODE REVIEW

**Comment by daniceexi** [comment]
I have reviewed the change and agree to merge.

**Comment by whowutwut** [comment]
I still think that we should first try and provide an automatic way to determine the os versions based on the files on the ISO image, then as a fall back, write the ISO number into the code..... then this kind of thing will not block copycds when doing testing...

**Comment by daniceexi** [comment]
@immarvin Could you take a look the possibility to use the configuration files in the disc to determine the OS and image name?

**Comment by whowutwut** [comment]
It's possible. I made the change to do it for powerKVM, first try to figure out. If can't then fail to the mapping...

We discussed it but I don't remember the history behind why we decided that we still needed to keep the identifier mapping method... We only do this mapping for red hat....

**Pull request merged**
