### PR TITLE
add copycds -p cases, fix #2699

### LINKED ISSUE #2699: [Test Case] refine test case for copycds
the related issue is https://github.com/xcat2/xcat-core/issues/2630

some test case on ``copycds -p`` should be created

### PR DESCRIPTION
**Pull request by tingtli**
@immarvin  Please review

### CODE REVIEW

**Comment by immarvin** [comment]
i am ok with the PR

**Comment by whowutwut** [comment]
Testcase is added to cover issue #2699

**Comment by whowutwut** [comment]
@tingtli The issue number in the title of the pull request does not create a link in GitHub.

**Comment by whowutwut** [comment]
@zet809 See this hassle of linking this pull request to testcase issue as well as real issue.... voicing my opinion that I don't like this.

**Pull request merged**
