### PR TITLE
modify bmc testcase

### PR DESCRIPTION
**Pull request by junxiawang**
ting ting please help merge

### CODE REVIEW

**Comment by whowutwut** [comment]
@junxiawang do we also have testcase a for the error condition when we do not pass in the correct options to bm discover? Like the user/password.

Looks like we are also not verifying the -w is writing to the xcatdb. check before -w then after to make sure an entry is added? What about testing the error handling for bmcdiscover? Or testing the --check option?

**Comment by whowutwut** [comment]
Also need to fill in the milestone and label for this pull request

**Comment by junxiawang** [comment]
@whowutwut  I will modify the bmc cases but not in this pull request .This pull request is just for some cases's output changed according to bmc code change.

**Comment by tingtli** [comment]
@junxiawang  I will merge your change to remove the error everyday. Please update the cases according to Victor's comments.

**Pull request merged**
