### PR TITLE
Use lowercase file name xcat-core.repo instead of xCAT-core.repo

### PR DESCRIPTION
**Pull request by neo954**
This pull request is for issue #4918

### CODE REVIEW

**Comment by robin2008** [comment]
@neo954 
I have below comments:
- where to handle the repo file for xcat-dep ?
- For `go-xcat`, we need to disable `xCAT-*.repo` if it found those old repo file, for example, rename it to `xCAT-*.repo.disable`
- In `mklocalrepo.sh`, it is required to do the same thing.

BTW:  Better for you  to have an self-build core and dep tarball, and use it for UT on below senario
1, fresh installaion
2, upgrade

**Comment by neo954** [comment]
@robin2008,

The patch for `go-xcat` is in pull request #4991.

**Comment by whowutwut** [comment]
@neo954 I think we also need to modify in our GSA directory for the xcat-dep package builds, because I believe those scripts are creating xCAT-dep.repo files...   Not sure if anyone changed those..  and re-spin a development version of the xcat-dep package.

**Comment by neo954** [comment]
The xcat-dep GSA directory was updated manually.
  * All file named `xCAT-dep.repo` were renamed to `xcat-dep.repo`
  * File `mklocalrepo.sh` was tweaked to rename `xCAT-dep.repo` if it exists.

**Comment by robin2008** [comment]
remember to modify xcat.org accordingly.

**Pull request merged**
