### PR TITLE
refine cases for bug 2659

### PR DESCRIPTION
**Pull request by tingtli**
Refine 2 cases in this pull request
This pull request is for task #3183 

[case 1]
Case Name: reg_linux_diskless_installation_flat

[case 2]
Case Name: reg_linux_diskless_installation_hierarchy

@bybai  Please help review. Thanks!

### CODE REVIEW

**Comment by bybai** [comment]
Hi @tingtli 
Please check:
1, this pull request contains more diff than that for #2659, please double check. 
2, Since #2659 is not finished, and the solution is not provided for this release, I think this can be merged with fixed #2659

**Comment by whowutwut** [comment]
Close/Reopen to trigger CI test

**Comment by robin2008** [comment]
This PR cannot reflect the test requirement of #2659,  it is required to check if the customized option is there.

**Comment by zet809** [comment]
Shall we close this PR and apply new one if needed?

**Comment by hu-weihua** [comment]
This pull request is linked to new task xcat2/xcat2-task-management#69.

**Comment by hu-weihua** [comment]
@tingtli , could you follow this PR again? thanks.

**Comment by hu-weihua** [comment]
@tingtli , It seems the requirement of this task was outdated. I have canceled the task xcat2/xcat2-task-management#69. Could you close this pull request? thanks

**Comment by tingtli** [comment]
This is not required now. Close this one.

**Pull request closed without merging**
