### PR TITLE
Tinker for the openssl -no_ssl2 command line argument

### PR DESCRIPTION
**Pull request by neo954**
Fix github issue #5365

### CODE REVIEW

**Comment by bybai** [comment]
agree to merge it.
Verified in sles11.4: 
echo "<xcatrequest>\n<command>litefile</command>\n</xcatrequest>" | LD_LIBRARY_PATH=/sysroot/lib64:/sysroot/usr/lib64 /sysroot/usr/bin/openssl s_client -quiet -no_ssl3 $(LD_LIBRARY_PATH=$/sysroot/lib64:/sysroot/usr/lib64 /sysroot/usr/bin/openssl s_client -help 2>&1 | grep -m 1 -o -- -no_ssl2) -connect 10.2.8.5:3001 -rand /bin/nice

**Comment by chuckbrazie** [comment]
I am out of the office until 07/16/2018.

I am out of the office until  Monday July 16.


Note: This is an automated response to your message  "[xcat2/xcat-core]
Tinker for the openssl -no_ssl2 command line argument (#5383)" sent on
7/9/18 8:59:16 AM.

This is the only notification you will receive while this person is away.

**Comment by chuckbrazie** [comment]
I am out of the office until 07/16/2018.

I am out of the office until  Monday July 16.


Note: This is an automated response to your message  "Re: [xcat2/xcat-core]
Tinker for the openssl -no_ssl2 command line argument (#5383)" sent on
7/9/18 9:02:10 AM.

This is the only notification you will receive while this person is away.

**Comment by chuckbrazie** [comment]
I am out of the office until 07/16/2018.

I am out of the office until  Monday July 16.


Note: This is an automated response to your message  "Re: [xcat2/xcat-core]
Tinker for the openssl -no_ssl2 command line argument (#5383)" sent on
7/9/18 9:11:16 AM.

This is the only notification you will receive while this person is away.

**Comment by chuckbrazie** [comment]
I am out of the office until 07/16/2018.

I am out of the office until  Monday July 16.


Note: This is an automated response to your message  "Re: [xcat2/xcat-core]
Tinker for the openssl -no_ssl2 command line argument (#5383)" sent on
7/9/18 9:11:31 AM.

This is the only notification you will receive while this person is away.

**Pull request merged**
