### PR TITLE
[OpenBMC] Improve the output message for reventlog to indicate missing PolicyTable file

### PR DESCRIPTION
**Pull request by whowutwut**
When running the command: 

```
[root@briggs01 ~]# reventlog mid05tor12cn13 10
mid05tor12cn13: 12/05/2017 20:55:15 [33]: xyz.openbmc_project.Common.Error.InternalFailure (PID: 1147), Resolved: 0
mid05tor12cn13: 12/06/2017 11:39:43 [34]: xyz.openbmc_project.Software.Version.Error.ManifestFileFailure (PID: 1292), Resolved: 0
mid05tor12cn13: 12/06/2017 11:46:57 [35]: org.open_power.Host.Boot.Error.Checkstop (PID: 2316), Resolved: 0
mid05tor12cn13: 12/06/2017 11:58:08 [36]: xyz.openbmc_project.Software.Version.Error.ManifestFileFailure (PID: 1387), Resolved: 0
mid05tor12cn13: 12/06/2017 12:05:06 [37]: org.open_power.Host.Boot.Error.Checkstop (PID: 4414), Resolved: 0
mid05tor12cn13: 12/06/2017 20:36:11 [38]: xyz.openbmc_project.Software.Version.Error.ManifestFileFailure (PID: 1387), Resolved: 0
mid05tor12cn13: 12/13/2017 02:59:20 [39]: xyz.openbmc_project.Software.Version.Error.ManifestFileFailure (PID: 1301), Resolved: 0
mid05tor12cn13: 12/13/2017 03:32:28 [40]: xyz.openbmc_project.Software.Version.Error.ManifestFileFailure (PID: 1392), Resolved: 0
mid05tor12cn13: 12/13/2017 04:39:45 [41]: xyz.openbmc_project.Software.Version.Error.ManifestFileFailure (PID: 1343), Resolved: 0
mid05tor12cn13: 12/13/2017 04:46:09 [42]: xyz.openbmc_project.Software.Version.Error.ManifestFileFailure (PID: 1369), Resolved: 0
Could not found '/opt/ibm/ras/lib/policyTable.json', all event messages above are original
```

I didn't think that message at the end was useful for the user....  but since the `ibm-crassd` RPM packaging may change, changing the message to the following with this Pull Request: 

```
[root@briggs01 xCAT_plugin]# reventlog mid05tor12cn13 10
mid05tor12cn13: 12/05/2017 20:55:15 [33]: xyz.openbmc_project.Common.Error.InternalFailure (PID: 1147), Resolved: 0
mid05tor12cn13: 12/06/2017 11:39:43 [34]: xyz.openbmc_project.Software.Version.Error.ManifestFileFailure (PID: 1292), Resolved: 0
mid05tor12cn13: 12/06/2017 11:46:57 [35]: org.open_power.Host.Boot.Error.Checkstop (PID: 2316), Resolved: 0
mid05tor12cn13: 12/06/2017 11:58:08 [36]: xyz.openbmc_project.Software.Version.Error.ManifestFileFailure (PID: 1387), Resolved: 0
mid05tor12cn13: 12/06/2017 12:05:06 [37]: org.open_power.Host.Boot.Error.Checkstop (PID: 4414), Resolved: 0
mid05tor12cn13: 12/06/2017 20:36:11 [38]: xyz.openbmc_project.Software.Version.Error.ManifestFileFailure (PID: 1387), Resolved: 0
mid05tor12cn13: 12/13/2017 02:59:20 [39]: xyz.openbmc_project.Software.Version.Error.ManifestFileFailure (PID: 1301), Resolved: 0
mid05tor12cn13: 12/13/2017 03:32:28 [40]: xyz.openbmc_project.Software.Version.Error.ManifestFileFailure (PID: 1392), Resolved: 0
mid05tor12cn13: 12/13/2017 04:39:45 [41]: xyz.openbmc_project.Software.Version.Error.ManifestFileFailure (PID: 1343), Resolved: 0
mid05tor12cn13: 12/13/2017 04:46:09 [42]: xyz.openbmc_project.Software.Version.Error.ManifestFileFailure (PID: 1369), Resolved: 0
Could not find '/opt/ibm/ras/lib/policyTable.json', install the OpenBMC RAS package to obtain more details logging messages.
```

### CODE REVIEW

**Comment by whowutwut** [comment]
@gurevichmark Not sure if that should be a `WARN` message .. or just an info like it is above...

**Comment by whowutwut** [comment]
Also going to fix this error message with this PR:
```
[root@fs2vm112 ~]# XCATBYPASS=1 rspconfig f6u17 hostname
Use of uninitialized value $debug_msg in concatenation (.) or string at /opt/xcat/lib/perl/xCAT_plugin/openbmc.pm line 2068.
Wed Dec 13 13:13:44 2017 OpenBMC: [openbmc_debug]
Use of uninitialized value $debug_msg in concatenation (.) or string at /opt/xcat/lib/perl/xCAT_plugin/openbmc.pm line 2069.
Wed Dec 13 13:13:57 2017 f6u17: [openbmc_debug] curl -k -c cjar -H "Content-Type: application/json" -d '{ "data": ["root", "xxxxxx"] }' https://10.6.17.100/login
Wed Dec 13 13:13:57 2017 f6u17: [openbmc_debug] login_response 200 OK
Wed Dec 13 13:13:57 2017 f6u17: [openbmc_debug] curl -k -b cjar -X GET -H "Content-Type: application/json" https://10.6.17.100/xyz/openbmc_project/network/enumerate
Wed Dec 13 13:13:58 2017 f6u17: [openbmc_debug] rspconfig_get_response 200 OK
f6u17: BMC hostname:
```

`Use of uninitialized value` message...

**Comment by whowutwut** [comment]
@gurevichmark please merge if you have a chance

**Comment by zet809** [comment]
hi, @xuweibj , will you pls help to review this PR and merge if no more comments? Thx!

**Comment by xuweibj** [comment]
Looks good to me. Will merge.

**Pull request merged**
