### PR TITLE
Update documentation to have the changes in master branch to 2.11

### PR DESCRIPTION
**Pull request by whowutwut**
Doing a mass update of the changes in the master branch documentation to the 2.11 branch.  
This is really to help sync up the docs before the GA.  

Once we GA, we will need to enforce that the pull request be created for both the master branch and the 2.11 branch (if we think it should be pulled into 2.11) 

Here's what I did....

*  Update the repositories for master and 2.11 in my forked copy
```
git fetch upstream
git checkout master
git merge upstream/master
git checkout 2.11
git merge upstream/2.11
git push origin 2.11 master
```

*  Stash any changes that I am working on to not get pulled in by accident, ```git status`` returns a clean working environment

*  Tar up the ``docs/source`` directory from master and copy over to 2.11 

```
git checkout master
cd docs
tar -czvf master_source.tar.gz ./source
git checkout 2.11
git branch update_doc_to_2.11
git checkout update_doc_to_2.11
tar -xzvf master_source.tar.gz 
```

* Now check the changes and only update the files that should be updated in 2.11...  

* Run the ``create_man_pages.py`` script to make sure any pods changed make it to the man pages

* Push the changes to my forked copy and create a pull request against the 2.11 branch

### CODE REVIEW

**Comment by whowutwut** [comment]
@daniceexi  should we merge this or wait until the end of the week ? I  think if we pull in any other documentation pull requests, we should just ask the originator to cherry pick the changes and create a pull request off of the 2.11 branch?

**Comment by daniceexi** [comment]
@whowutwut Yes, to avoid the missing check in for the earlier branch, people should make the corresponding pull request for earlier branch as soon as the pull request for master is merged.
So I agree that we can merge the pull request for 2.11 any time instead of waiting for the close of GA.

BTW, for your steps to merge the commits from master to 2.11, does the master_source.tar.gz include the changed files and commit information? how the commit be98fa3 in this pull request was created?

**Comment by whowutwut** [comment]
No it does not have the commit info from the original. If we want to do that then we should cherry pick the individual commits... Should we do that?  The few commits is just me separating some of the files into different commits

**Comment by daniceexi** [comment]
@whowutwut it's good enough. I merge it now.

**Pull request merged**
