### PR TITLE
Catch BMC status error from get status request

### PR DESCRIPTION
**Pull request by gurevichmark**
#4855 
Catch client exception from get state request and display error message as part of `rpower bmcstate` 

UT:
```
[root@boston02 xcat]# rpower mid08tor03cn01 bmcreboot
mid08tor03cn01: BMC reboot

[root@boston02 xcat]# while true; do  sleep 5; date; rpower mid08tor03cn01 bmcstate ; done
Wed Mar 21 14:51:19 EDT 2018
mid08tor03cn01: Error: Login to BMC failed: Can't connect to 172.21.226.1 (Connection reset by peer).
Wed Mar 21 14:51:26 EDT 2018
mid08tor03cn01: Error: Login to BMC failed: Can't connect to 172.21.226.1 (Connection reset by peer).
Wed Mar 21 14:51:32 EDT 2018
mid08tor03cn01: Error: Login to BMC failed: Can't connect to 172.21.226.1:443 (timeout).
Wed Mar 21 14:51:57 EDT 2018
mid08tor03cn01: Error: Login to BMC failed: Can't connect to 172.21.226.1 (Connection reset by peer).
Wed Mar 21 14:52:22 EDT 2018
mid08tor03cn01: Error: Login to BMC failed: Can't connect to 172.21.226.1 (Connection reset by peer).
Wed Mar 21 14:52:28 EDT 2018
mid08tor03cn01: Error: Login to BMC failed: Can't connect to 172.21.226.1 (Connection reset by peer).
Wed Mar 21 14:52:37 EDT 2018
mid08tor03cn01: Error: Login to BMC failed: Can't connect to 172.21.226.1 (Connection reset by peer).
Wed Mar 21 14:52:43 EDT 2018
mid08tor03cn01: Error: Login to BMC failed: Can't connect to 172.21.226.1:443 (timeout).
Wed Mar 21 14:53:09 EDT 2018
mid08tor03cn01: Error: Login to BMC failed: Can't connect to 172.21.226.1:443 (timeout).
Wed Mar 21 14:53:35 EDT 2018
mid08tor03cn01: BMC NotReady ([404] org.freedesktop.DBus.Error.FileNotFound: path or object not found: /xyz/openbmc_project/state/bmc0)
Wed Mar 21 14:53:56 EDT 2018
mid08tor03cn01: BMC NotReady ([404] org.freedesktop.DBus.Error.FileNotFound: path or object not found: /xyz/openbmc_project/state/bmc0)
Wed Mar 21 14:54:02 EDT 2018
mid08tor03cn01: BMC NotReady ([404] org.freedesktop.DBus.Error.FileNotFound: path or object not found: /xyz/openbmc_project/state/bmc0)
Wed Mar 21 14:54:08 EDT 2018
mid08tor03cn01: BMC NotReady
Wed Mar 21 14:54:15 EDT 2018
mid08tor03cn01: BMC NotReady
Wed Mar 21 14:54:24 EDT 2018
mid08tor03cn01: BMC NotReady
Wed Mar 21 14:54:32 EDT 2018
mid08tor03cn01: BMC NotReady
Wed Mar 21 14:54:38 EDT 2018
mid08tor03cn01: BMC Ready
```

### CODE REVIEW

**Comment by whowutwut** [comment]
@gurevichmark This looks great! Thank you

**Comment by xuweibj** [comment]
Hi @gurevichmark , I think we could make it easy for "get_bmcstate" error.

1. for login: add "except SelfClientException" to deal with error like "401". ---- Currently, will exit with exception.
2. for get_bmc_state part: 
    modify "except SelfServerException, SelfClientException:" to 
    ```
    except SelfServerException as e:
        xxxxxx
    except SelfClientException as e:
        if e.code == 404:
            xxxx
       else:
            xxxx
    ```
    If so, we do not need to modify file "xCAT-openbmc-py/lib/python/agent/hwctl/openbmc_client.py"

**Comment by gurevichmark** [comment]
@xuweibj But I think we should still add a `except SelfClientException` to openbmc_client.py:request().
This is because handle_response() was raising SelfClientException, but request() was calling `return self.handle_response(response, cmd=cmd)` but never catching the `SelfClientException`

**Comment by xuweibj** [comment]
Hi @gurevichmark , if there is one error raise, the code will return until a function try to catch it or just exit. So we do not need to catch it every function. You could have a try to just catch it in get_bmcstate, it's ok.

**Comment by gurevichmark** [comment]
@xuweibj Yes you are right. This make the code even simpler.

**Comment by xuweibj** [comment]
Looks good to me. Agree to merge. Thanks @gurevichmark .

**Pull request merged**
