### PR TITLE
Need to get latest xcat2 updates to zvm git

### PR DESCRIPTION
**Pull request by zVMopenstack**

### CODE REVIEW

**Comment by zVMopenstack** [comment]
Just working to get latest xcat master from xcat2

**Comment by zVMopenstack** [comment]
getting latest

**Comment by whowutwut** [comment]
I'm not entirely sure why this pull request is required?  Are you trying to update the zVMopenstack:master branch with what is in the xcat2:master branch? 

In that case, in your forked repo, you can configure and upstream that points to xcat2:xcat-core, then fetch upstream, then merge upstream/master to your master branch.  Then push the chagnes to your zVMopenstack/xcat-core master branch...  

@daniceexi  any comments?

**Comment by whowutwut** [comment]
No response, closing for now.  Feel free to re-open if needed.

**Pull request closed without merging**
