### PR TITLE
Change bmcdiscover to look at system information instead of motherboard info for OpenBMC

### LINKED ISSUE #3205: [openbmc] bmcdiscover does not return the correct MTM and Serial for OpenBMC systems
This issue is opened to close out any remaining work for verification with the `bmcdiscover` command for OpenPower OpenBMC support. 

API: [Inventory](https://github.com/openbmc/phosphor-dbus-interfaces/tree/master/xyz/openbmc_project/Inventory)
Endpoint: `inventory/system`
Model Type Value: `{PartNumber}`
Serial Number Value:  `{SerialNumber}`

Examples:

### PR DESCRIPTION
**Pull request by whowutwut**
Resolves #3205 

Change bmcdiscover to look at system information instead of motherboard info for OpenBMC.
And use variables for building up then endpoint for OpenBMC

Sample Output: 
```
[root@fs2vm104 ~]#  bmcdiscover --range 10.6.9.254 -z
node-2-0000000000000000:
	objtype=node
	groups=all
	bmc=10.6.9.254
	cons=openbmc
	mgt=openbmc
	mtm=2
	serial=0000000000000000
```

Here's a sample of the output that is returned from OpenBMC at this time.
```
    "/xyz/openbmc_project/inventory/system": {
      "BuildDate": "",
      "Cached": 0,
      "FieldReplaceable": 0,
      "Manufacturer": "",
      "Model": "2",
      "PartNumber": "0000000000000000",
      "Present": 1,
      "PrettyName": "",
      "SerialNumber": "0000000000000000"
    },
    "/xyz/openbmc_project/inventory/system/chassis/motherboard": {
      "BuildDate": "",
      "Manufacturer": "0000000000000000",
      "Model": "",
      "PartNumber": "00VK525         ",
      "Present": 0,
      "PrettyName": "SYSTEM PLANAR   ",
      "SerialNumber": "Y130UF72701M    "
    },
```

### CODE REVIEW

**Comment by zet809** [comment]
Hi, @whowutwut , the data "Model: 2" doesn't seems to be the Machine Type/Mode for a server with OpenBMC. I think it shall be "PartNumber" instead.

Here is how we get MTMS from the host OS.
```
[root@p9euh01 ~]# cat /proc/device-tree/model
0000000000000000
[root@p9euh01 ~]# cat /proc/device-tree/system-id
0000000000000000
[root@p9euh01 ~]#
```

**Comment by whowutwut** [comment]
@zet809 Thank you! Yes, I was not sure if Model was the right value, so put this as [DO NOT MERGE] but from your info... looks like the corresponding pieces we should look for is `PartNumber` and `SerialNumber`.   Going to make changes for that... 

```
    "/xyz/openbmc_project/inventory/system": {
      "BuildDate": "",
      "Cached": 0,
      "FieldReplaceable": 0,
      "Manufacturer": "",
      "Model": "2",
      "PartNumber": "0000000000000000",
      "Present": 1,
      "PrettyName": "",
      "SerialNumber": "0000000000000000"
    },
```

**Comment by whowutwut** [comment]
With the latest changes, the output looks like the following:

```
[root@fs2vm104 ~]#  bmcdiscover --range 10.6.7.254 -z
node-0000000000000000-0000000000000000:
        objtype=node
        groups=all
        bmc=10.6.7.254
        cons=openbmc
        mgt=openbmc
        mtm=0000000000000000
        serial=0000000000000000
```

**Comment by whowutwut** [comment]
I'm ok for this to go in for now  and we can validate as we get more systems that have this set...

**Comment by zet809** [comment]
hi, @whowutwut , the pull request looks good to me, since both @xuweibj and I approved it, I will merge the code. Thx!

**Pull request merged**
