### PR TITLE
Story50687 xCAT customize rsyslog configuration files and logrotate configuration file

### PR DESCRIPTION
**Pull request by neo954**
Hello All,

This is for the story 50687.

GONG Jie

### CODE REVIEW

**Comment by samveen** [comment]
@neo954 Merging upstream:master into your work is probably not a good idea. See @whowutwut 's last comment on #133

**Comment by neo954** [comment]
@samveen Good point. I rollback the commit for merge. :D

**Comment by immarvin** [comment]
hi, the code looks good.

**Comment by whowutwut** [comment]
@neo954 , is it possible to add some description to this task to describe the changes that went in for this.  I was looking for some information about the changes made to logging and there's nothing provided here nor is there anything in the RTC Story.  We should not just write "Story xxxxx" because the community cannot access that tool. .

**Pull request merged**
