### PR TITLE
Get correct WWN and PATH values in getinstdisk

### PR DESCRIPTION
**Pull request by xuweibj**
When get the WWN and PATH values from disk_info, there is a bug in the code. Fix it to get correct information.

### CODE REVIEW

**Comment by whowutwut** [comment]
I will review this

**Comment by daniceexi** [comment]
@whowutwut @zet809 has reviewed the change, it should be safe for merge.

**Comment by zet809** [comment]
@whowutwut The fix looks good to me.

**Comment by whowutwut** [comment]
@xuweibj  please set the milestone and lables when creating Pull requests.

**Comment by whowutwut** [comment]
I wanted to review the code a bit more closely.  

* line 21, please use the -f option for rm to avoid this error message: `rm: cannot remove '/tmp/install_disk': No such file or directory`
* Why do we remove tmpdir at the end:  `rm -rf $tmpdir`  ?  If we are debugging in xcatdebugmode, this directory is gone.  Do we need to look in that directory to get some output? 
* Why is /tmp/install_disk used as the name of the file?  Suggest that we be consistent and since tmpdir is `/tmp/xcat.getinstalldisk` , we should put the results in `/tmp/xcat.install_disk` to indicate it's xCAT file. 
* In the mount code,

1) We are getting an error mounting sda1, 
```
    117 + mount /dev/sda1 /tmp/xcat.getinstalldisk/xcat.getinstalldisk.mount
    118 mount: /dev/sda1 is write-protected, mounting read-only
    119 mount: wrong fs type, bad option, bad superblock on /dev/sda1,
    120        missing codepage or helper program, or other error
    121 
    122        In some cases useful info is found in syslog - try
    123        dmesg | tail or so.
```
Is that /boot? 
2) There's never a `umount` command to unmount the mounted directory in the loop
3) The `rmdir $mount_dir` fails because the directory is not empty, probably due to the above issue about not unmounting.  

* Can you add a block comment to explain how we are using the WWN information to select the disk? The lack of comment makes it very difficult to understand what the code is doing unless I trace through it. 

Here's  a sample output,  what are we using to detect the order?
```
[get_install_disk]The disk sdb information: 
[get_install_disk]    disk_wwn=0xbdb38c59c5005000
[get_install_disk]    disk_path=/devices/pci0005:00/0005:00:00.0/0005:01:00.0/0005:02:02.0/0005:04:00.0/ata2/host1/target1:0:0/1:0:0:0/block/sdb
[get_install_disk]    disk_driver=ahci
[get_install_disk]    Add disk: sdb 0xbdb38c59c5005000 into wwn firstchoicedisks
[get_install_disk]The disk sda information: 
[get_install_disk]    disk_wwn=0xbe878c5cc5005000
[get_install_disk]    disk_path=/devices/pci0005:00/0005:00:00.0/0005:01:00.0/0005:02:02.0/0005:04:00.0/ata1/host0/target0:0:0/0:0:0:0/block/sda
[get_install_disk]    disk_driver=ahci
[get_install_disk]    Add disk: sda 0xbe878c5cc5005000 into wwn firstchoicedisks
[get_install_disk]The install_disk is /dev/sdb by sorting wwn and DRIVER.
```

Do you know why in the pre-install.log, it seems to be running with `set -x` ?

**Comment by whowutwut** [comment]
@xuweibj  on the test machine fs1,  I think you have a copy of getinstdisk in /tmp....  I copied it over to `/opt/xcat/share/xcat/install/scripts/getinstdisk`
```
[root@fs1 opt]# diff /opt/xcat/share/xcat/install/scripts/getinstdisk /opt/xcat/share/xcat/install/scripts/getinstdisk.orig
25c25
< has_awk=$(find /usr/* -name "awk")
---
> has_awk=$(find / -name "awk")
134,137c134,137
<         output_for_wwn=$(IFS= ;echo $disk_info | grep '\<ID_WWN\>' | cut -d "=" -f2)
<         disk_wwn=$(echo $output_for_wwn | $utolcmd)
<         output_for_path=$(IFS= ;echo $disk_info | grep DEVPATH | cut -d "=" -f2)
<         disk_path=$(echo $output_for_path | $utolcmd)
---
>         output_for_wwn=$(echo $disk_info | grep '\<ID_WWN\>' | cut -d "=" -f2 | $utolcmd)
>         disk_wwn=$(IFS= ;echo $output_for_wwn)
>         output_for_path=$(echo $disk_info | grep DEVPATH | cut -d "=" -f2 | $utolcmd)
>         disk_path=$(IFS= ;echo $output_for_path)
```
And reprovisioned the compute node, still it picks up sdb and the install stalls. 
```
[anaconda root@c910f05c31 ~]# cat /tmp/install_disk 
/dev/sdb
```

I don't think we can merge this right now.

**Comment by xuweibj** [comment]
@whowutwut 
/dev/sdb is correct result. It's WWN value is smaller than /dev/sda. So choose /dev/sdb.

**Comment by xuweibj** [comment]
@whowutwut 
All the files in tmpdir are temporary, they are used for the code to collect information and then to process. So we don't need to save them and don't need to look in. We hope we can get information from log.
/tmp/install_disk is the final result for other code to get information. It is the output of this script, we can not put it under /tmp/xcat.getinstalldisk.

1) It is the system error, some partition can not be mounted, I think we don't need to do anything about it.
2) We will umount when mounted successfully.
3) I think maybe umount failed.

[get_install_disk]The disk sdb information: 
[get_install_disk]    disk_wwn=0xbdb38c59c5005000
[get_install_disk]    disk_path=/devices/pci0005:00/0005:00:00.0/0005:01:00.0/0005:02:02.0/0005:04:00.0/ata2/host1/target1:0:0/1:0:0:0/block/sdb
[get_install_disk]    disk_driver=ahci
[get_install_disk]    Add disk: sdb 0xbdb38c59c5005000 into wwn firstchoicedisks
[get_install_disk]The disk sda information: 
[get_install_disk]    disk_wwn=0xbe878c5cc5005000
[get_install_disk]    disk_path=/devices/pci0005:00/0005:00:00.0/0005:01:00.0/0005:02:02.0/0005:04:00.0/ata1/host0/target0:0:0/0:0:0:0/block/sda
[get_install_disk]    disk_driver=ahci
[get_install_disk]    Add disk: sda 0xbe878c5cc5005000 into wwn firstchoicedisks
[get_install_disk]The install_disk is /dev/sdb by sorting wwn and DRIVER.

From above information, the drivers are the same so compare their WWN.
/dev/sdb WWN value is smaller, so choose it.

**Comment by zet809** [comment]
@whowutwut Hi, victor, the fix @xuweibj made is to correct the disk chosen with WWN.
But for the issue that the issue that "storage configuration failed: failed to find a suitable...", it is fixed within defect #948

**Comment by whowutwut** [comment]
@xuweibj 

Thanks, I see the umount line now, I missed it before. 

Putting the results in `/tmp/xcat.install_disk` is not a directory, it's a file.  If we do this type of label, then the user who logs into anaconda will immediately know that the file is created by xCAT.  We can still delete the working directory. 

Regarding the error I see in get_install_disk, 
```
+ echo '[get_install_disk]    Partition sda3 mount failed or the partition is swap.'
[get_install_disk]    Partition sda3 mount failed or the partition is swap.
+ '[' '' ']'
+ rmdir /tmp/xcat.getinstalldisk/xcat.getinstalldisk.mount
+ rm
rm: missing operand
Try 'rm --help' for more information.
+ has_wwn=0
+ has_path=0
+ file_pre=
+ disk_data=
```

The rm call is not correct, so we need to fix that. 

I don't think /dev/sdb is the correct disk to use.  The RH install fails at this step: 
```
================================================================================
================================================================================
Installation

 1) [x] Language settings                 2) [x] Timezone settings
        (English (United States))                (America/New_York timezone)
 3) [x] Installation source               4) [!] Software selection
        (http://192.168.3.29:80/install          (Minimal Install)
        /rhels7.2/ppc64le)                6) [x] Kdump
 5) [!] Installation Destination                 (Kdump is enabled)
        (Error checking storage configu   8) [ ] User creation
        ration)                                  (No user will be created)
 7) [x] Network configuration
        (Wired (enP5p7s0f0) connected)
  Please make your choice from above ['q' to quit | 'b' to begin installation |
  'r' to refresh]: 
```

Looking at petitboot, it looks like this when I'm running the OS install
```
 Petitboot (dev.20160208)                     8335-GTB         100469A
 ──────────────────────────────────────────────────────────────────────────────
 Petitboot (dev.20160208)                     8335-GTB         100469A
 ──────────────────────────────────────────────────────────────────────────────
  [Disk: sda2 / c4ea56b7-fbfe-4837-810a-057215fd5f18]
  Ubuntu, with Linux 3.19.0-25-generic (recovery mode)
    Ubuntu, with Linux 3.19.0-25-generic
    Ubuntu
  [Network: enP2p7s0f0 / 70:e2:84:14:0a:29]
    xCAT

  System information
  System configuration
  Language
  Rescan devices
 *Retrieve config from URL                              
  Exit to shell






 ──────────────────────────────────────────────────────────────────────────────
 Enter=accept, e=edit, n=new, x=exit, l=language, h=help
```

So /dev/sda has Ubuntu on it, I want to replace the OS with RHEL, not install RHEL over onto the 2nd disk /dev/sdb....   so I think something is wrong with this logic here.

I don't want to force the install into /dev/sda in the installer menu because we may not be able to recreate this scenario.  I'd rather have the fix be done by the getinstdisk` to select the correct disk....

**Comment by whowutwut** [comment]
@zet809  I just saw your comment, thanks.  I was not running with your code change, I added to my environment and will re-run this provisioning.. will report the results.

**Comment by whowutwut** [comment]
@zet809  @xuweibj  Things now look good with changes from #948   and it's installing on /dev/sda. Thank you! 

I will merge this in.... so the fix is available for the GA build.

**Pull request merged**
