### PR TITLE
Add quickstart documentation for goconserver 

### PR DESCRIPTION
**Pull request by whowutwut**
Create a quick start documentation for goconserver for 2.13.11

### CODE REVIEW

**Comment by whowutwut** [comment]
I may add in some more information about TCP configuration here, but need to test that first and will push more commits if that is ready.

**Comment by zet809** [comment]
Hi, @neo954 , as you have verified the `TCP configuration` function about goconserver, will you pls help to update this Pull Request? Thx  a lot!

**Comment by chenglch** [comment]
@whowutwut , as some conflict exists , I have opened a new one https://github.com/xcat2/xcat-core/pull/4896 with your quick start doc inside.

**Comment by zet809** [comment]
So, @whowutwut , shall we close this PR if #4896 cover this PR.

**Pull request closed without merging**
