### PR TITLE
Add test cases for Using Regular Expressions in the xCAT Tables

### PR DESCRIPTION
**Pull request by neo954**
Add 3 cases in this pull request
This pull request is for task #2619

[case 1]
Case Name: mkdef_regex_bmc
description: Test of using regular expressions in xCAT table ipmi.

[case 2]
Case Name: mkdef_regex_ip
description: Test of using regular expressions in xCAT table hosts.

[case 3]
Case Name: mkdef_regex_kvm
description: Test of using regular expressions in xCAT table vm.

### CODE REVIEW

**Comment by neo954** [comment]
Please notice, the third test case, `mkdef_regex_kvm` will fail at time. This is due to a bug of xCAT. A new issue #3006 was opened to trace this bug.

**Comment by neo954** [comment]
@immarvin, please help on review this patch.

**Comment by immarvin** [comment]
i am ok with the change

**Comment by hu-weihua** [comment]
@neo954, Could you do the **carefully UT** before pulling the request.  Two mistakes have been found ( #3454 and #3718) for test case ``mkdef_regex_kvm``.

**Pull request merged**
