### PR TITLE
fix defect [FVT]xCAT in docker :genimage failed #663

### PR DESCRIPTION
**Pull request by immarvin**
fix defect [FVT]xCAT in docker :genimage failed #663:
(1). mount /proc /sys read-only to eliminate errors during package installation in the chrooted directory
(2). fake invoke.rc.d to eliminate errors during package installation in the chrooted directory

### CODE REVIEW

**Comment by immarvin** [comment]
hi @daniceexi @whowutwut ,any comments?

**Comment by immarvin** [comment]
``Is there same issues for rh and sles?``
I am not sure, we did not build xcat docker images from a redhat/sles base image yet.

``Do we need to handle the /dev here too?``
The genimage on ubuntu works without devfs mounted, it is also ok with devfs mounted readonly, do we need to add devfs in chroot_mount?

**Comment by daniceexi** [comment]
@immarvin I meant we need to do the similar thing for rh and sles. At least for rh, we did see the issue caused by the missing of /proc, but I cannot remember why the code for mounting was removed.

And please do the mount for /dev too.

**Comment by immarvin** [comment]
mounted devfs under rootimg during genimage, code updated @daniceexi

**Comment by daniceexi** [comment]
I have reviewed the change and agree to merge.

**Pull request merged**
