### PR TITLE
Re-format the mixed cluster support page to improve clarity. 

### PR DESCRIPTION
**Pull request by whowutwut**
Hopefully this makes is a bit more clear about mixed cluster support

Also update the stateless image creation file to include
the NOTE for using a local file.  I hit problems with genimage
when it's writing to the mounted NFS /install directory

### CODE REVIEW

**Comment by daniceexi** [comment]
@whowutwut 
China team members always create a local web server for doc change review.  For example, my local web server is: http://10.4.14.20/. In the root path, you can see there are several version of doc for review.

Even thsi local web server cannot be access from outside of IBM, but it's very helpful for our internal review.

**Comment by whowutwut** [comment]
@daniceexi 

Yea, I see that.  I have been expanding the ``command line instructions`` from the Merge instructions above and running step 1 from my own forked git repo.. This allows me to

- make changes to the suggested changes to test out formatting or suggestions
- allow me to see if there are any build related errors in the log by building myself
- I can view the changes locally on my dev machine

But I do understand the convenience of having a server up and running. 
I put the build output here: http://10.2.5.2/mixed_cluster_improv/advanced/mixed_cluster/index.html

**Comment by daniceexi** [comment]
@whowutwut  

I agree with you that download the change to dev machine could do more compicated work especially the reviewer thinks the structure of the doc has problem.

A local web server can make the review process quicker if there's no major comments. The reviewer can choose the way to execute the review. :)

**Comment by daniceexi** [comment]
The change looks good for me. I agree to check in.

**Pull request merged**
