### PR TITLE
fix issue xcat is failing to run postbootscripts on stateful node. #2167

### PR DESCRIPTION
**Pull request by immarvin**
fix issue https://github.com/xcat2/xcat-core/issues/2167#issuecomment-261417563

### CODE REVIEW

**Comment by neo954** [comment]
The patch looks good. I will merge this one.

**Comment by ralphbellofatto** [comment]
When will this fix be made available to those looking for software here?
```
baseurl=http://xcat.org/files/xcat/repos/yum/devel/core-snap
```

**Comment by immarvin** [comment]
hi @ralphbellofatto , the fix has been available , please try the repo you attached

**Comment by ralphbellofatto** [comment]
```
[root@c460mgt01 postscripts]# yum update '*xCAT*'
Loaded plugins: product-id, search-disabled-repos, subscription-manager
This system is not registered to Red Hat Subscription Management. You can use subscription-manager to register.
No packages marked for update
```

Am I missing something here?

**Comment by immarvin** [comment]
please try http://xcat-docs.readthedocs.io/en/stable/guides/install-guides/yum/update_xcat.html
````
yum clean metadata # or, yum clean all
yum update '*xCAT*'
````

**Comment by ralphbellofatto** [comment]
ok, got the change and inspecting it before testing:

I'm observing:
```
[root@c460mgt01 postscripts]# grep RUNBOOTSCRIPTS xcatpostinit1.install
  if [ "$REBOOT" = "TRUE" -a -r /opt/xcat/xcatdsklspost ] && [[ "$RUNBOOTSCRIPTS" =~ ^1|yes|y$ ]]; 

[root@c460mgt01 postscripts]# grep RUNBOOTSCRIPTS xcatdsklspost
  if [ "$RUNBOOTSCRIPTS" != "'yes'" ]; then
```

It looks like you are trying to use a regular expression to make the test more robust for RUNBOOTSCRIPTS=yes and RUNBOOTSCRIPTS='yes' in the myxcatpost file.

However, in doing that you should also probably match the syntax in the xcatdsklspost.

**Comment by immarvin** [comment]
hi @ralphbellofatto , another fix in https://github.com/xcat2/xcat-core/pull/2173

**Pull request merged**
