### PR TITLE
Add redfish support perl part

### PR DESCRIPTION
**Pull request by xuweibj**
https://github.com/xcat2/xcat2-task-management/issues/157

1. Add new mgt type "redfish", modify Schema.pm.
2. Add new plugin "redfish.pm" 
2.1 collect data : bmc, bmcip, bmcusername, bmcpassword
2.2 check commands args (current only handle ``rpower``)
2.3 call AGENT.pm to pass data to python
3. Move agent code from OPENBMC.pm to AGENT.pm

Data want to pass to python like this:
```
{"cwd":["/root"],"nodeinfo":{"boston_redfish":{"password":"ADMIN","bmc":"x.x.x.x","bmcip":"x.x.x.x","username":"ADMIN"}},"args":["stat"],"nodes":["boston_redfish"],"envs":{"debugmode":"1"},"command":"rpower","module":"redfish"}
```

### CODE REVIEW

**Comment by gurevichmark** [comment]
Reminder that changes to Schema.pm will cause man pages to be updated so new `.rst` files will need to be generated and checked in.

**Comment by whowutwut** [comment]
Two issues before review code 

1. Feature branch is spelled wrong. Should be “support”
2. Root user commit this change, please amend the correct user and re push (-f force) to this PR

**Comment by xuweibj** [comment]
Hi @whowutwut , I have modified, shall we merge this pull request?

**Comment by zet809** [comment]
Let's merge this first.

**Pull request merged**
