### PR TITLE
[FVT]Update installation cases with rinstall command

### PR DESCRIPTION
**Pull request by caomengmeng**
@tingtli 
Please help to review code

### CODE REVIEW

**Comment by tingtli** [comment]
@caomengmeng  i am fine with the change. One comment is we also need to update the migration cases, please search all the cases and make sure we updates.

**Comment by caomengmeng** [comment]
@tingtli
please help to review files with latest update for rinstall

**Comment by tingtli** [comment]
i don't have further comments. @immarvin  How about your opinion?

**Comment by immarvin** [comment]
i am ok with the change

**Pull request merged**
