### PR TITLE
refine xcat-inventory test case

### PR DESCRIPTION
**Pull request by immarvin**

### CODE REVIEW

**Comment by immarvin** [comment]
UT:
```
[root@c910f03c05k21 xcat_inventory_try_to_export_all_type_is_node_default_format]# XCATTEST_DSTMN=10.3.5.21 xcattest -t [root@c910f03c05k21 xcat_inventory_try_to_export_all_type_is_node_default_format]# xcattest -t export_import_site_by_json
...

------END::export_import_site_by_json::Passed::Time:Fri May 25 03:21:39 2018 ::Duration::12 sec------
------Total: 1 , Failed: 0------

xCAT automated test finished at Fri May 25 03:21:39 2018
Please check results in the /opt/xcat/bin/../share/xcat/tools/autotest/result/,
and see /opt/xcat/bin/../share/xcat/tools/autotest/result//failedcases.20180525032127 file for failed cases.
see /opt/xcat/bin/../share/xcat/tools/autotest/result//performance.report.20180525032127 file for time consumption
```

**Comment by immarvin** [comment]
UT:
```
[root@c910f03c05k21 /]# XCATTEST_DSTMN=10.3.5.21 xcattest -t xcat_inventory_try_to_export_all_type_is_site_default_format
...
------END::xcat_inventory_try_to_export_all_type_is_site_default_format::Passed::Time:Fri May 25 03:23:20 2018 ::Duration::3 sec------
------Total: 1 , Failed: 0------

xCAT automated test finished at Fri May 25 03:23:20 2018
Please check results in the /opt/xcat/bin/../share/xcat/tools/autotest/result/,
and see /opt/xcat/bin/../share/xcat/tools/autotest/result//failedcases.20180525032316 file for failed cases.
see /opt/xcat/bin/../share/xcat/tools/autotest/result//performance.report.20180525032316 file for time consumption
[root@c910f03c05k21 /]#
```

**Comment by immarvin** [comment]
UT:
```
[root@c910f03c05k21 /]# XCATTEST_DSTMN=10.3.5.21 xcattest -t xcat_inventory_try_to_export_all_type_is_site_json_format
...
------END::xcat_inventory_try_to_export_all_type_is_site_json_format::Passed::Time:Fri May 25 03:24:23 2018 ::Duration::4 sec------
------Total: 1 , Failed: 0------

xCAT automated test finished at Fri May 25 03:24:23 2018
Please check results in the /opt/xcat/bin/../share/xcat/tools/autotest/result/,
and see /opt/xcat/bin/../share/xcat/tools/autotest/result//failedcases.20180525032418 file for failed cases.
see /opt/xcat/bin/../share/xcat/tools/autotest/result//performance.report.20180525032418 file for time consumption
```

**Comment by immarvin** [comment]
UT:
```
[root@c910f03c05k21 /]# XCATTEST_DSTMN=10.3.5.21 xcattest -t xcat_inventory_try_to_export_all_type_is_site_yaml_format,xcat_inventory_try_to_import_all_type_is_site_json_format,xcat_inventory_try_to_import_all_type_is_site_yaml_format,export_site_table_then_modify_yaml_then_import,export_site_table_then_modify_json_then_import

...

------END::export_site_table_then_modify_json_then_import::Passed::Time:Fri May 25 03:26:32 2018 ::Duration::10 sec------
------Total: 5 , Failed: 0------

xCAT automated test finished at Fri May 25 03:26:32 2018
Please check results in the /opt/xcat/bin/../share/xcat/tools/autotest/result/,
and see /opt/xcat/bin/../share/xcat/tools/autotest/result//failedcases.20180525032542 file for failed cases.
see /opt/xcat/bin/../share/xcat/tools/autotest/result//performance.report.20180525032542 file for time consumption
```

**Comment by hu-weihua** [comment]
It is ok for me, thanks @immarvin

**Comment by whowutwut** [comment]
@immarvin @hu-weihua  this is great! 

Some questions/ comments... For the files created during the test cases are we doing proper clean up?  Should we consider starting to put all test case working  files into a single directory  in tmp.  This way we have debug information if the case fails and makes it easy to clean up 

@immarvin are there any example of a single failure in the above cases and how one would easily debug the cause of the failure?  Essentially if it fails  can we figure out why from output or logs or do we have to manually re run the case to debug?

**Comment by hu-weihua** [comment]
@whowutwut , The first lines of most case of ``xcat-inventory`` like below

```
cmd:dir="/tmp/xcat_inventory_export_option_f";echo ${dir}".old";if [ -d "${dir}" ];then mv ${dir} ${dir}".old"; fi; mkdir -p $dir
check:rc==0
```
The last lines like below 
```
cmd:dir="/tmp/xcat_inventory_export_option_f"; rm -rf $dir; if [ -d ${dir}".old" ];then mv ${dir}".old" $dir; fi
check:rc==0
```
That means we created a directory which has the same name with test case under ``/tmp``, all temporary files generated by current case will be saved in this directory, when the case exits, the whole directory will be deleted.  One standard of writing a case is do not change anything in current environment. If you find any case does not clean up the file it created, close issue for that. 

The other standard of writing a case is that customer can get all debug information from log and need not to rerun a case. If you find any case's log is not convenient to debug, open issue for it, FVT will refine them ASAP. thanks

**Comment by whowutwut** [comment]
👍 great @hu-weihua  Seem my comments here: https://github.com/xcat2/xcat-core/pull/5240#issuecomment-393257973 
 
> The other standard of writing a case is that customer can get all debug information from log and need not to rerun a case. If you find any case's log is not convenient to debug, open issue for it, FVT will refine them ASAP

One comment I have is that if we store everything in a sub dir to save for debug, we don't need to back it up on the next run, but just delete it completely.  That will simply the logic of the testcases.

**Comment by hu-weihua** [comment]
@whowutwut, FVT suppose test case can be run on any one's environment, the reason why back up directory is to avoid there is customer's directory has the same name with the directory we plan to save log.  In order not to change customer's environment, so it is better to back up.

**Comment by whowutwut** [comment]
@hu-weihua correct and one good way to avoid this is to create a unique name   Like /tmp/_xcattest_<casename>.temp Where it is more unlikely to be the same from customers. 

Then we don’t have to back up files and we can easily identify test working files and do an easy cleanup. ‘rm -rf /tmp/_xcattest_*’

**Pull request merged**
