### PR TITLE
Fix issue 1029 [FVT] The word trusty is hard coded in the script mlnxofed_ib_install.v2

### PR DESCRIPTION
**Pull request by hu-weihua**
Fix issue #1029  [FVT] The word trusty is hard coded in the script mlnxofed_ib_install.v2

### CODE REVIEW

**Comment by whowutwut** [comment]
@hu-weihua ,  since you are touching this file, can you `chmod 755 mlnxofed_ib_install.v2` and commit that file permission change. Then lets remove the instructions for chmod in the RTD. 

http://xcat-docs.readthedocs.io/en/latest/advanced/networks/infiniband/mlnxofed_ib_install_v2_preparation.html

The other postscripts all have execute permission, so we should make this consistent.

**Comment by hu-weihua** [comment]
@whowutwut, I have added the execute permission for  ``mlnxofed_ib_install.v2``. 
About the document, I will change it later, I have another document changing requirement from issue #975, I will change it with that at same time. thanks for your comments

**Comment by neo954** [comment]
Will merge this one.

**Comment by whowutwut** [comment]
@hu-weihua  Thanks!

**Pull request merged**
