### PR TITLE
makehosts enhancement

### PR DESCRIPTION
**Pull request by bybai**
**Requirements**:
In current makehosts fuction, if there are configured other interfaces in hosts table, makehosts will add line in /etc/hosts as following: 
ip host-<ext> host-<ext>.domain 
The new requirement is : makehosts will have a label, if this label is configured, makehosts can generate one more column host.domain, such as following in /etc/hosts:
ip host-<ext> host-<ext>.domain host.domain

**Design**:
Add ":1" for otherinterfaces as a label to control if makehosts will generate one more column host.domain or not.
If we configure otherinterfaces in hosts table format like this: -<ext>:<ip>:1,......, after makehosts command, this line will be added in /etc/hosts:
ip host-<ext> host-<ext>.domain host.domain
If we do not configure otherinterfaces with ":1", format like this: -<ext>:ip,......, after makehosts command, this line will be added in /etc/hosts:
ip host-<ext> host-<ext>.domain

**Test results:**
CASE1:
````
~]# tabedit nics
# node,nicips,nichostnamesuffixes,nichostnameprefixes,nictypes,niccustomscripts,nicnetworks,nicaliases,nicextraparams,nicdevices,nicsadapter,comments,disable

"__NetworkProfile_default_network_profile",,"eth0!-eth0,eth2!-eth2",,"eth0!Ethernet,eth2!Ethernet",,"eth0!private,eth2!public",,,,,,
"c910f04x23","eth0!10.4.41.30,eth2!9.21.54.3","eth0!-eth0,eth2!-eth2",,,,,"eth2!c910f04x23.pub.com",,,,,

 ~]# tabdump hosts
# node,ip,hostnames,otherinterfaces,comments,disable

"c910f04x23","10.4.41.30","c910f04x23","-eth2:9.21.54.3:1",,

 ~]# cat /etc/hosts|grep c910f04x23
10.4.41.30 c910f04x23 c910f04x23.cluster.com c910f04x23-eth0
9.21.54.3 c910f04x23-eth2 c910f04x23-eth2.pub.com c910f04x23.pub.com

 ~]# tabdump networks
# netname,net,mask,mgtifname,gateway,dhcpserver,tftpserver,nameservers,ntpservers,logservers,dynamicrange,staticrange,staticrangeincrement,nodehostname,ddnsdomain,vlanid,domain,comments,disable

"private","10.0.0.0","255.0.0.0","eth0","10.0.0.103",,"10.5.106.8",,,,,,,,,,"cluster.com",,
"public","9.21.54.0","255.255.255.0","eth2","<xcatmaster>",,"9.21.54.1",,,,,,,,,,"pub.com",,

CASE2:
~]# tabdump networks
# netname,net,mask,mgtifname,gateway,dhcpserver,tftpserver,nameservers,ntpservers,logservers,dynamicrange,staticrange,staticrangeincrement,nodehostname,ddnsdomain,vlanid,domain,comments,disable

"private","10.0.0.0","255.0.0.0","eth0","10.0.0.103",,"10.5.106.8",,,,,,,,,,"cluster.com",,
"public","9.21.54.0","255.255.255.0","eth2","<xcatmaster>",,"9.21.54.1",,,,,,,,,,"pub.com",,
~]# tabdump hosts
# node,ip,hostnames,otherinterfaces,comments,disable

"c910f04x23","10.4.41.30","c910f04x23","-eth2:9.21.54.3:1,-eth1:9.21.54.4",,
~]# makehosts -n
~]# cat /etc/hosts |grep c910f04x23
10.4.41.30 c910f04x23 c910f04x23.cluster.com
9.21.54.3 c910f04x23-eth2 c910f04x23-eth2.pub.com c910f04x23.pub.com
9.21.54.4 c910f04x23-eth1 c910f04x23-eth1.pub.com
````

### CODE REVIEW

**Comment by immarvin** [comment]
manpage required

**Comment by immarvin** [comment]
hi @daniceexi , do you have comments on this PR?

**Comment by daniceexi** [comment]
I think we still need to refine the user interface for this new feature. Please catch me to discuss this.

**Comment by immarvin** [comment]
hi @bybai , please discuss this PR with @daniceexi offline

**Comment by whowutwut** [comment]
@bybai  can we format the description above a little better?

**Comment by kcgthb** [comment]
How will that interact with `makedns`?

**Comment by bybai** [comment]
Hi @daniceexi and @immarvin and @whowutwut 
Could the following explanation be better for otherinterfaces?

Other IP addresses to add for this node in /etc/hosts. Format: -<ext>:<ip>[ |:1],<intfhostname>:<ip>,....
<ext> is hostname suffix for nic. We can use -<ext>:<ip> or -<ext>:<ip>:1, if we use -<ext>:<ip> here, makehosts will add the line 'ip hosts-<ext> host-<ext>.domain' in /etc/hosts, if we use -<ext>:<ip>:1, makehosts will add the line 'ip hosts-<ext> host-<ext>.domain host.domain' in /etc/hosts.

**Comment by bybai** [comment]
Hi @kcgthb ,
makedns can resolve correctly for the following example:
9.21.54.3 c910f04x23-eth2 c910f04x23-eth2.pub.com c910f04x23.pub.com
9.21.54.4 c910f04x23-eth1 c910f04x23-eth1.pub.com

**Comment by whowutwut** [comment]
@bybai  we need to associate a milestone with the pull request, I am moving off to 2.13.1 for now since we are preparing for 2.13 GA.

**Comment by zet809** [comment]
Hi, @bybai and @immarvin , any updates for this Pull Request?

**Comment by bybai** [comment]
Hi @zet809 ,
this pull request will be closed, The fix will be abandoned. Will fix in new pull request.

**Comment by zet809** [comment]
Hi, @bybai , will you pls attend the number of the new pull request first and then close this pull request? Thx a lot!

**Pull request closed without merging**
