### PR TITLE
Regenerate .rst man pages with create_man_pages

### PR DESCRIPTION
**Pull request by gurevichmark**
Regenerating the `.rst` man files changed by #5429 

`.rst` man pages should not be directly modified. Use `create_man_pages.py` instead

### CODE REVIEW

**Comment by gurevichmark** [comment]
Close/reopen to restart Travis.

**Comment by whowutwut** [comment]
Seem the travis test has some instability, many of them are failing. This PR has nothing to do with xCAT code and only affects  https://xcat-docs.rtfd.io/ so passing CI is not really needed.

**Comment by gurevichmark** [comment]
I think there is a failure in one of the regression tests that Travis runs:
```
'RUN:lsdef -s dyngrp [Fri Aug 31 15:03:55 2018]',
          'ElapsedTime:0 sec',
          'RETURN rc = 1',
          'OUTPUT:',
          'Error: [travis-job-3c103938-ad61-45be-95f7-6369e07f8903]: Could not find an object named \'dyngrp\' of type \'node\'.',
          'CHECK:rc == 0	[Failed]',
          ' ',
```

**Comment by gurevichmark** [comment]
Close/reopen to trigger Travis rerun.

**Comment by gurevichmark** [comment]
Close/reopen to trigger Travis rerun.

**Pull request merged**
