### PR TITLE
[OpenBMC] Support bootmode generically

### PR DESCRIPTION
**Pull request by whowutwut**
This function is used to view/set the host bootmode.  This is really added to help debug some strange issues that we are seeing where certain machines are stopping at Petitboot and not booting off the network on first discovery. 

The 4th commit is related to PowerSupplyRedundancy (tag #4715) in that the value takes effect on a IPL, not a bmc reboot.  A bmcreboot actually removes the setting. 

I'd like to get this into the 2.13.10 release tomorrow. 

UT:
```
[root@stratton01 Control]# rspconfig p9euh01 powersupplyredundancy=disablEd
p9euh01: BMC Setting BMC PowerSupplyRedundancy...
[root@stratton01 Control]# rspconfig p9euh01 bootmode
p9euh01: BMC BootMode : Regular
[root@stratton01 Control]# rspconfig p9euh01 bootmode=setup
p9euh01: BMC Setting BMC BootMode...
[root@stratton01 Control]# rspconfig p9euh01 bootmode
p9euh01: BMC BootMode : Setup
[root@stratton01 Control]# rspconfig p9euh01 bootmode=regular
p9euh01: BMC Setting BMC BootMode...
[root@stratton01 Control]# rspconfig p9euh01 bootmode
p9euh01: BMC BootMode : Regular
[root@stratton01 Control]#
```

On errror, we would see the following msg: 
```
[root@stratton01 Control]# rspconfig p9euh01 bootmode
p9euh01: BMC BootMode : Regular
p9euh01: WARNING: Unexpected value set: xyz.openbmc_project.Control.Boot.Mode.Modes.Regular
p9euh01: WARNING: Valid values: xyz.openbmc_project.Control.Boot.Mode.Safe,xyz.openbmc_project.Control.Boot.Mode.Regular,xyz.openbmc_project.Control.Boot.Mode.Setup
```

### CODE REVIEW

**Comment by zet809** [comment]
hi, @whowutwut , why not implement the boot mode interface to rsetboot as I suggest in https://ibm-systems-storage.slack.com/archives/C68N2UK0X/p1516868331000070?thread_ts=1516820529.000339&cid=C68N2UK0X?
For `rsetboot`, it is used to set boot order, and also can be used to set boot mode, right?

**Comment by whowutwut** [comment]
@zet809 What would be the suggested interface here if we tagged to rspconfig? 

The rsetboot is temporarily setting the next boot of the server, where this bootmode in my opinion is really a debug attribute.  The use case here is to run across a large number of systems and make sure that the value is "Regular" I don't think customer will be messing with this value at all.  MFG uses it when pre-loading the server, but should return the value to Regular when ship out. 

So really, adding this attribute is really to help debug and allow xCAT to display this OpenBMC configuration value more easily

**Comment by zet809** [comment]
Hi, @whowutwut , I think you are right that bootmode mainly useful for debugging.
But `rspconfig` is mostly configuration for BMCs, but bootmode works for host, right?

**Comment by whowutwut** [comment]
Resolves #4718

**Comment by whowutwut** [comment]
@zet809 Yes, bootmode controls the behavior I believe up to Petitboot... when the host IPLs..

**Pull request merged**
