### PR TITLE
Clean up the usage and manpage for bmcdiscover command

### PR DESCRIPTION
**Pull request by whowutwut**
Cleaned up the usage and manpage for bmcdiscover command
Improve the output message for --ipsource and --check to be more informative for the user

### CODE REVIEW

**Comment by whowutwut** [comment]
@tingtli , some of the usage output and the command behavior will change with this pull request....  are there any autotest cases that test ``bmcdiscover``? 

@zet809, was not sure to assign you this for review or @bybai ?

**Comment by zet809** [comment]
@whowutwut sorry for the delayed review, it looks good to me. But you need to deal with the conflict before merge.

**Comment by whowutwut** [comment]
@gurevichmark  Can you take a quick look at the bmcdiscover.pod file, the version is on the 2nd line here but in the code in the master branch, it's on the same line as the help option.   I want to make sure I'm not undoing some change that you did.. or vice versa...

**Comment by whowutwut** [comment]
@zet809  I finished the changes with the last commit.. some changes to the usage.  Can you review and merge if OK?

**Comment by zet809** [comment]
Looks good to me, I agree to merge.

**Pull request merged**
