### PR TITLE
Fix isse #801, change the package name perl-xCAT to perl-xcat.

### PR DESCRIPTION
**Pull request by neo954**
Fixing the Ubuntu packaging problem.

### CODE REVIEW

**Comment by daniceexi** [comment]
Refer to the issue #790, this fix is reasonable to complain the issue why there's dependency issue for 16.04.
It's OK to merge.

**Comment by whowutwut** [comment]
@neo954 @daniceexi  Sorry for this late review, but we should have probably checked all control files to make sure we are doing lowercase in every spot.  We missed ``xCAT-client`` in:
https://github.com/xcat2/xcat-core/blob/master/xCAT-OpenStack-baremetal/debian/control
https://github.com/xcat2/xcat-core/blob/master/xCAT-vlan/debian/control

**Comment by daniceexi** [comment]
Good point, we need to change all the dependency packages name to be low case in the Debian deb control file. @neo954

**Comment by neo954** [comment]
Created new pull request #823.

**Pull request merged**
