### PR TITLE
Fix systemctl commands in the install guide

### PR DESCRIPTION
**Pull request by khaledsalim**

### CODE REVIEW

**Comment by whowutwut** [comment]
Hi @khaledsalim  Thanks for your interest in the xCAT project! Before we are able to pull in this Pull Request, we need you to sign the xCAT CLA agreement, the instructions are here: http://xcat-docs.readthedocs.io/en/stable/developers/license/index.html

**Comment by khaledsalim** [comment]
Hello @whowutwut,

I have emailed the singed CLA to the mentioned email address in the document.

Thank you.

**Comment by whowutwut** [comment]
Thanks, got it.  Thanks for making the fixes to the doc!

**Comment by whowutwut** [comment]
@khaledsalim  I noticed that you created the pull request off of your forked master branch.  One tip that we suggest is creating a branch for your fixes, not using the master branch in your fork copy.  This will allow you to more easily keep your forked copy in sync with xcat2/xcat-core (the upstream) repository.  After a pull request is merged, the branch is normally deleted.    

Sometimes a pull request takes some time to review, so having it in a separate branch allows you to continue working on other fixed and pulling down changes from the upstream, without affecting the active pull request.

**Comment by khaledsalim** [comment]
@whowutwut Thanks for the tip, I will consider it in my upcoming contributions.

Thanks for accepting the pull request.

**Pull request merged**
