### PR TITLE
Add -f option to nodestat usage

### PR DESCRIPTION
**Pull request by aduffy19**
Add -f documentation

### CODE REVIEW

**Comment by immarvin** [comment]
hi @aduffy19 ,Thanks for your interest in the xCAT project and your pull request! We appreciate it. Before we are able to accept contributions, we do require a CLA to be signed. You can find the document and instructions here:
http://xcat-docs.readthedocs.io/en/stable/developers/license/contributors.html

CLA or CCLA (corporate).. If you are covered under a corporate CLA, please let us know the company and we will add your ID into the list. Thanks!

**Comment by robin2008** [comment]
@aduffy19  It seems you don't modify `usage` method, are you sure that the '-f' is added into usage?

**Comment by gurevichmark** [comment]
Interestingly, man page already has `-f` option. But seems like the code never handled it ?

**Comment by jjohnson42** [comment]
FYI, -f does get consumed, the usage message in this pull request is pointless.

Evidently, there exists at least one user that was using this feature.

**Comment by aduffy19** [comment]
Replaced by pull request 4849

**Comment by whowutwut** [comment]
@immarvin amanda is covered under the Lenovo CCLA so this is ok

**Pull request closed without merging**
