### PR TITLE
[OpenBMC] Support older endpoint path before OP910 1738 driver, fix rsetboot, 403 message.

### PR DESCRIPTION
**Pull request by whowutwut**
To support machines with older firmware than OP910 1738, we need to allow for an environment variable that would change the URL endpoints back to what it was prior to 1738.  

The issue here is that on https://github.com/xcat2/xcat-core/pull/3982 made a change to the endpoint that is used to select boot source based on what we had seen with FW 1738...  however, many of our machines are not upgraded yet to that FW level and so we are unable to control them correctly.  

Machines with firmware level > 1738 should NOT have any impact because of PR #3982, but prio firmware levels would see the following error: 
```
[root@briggs01 ~]# rsetboot mid05tor12cn18 net
mid05tor12cn18: Error: 403 Forbidden - This function is not yet available in OpenBMC firmware.
```

This is because the endpoint is not correct so we get a 403 error code. 

To work around with the PR, you would do the following: 
```
[root@briggs01 ~]# export XCAT_OPENBMC_FIRMWARE=1736
[root@briggs01 ~]# rsetboot mid05tor12cn18 net
mid05tor12cn18: Network
```

### CODE REVIEW

**Comment by whowutwut** [comment]
This code was used by @gurevichmark and myself yesterday, so after the Travis CI checking is complete, I plan to merge it so get the fix into the development build so our internal teams can pick it up asap...

**Comment by xuweibj** [comment]
Hi @whowutwut , for pull request #3982 option ``-o`` is used to support firmware and other old version, I think if you modify like this, we do not need ``-o `` option.

**Comment by whowutwut** [comment]
@xuweibj , I see...  we were not  sure what that `-o` option was for but did not have time to take a closer look last Friday.   I will take a look at this -o option later this week...

**Comment by whowutwut** [comment]
Actually, I just decided to try this out...

```
[root@briggs01 ~]# rsetboot mid05tor12cn18 net 
mid05tor12cn18: Error: 403 Forbidden - This function is not yet available in OpenBMC firmware.
[root@briggs01 ~]# rsetboot -o mid05tor12cn18 net
Unsupported command: rsetboot -o
[root@briggs01 ~]# rsetboot mid05tor12cn18 net -o
mid05tor12cn18: Error: 403 Forbidden - This function is not yet available in OpenBMC firmware.

```

How is it invoked? 

Here is the change with the PR to show that this machine is actually running the 1736 FW...
```
[root@briggs01 ~]# export XCAT_OPENBMC_FIRMWARE=1736
[root@briggs01 ~]# rsetboot mid05tor12cn18 net
mid05tor12cn18: Network
[root@briggs01 ~]# unset XCAT_OPENBMC_FIRMWARE
[root@briggs01 ~]# rsetboot mid05tor12cn18 net
mid05tor12cn18: Error: 403 Forbidden - This function is not yet available in OpenBMC firmware.
[root@briggs01 ~]# 
```

**Pull request merged**
