### PR TITLE
fix issue 5499: rflash option needed to update PNOR or BMC individually for P9 OpenPower servers

### PR DESCRIPTION
**Pull request by zet809**
Fix issue #5499 

Not add new options, just provide 2 environment variables to enable PNOR or BMC update:
`XCAT_PUPDATE_BMC` and `XCAT_PUPDATE_PNOR`

The UT result:
```
[root@stratton01 tmp]# XCAT_PUPDATE_BMC=1 rflash boston02 -d /root/vhu/20170729PNOR_BMC0.23/
boston02: Update BMC firmware: /root/vhu/20170729PNOR_BMC0.23//DEBUG_P9_023.bin

[root@stratton01 tmp]# XCAT_PUPDATE_PNOR=1 rflash boston02 -d /root/vhu/20170729PNOR_BMC0.23/
boston02: Update PNOR firmware: /root/vhu/20170729PNOR_BMC0.23//p9dsu07292017_IBM_sign.pnor

[root@stratton01 tmp]# rflash boston02 -d /root/vhu/20170729PNOR_BMC0.23/
boston02: Update BMC firmware: /root/vhu/20170729PNOR_BMC0.23//DEBUG_P9_023.bin
boston02: Update PNOR firmware: /root/vhu/20170729PNOR_BMC0.23//p9dsu07292017_IBM_sign.pnor

[root@stratton01 tmp]# XCAT_PUPDATE_BMC=1 XCAT_PUPDATE_PNOR=1 rflash boston02 -d /root/vhu/20170729PNOR_BMC0.23/
boston02: Update BMC firmware: /root/vhu/20170729PNOR_BMC0.23//DEBUG_P9_023.bin
boston02: Update PNOR firmware: /root/vhu/20170729PNOR_BMC0.23//p9dsu07292017_IBM_sign.pnor

```

### CODE REVIEW

**Comment by whowutwut** [comment]
Reopen to kick off CI

**Comment by gurevichmark** [comment]
Do we need to update the `man` page for `rflash`? Or are these env variables for internal use only ?

**Comment by whowutwut** [comment]
@zet809 @gurevichmark  I think this is OK as a work around for the time being since we want to be more quick to make this change...  I think what we should do is look into creating a standard interface that would result in similar behavior between IPMI (SMC) and OpenBMC boxes. both have separate BMC and PNOR/HOST files ...

**Comment by whowutwut** [comment]
@hu-weihua  I am OK to merge this but seems  like some fundamental problem with the CI ..

**Comment by zet809** [comment]
Hi, @gurevichmark , I agree with Victor that this is a quick work around, so I add 2 environment to enable the separate uploading.
And, another thought is, for ipmi rflash, it is shared by Boston(PNOR+BMC file) and P8 OpenPower server(only 1 hpm file), new options will involve in much complex to parse args...
So, if no more requirement, I think the 2 env variable is enough. What is your idea?

**Comment by hu-weihua** [comment]
@whowutwut I just rerun the CI test, it seems all things are fine now.

**Pull request merged**
