### PR TITLE
remove setupntp for sles12.1 ntpd doesn't synchronize to local clock …

### PR DESCRIPTION
**Pull request by tingtli**
…anymore in version 4.2.8p4. see#2248

### CODE REVIEW

**Comment by immarvin** [comment]
agree to merge

**Comment by whowutwut** [comment]
@tingtli  @immarvin   I just caught this....  this pull request branch is against 2.13, this is incorrect.  we should not be creating changes against 2.13 branch but against master branch, then we merge master -> release when we are creating the RC builds.

**Comment by whowutwut** [comment]
I think it might be OK because there seems to be no conflicts with merging master to 2.13, but your changes might NOT be in the master branch....

**Comment by tingtli** [comment]
@whowutwut  This commit is also in master branch. After I check in the code in master branch, i cherry pick this commit to 2.13 branch. The commit number is 8ec1af2f0c07e09cad8644708b04a18d9c099e5d.

The reason I need to check this change to 2.13 is because FVT also run some tests against 2.13 branch to fix some test framework stability problems.

**Pull request merged**
