### PR TITLE
update labels

### PR DESCRIPTION
**Pull request by tingtli**
Update labels

### CODE REVIEW

**Comment by chuckbrazie** [comment]
I am out of the office until 07/16/2018.

I am out of the office until  Monday July 16.


Note: This is an automated response to your message  "[xcat2/xcat-core]
update labels (#5368)" sent on 7/4/18 3:45:42 AM.

This is the only notification you will receive while this person is away.

**Comment by chuckbrazie** [comment]
I am out of the office until 07/16/2018.

I am out of the office until  Monday July 16.


Note: This is an automated response to your message  "Re: [xcat2/xcat-core]
update labels (#5368)" sent on 7/4/18 3:48:49 AM.

This is the only notification you will receive while this person is away.

**Comment by hu-weihua** [comment]
It is ok for me, thanks @tingtli

**Comment by chuckbrazie** [comment]
I am out of the office until 07/16/2018.

I am out of the office until  Monday July 16.


Note: This is an automated response to your message  "Re: [xcat2/xcat-core]
update labels (#5368)" sent on 7/4/18 6:02:02 AM.

This is the only notification you will receive while this person is away.

**Comment by chuckbrazie** [comment]
I am out of the office until 07/16/2018.

I am out of the office until  Monday July 16.


Note: This is an automated response to your message  "Re: [xcat2/xcat-core]
update labels (#5368)" sent on 7/4/18 6:02:07 AM.

This is the only notification you will receive while this person is away.

**Pull request merged**
