### PR TITLE
Use defined variable in updateflag.awk

### PR DESCRIPTION
**Pull request by Obihoernchen**
just minor code cleanup

### CODE REVIEW

**Comment by immarvin** [comment]
hi @Obihoernchen   Thanks for this pull request and your interest in the xCAT project. In order for the xCAT team to consider your changes, you must first sign a CLA, instructions are documented here: http://xcat-docs.readthedocs.io/en/stable/developers/license/contributors.html

Or if you know you are covered under a Corporate CLA that was signed, can you please give us the corporation name and we can verify. Thanks!

**Comment by Obihoernchen** [comment]
Hi @immarvin I'm an IBMer ;) No need for CLA.

**Comment by immarvin** [comment]
agree to merge

**Comment by immarvin** [comment]
hi @Obihoernchen , would you please send me a mail with your @ibm mail address? So that we can talk  about the customer issue related to this ticket internally? 

My address is 
``yangsbj(AT)cn.ibm.com``
please replace ``(AT)`` with ``@``
thanks

**Pull request merged**
