### PR TITLE
simplify the process of running xCAT in Docker with Docker 1.10

### PR DESCRIPTION
**Pull request by immarvin**
http://10.3.5.21/doc/advanced/docker/run_xcat_in_docker.html

### CODE REVIEW

**Comment by daniceexi** [comment]
@immarvin I am note sure how many people has been moved to docker 1.10. Since we already has the doc to make it works well for docker 1.09 or lower version, we suggest we can keep the original doc and make this new doc to be the one for v1.10 and newer.

**Comment by immarvin** [comment]
On the loop device problem, i added the code logic to create loop device in startservice.sh

**Comment by immarvin** [comment]
Hi, i do not think there is anyone using xcat in docker now, since we have not released it yet. Since docker is in the fast development phase,  the behavior changes and new features are introduced in each major release, some options are deprecated,some are added, the behavior of some existing options are changed, this will continue until it is matured and stable enough in the production environment.   It seems docker does not care backward compatibility at this time,  so I think it is ok for xcat to support the latest docker major release, docker.docs provided the steps on docker upgrade , we do not need to worry about this.

I think we should focus on xcat release in xcat docker  image instead of docker release, since the xcat docker image on docker hub is built and based on the features of docker v1.10 release, i am not sure whether it still works on docker 1.9, and i do not want to put any effort to make sure this:)

**Comment by immarvin** [comment]
Ping @daniceexi

**Comment by daniceexi** [comment]
OK. If our xCAT docker image is built base on docker v1.10, it's reasonable to only support v1.10 now.

**Pull request merged**
