### PR TITLE
Fix insecure processing of XML input

### PR DESCRIPTION
**Pull request by jjohnson42**
XML::Simple is not up to the task.  Switch to
XML::LibXML::Simple and coax it to not do as much
XML to avoid XXE attacks.

### The modification include

_##item1_

_##item2_

### The UT result
`##The UT output##`

# Please remove this line and below if fix issue

# Please remove this line and above for tasks or features

### The PR is for task _#xxx_ or to implement feature #xxx

_##Feature description##_

### The content of the PR:
* [ ] _##The mini-design link_
* [ ] _##The basic code logic_

### The UT result
`##The UT output##`

### CODE REVIEW

**Comment by gurevichmark** [comment]
@jjohnson42 Can you please take a look at the output of the Travis regression test for this PR? Is the failure related to your proposed change ?

**Comment by gurevichmark** [comment]
@jjohnson42 We are trying to decide which PRs to merge into the next release of xCAT.
Can you check the output of the Travis regression test for this PR? Is the failure related to your proposed change ?

**Comment by thotypous** [comment]
Shouldn't this be listed [here](https://xcat-docs.readthedocs.io/en/latest/security/index.html)? And sorry for being rude, but 5 months to merge a security fix?

**Comment by besawn** [comment]
> Shouldn't this be listed [here](https://xcat-docs.readthedocs.io/en/latest/security/index.html)? And, not to be rude, but 5 months to merge a simple security fix for a potentially serious vulnerability?

The fix did not pass continuous integration testing, so it needs to be modified and cannot be merged as-is.

**Comment by gurevichmark** [comment]
Closing. Replaced by #6688

**Pull request closed without merging**
