### PR TITLE
Add labels for xcatd test cases

### PR DESCRIPTION
**Pull request by hu-weihua**
* Add labels for xcatd test cases
* combine some test cases
* Add labels for some usage test cases

Related task xcat2/xcat2-task-management#208

### CODE REVIEW

**Comment by hu-weihua** [comment]
```
# XCATTEST_CASEDIR="/git/pubgit/xcat-core/xCAT-test/autotest/testcase/lsxcatd" ./xcattest -l labelinfo
-------------------------------
The labels of cases:
-------------------------------
lsxcatd_a       mn_only,xcatd,
lsxcatd_d       mn_only,xcatd,
lsxcatd_h       mn_only,xcatd,
lsxcatd_null    mn_only,xcatd,
```

**Comment by hu-weihua** [comment]
```
# XCATTEST_CASEDIR="/git/pubgit/xcat-core/xCAT-test/autotest/testcase/xcatd" ./xcattest -l labelinfo
-------------------------------
The labels of cases:
-------------------------------
assign_certain_command_permission          mn_only,xcatd,
disable_root_permission_in_policy_table    mn_only,xcatd,
run_command_with_XCATBYPASS                mn_only,xcatd,
xcatd_restart                              mn_only,xcatd,
xcatd_start                                mn_only,xcatd,
xcatd_stop                                 mn_only,xcatd,
```

**Comment by hu-weihua** [comment]
```
# XCATTEST_CASEDIR="/git/pubgit/xcat-core/xCAT-test/autotest/testcase/xcatsnap" ./xcattest -l labelinfo
-------------------------------
The labels of cases:
-------------------------------
xcatsnap_b_d     mn_only,
xcatsnap_h       mn_only,
xcatsnap_null    mn_only,
xcatsnap_v       mn_only,
```

**Comment by hu-weihua** [comment]
```
# XCATTEST_CASEDIR="/git/pubgit/xcat-core/xCAT-test/autotest/testcase/xcatconfig" ./xcattest -l labelinfo
-------------------------------
The labels of cases:
-------------------------------
testtest                                        mn_only,db,
xcatconfig_c                                    mn_only,
xcatconfig_d_V                                  mn_only,
xcatconfig_h                                    mn_only,
xcatconfig_i                                    mn_only,
xcatconfig_k                                    mn_only,
xcatconfig_k_c                                  mn_only,
xcatconfig_null                                 mn_only,
xcatconfig_s                                    mn_only,
xcatconfig_s_c                                  mn_only,
xcatconfig_u                                    mn_only,
xcatconfig_u_check_xcatsslversion_rhels_sles    os=rhels,os=sles,mn_only,
xcatconfig_u_check_xcatsslversion_ubuntu        os=ubuntu,mn_only,
xcatconfig_v                                    mn_only,
```

**Comment by hu-weihua** [comment]
```
# XCATTEST_CASEDIR="/git/pubgit/xcat-core/xCAT-test/autotest/testcase/analyze_log" ./xcattest -l labelinfo
-------------------------------
The labels of cases:
-------------------------------
check_mn_cluster_log_file    mn_only,
```

**Comment by hu-weihua** [comment]
```
# XCATTEST_CASEDIR="/git/pubgit/xcat-core/xCAT-test/autotest/testcase/chvm" ./xcattest -l labelinfo
-------------------------------
The labels of cases:
-------------------------------
chvm_attr        hcp=hmc,others,virtualization,
chvm_err_node    mn_only,virtualization,
chvm_node        mn_only,virtualization,
chvm_p           hcp=hmc,others,virtualization,
```

**Comment by chuckbrazie** [comment]
I am out of the office until 07/16/2018.

I am out of the office until  Monday July 16.


Note: This is an automated response to your message  "Re: [xcat2/xcat-core]
Add labels for xcatd test cases (#5357)" sent on 7/2/18 9:57:29 AM.

This is the only notification you will receive while this person is away.

**Comment by chuckbrazie** [comment]
I am out of the office until 07/16/2018.

I am out of the office until  Monday July 16.


Note: This is an automated response to your message  "[xcat2/xcat-core] Add
labels for xcatd test cases (#5357)" sent on 7/2/18 9:53:30 AM.

This is the only notification you will receive while this person is away.

**Comment by chuckbrazie** [comment]
I am out of the office until 07/16/2018.

I am out of the office until  Monday July 16.


Note: This is an automated response to your message  "Re: [xcat2/xcat-core]
Add labels for xcatd test cases (#5357)" sent on 7/2/18 9:55:07 AM.

This is the only notification you will receive while this person is away.

**Comment by chuckbrazie** [comment]
I am out of the office until 07/16/2018.

I am out of the office until  Monday July 16.


Note: This is an automated response to your message  "Re: [xcat2/xcat-core]
Add labels for xcatd test cases (#5357)" sent on 7/2/18 9:56:46 AM.

This is the only notification you will receive while this person is away.

**Comment by chuckbrazie** [comment]
I am out of the office until 07/16/2018.

I am out of the office until  Monday July 16.


Note: This is an automated response to your message  "Re: [xcat2/xcat-core]
Add labels for xcatd test cases (#5357)" sent on 7/2/18 9:55:31 AM.

This is the only notification you will receive while this person is away.

**Comment by chuckbrazie** [comment]
I am out of the office until 07/16/2018.

I am out of the office until  Monday July 16.


Note: This is an automated response to your message  "Re: [xcat2/xcat-core]
Add labels for xcatd test cases (#5357)" sent on 7/2/18 9:54:34 AM.

This is the only notification you will receive while this person is away.

**Comment by chuckbrazie** [comment]
I am out of the office until 07/16/2018.

I am out of the office until  Monday July 16.


Note: This is an automated response to your message  "Re: [xcat2/xcat-core]
Add labels for xcatd test cases (#5357)" sent on 7/2/18 9:55:59 AM.

This is the only notification you will receive while this person is away.

**Comment by chuckbrazie** [comment]
I am out of the office until 07/16/2018.

I am out of the office until  Monday July 16.


Note: This is an automated response to your message  "Re: [xcat2/xcat-core]
Add labels for xcatd test cases (#5357)" sent on 7/2/18 9:56:24 AM.

This is the only notification you will receive while this person is away.

**Comment by chuckbrazie** [comment]
I am out of the office until 07/16/2018.

I am out of the office until  Monday July 16.


Note: This is an automated response to your message  "Re: [xcat2/xcat-core]
Add labels for xcatd test cases (#5357)" sent on 7/3/18 9:23:44 AM.

This is the only notification you will receive while this person is away.

**Pull request merged**
