### PR TITLE
More minor documentation changes

### PR DESCRIPTION
**Pull request by mfoliveira**
…ines so they actually become separate lines.

### CODE REVIEW

**Comment by mfoliveira** [comment]
Hi..
I'm going through some more sections, and may put more commits in this branch soon.

**Comment by bybai** [comment]
hi @mfoliveira, 
There are many commits in your pull requests. 
Could you use ``git commit --amend`` next time ?  
So that all the commits will be formed as one commit. 
You can refer to doc http://xcat-docs.readthedocs.org/en/latest/developers/github/pull_request.html#changing-pull-request

**Comment by mfoliveira** [comment]
Hi @bybay

Sure! No problem.

It turned out to be so many commits because I've been editing the files
directly on github as I went through them.

I can amend them next time. If this is required for this PR too, just let
me know.

Thanks!

**Comment by mfoliveira** [comment]
s/@bybay/@bybai/

**Comment by whowutwut** [comment]
@mfoliveira I think you are replying directly to the GitHub notifications, but you can edit your post directly from the GitHub UI also.. if you made a mistake spelling. Just FYI 

Anyway, I think this is kind of a debate....    I do see @bybai  point about reducing the number of commits, but I don't think git cares how many commits we make.  I also don't like the use of ``--amend`` unless I made a mistake with my commit. 

For example, if I'm working on a small function and make ``commit1``, but then I found I spelled something wrong, I would much rather fix the spelling mistake in ``commit1`` rather then creating ``commit2``.   Or maybe I'm working on a function and I think I have completed a checkpoint, I might commit that set of work.  The next day, I find I forgot something relating to that functional set, and so I would amend to include the missing piece.

Other than that I think it's **not** good to amend after we start reviewing pull requests.  I might spend 1-2 hours reviewing some large code change, then make 2-3 small comments,... If the originator uses amend, I CANNOT quickly see the 2 or 3 changes I requested.  I have to review EVERYTHING again.   it's better to just commit again and I can just look at the new differences from where I last reviewed.

**Comment by mfoliveira** [comment]
Hi @whowutwut 

Oh, cool. Thanks for the clarifications and rationale - really appreciated.

**Pull request merged**
