### PR TITLE
[go-xcat] Fix repository query and force problem resolution for zypper

### PR DESCRIPTION
**Pull request by neo954**
This pull request fix multiple problems on SLES.

### CODE REVIEW

**Comment by neo954** [comment]
This pull request solve issue #2835.

**Comment by neo954** [comment]
@robin2008 and @immarvin Please help review this pull request. The second patch of this pull request solve the migration problem on SLES. Which is due to xCAT changed the vendor name from `IBM Corp` to `IBM Corp.` in the metadata of some of the xCAT rpm packages.

**Comment by neo954** [comment]
See issue #2409.

**Comment by robin2008** [comment]
You fix may work on go-xcat, but I don't think this PR can resolve #2835 , as in xCAT-test package, for the migration in SLES,  it does not leverage go-xcat (BTW:  I don't see any zypper update in go-xcat,  is the tool support upgrade?) .

**Comment by immarvin** [comment]
seems there has been some discussion and decision in https://github.com/xcat2/xcat-core/issues/2409

**Comment by neo954** [comment]
@robin2008 This patch will not resolve #2835, since in #2835, there is no `go-xcat` involved. This patch only partly covered the problem. If the end user choose use `go-xcat` to do the xCAT upgrade, he/she will not hit the migration problem any more.

BTW, `go-xcat` does not call `zypper update`, instead, `go-xcat` calls `zypper install`. That is due to `zypper update` will update all the rpm packages installed on the system. But `go-xcat` will only update the packages xCAT shipped. Thus, `go-xcat` calls `zypper install` with a specific package list, in this way, only the packages shipped by xCAT will be updated.

**Comment by neo954** [comment]
@immarvin, issue #2409 will leave there as is. This patch only partly covered that issue if `go-xcat` is involved during xCAT upgrade procedure by adding the `--foce-resolution` command line argument to `zypper`.

**Comment by robin2008** [comment]
@neo954 
To current sprint, enhance go-xcat is another new task which is not planned. Our focusing is to clean up the failure in daily automation testing. Please enhance the SLES migration case to cover the specific version upgrade (you can added the version parsing there and do the corresponding upgrade action based on x -> y)

**Comment by robin2008** [comment]
Fine with the code change,  but I'm not very sure about the automatic resolution choice made by zypper when "--force-resolution" is applied. Assume that you have done the UT for go-xcat via xcattest.

**Comment by robin2008** [comment]
Code change is merged into go-xcat, let's verify it ASAP.

**Pull request merged**
