### PR TITLE
add labels for  makedhcp makedns xdcp xdsh makehosts command test cases

### PR DESCRIPTION
**Pull request by hu-weihua**
* Add labels for  test cases of ``makedhcp``, ``makedns``, ``xdcp``, ``xdsh``,`` makehosts``.
* delete some AIX test cases
* combine few cases

labels for ``makehosts``
```
-------------------------------
The labels of cases:
-------------------------------
makehost_n_r             mn_only,dns,
makehosts_d              mn_only,dns,
makehosts_h              mn_only,dns,
makehosts_help           mn_only,dns,
makehosts_l              mn_only,dns,
makehosts_n              mn_only,dns,
makehosts_n_noderange    mn_only,dns,
makehosts_null           mn_only,dns,
makehosts_regex          mn_only,dns,
```

labels for ``xdsh``
```
xdsh_E                    cn_os_ready,parallel_cmds,
xdsh_Q_command            cn_os_ready,parallel_cmds,
xdsh_T                    cn_os_ready,parallel_cmds,
xdsh_V                    mn_only,parallel_cmds,
xdsh_c_cn                 cn_os_ready,parallel_cmds,
xdsh_c_sn                 cn_os_ready,parallel_cmds,
xdsh_e_filename           cn_os_ready,parallel_cmds,
xdsh_h                    mn_only,parallel_cmds,
xdsh_i_linux              cn_os_ready,parallel_cmds,
xdsh_o                    cn_os_ready,parallel_cmds,
xdsh_permission_denied    cn_os_ready,parallel_cmds,
xdsh_q                    cn_os_ready,parallel_cmds,
xdsh_regular_command      cn_os_ready,parallel_cmds,
xdsh_t                    cn_os_ready,parallel_cmds,
```

labels for ``xdcp``
```
xdcp_P_src_dst                     cn_os_ready,parallel_cmds,
xdcp_R                             cn_os_ready,parallel_cmds,
xdcp_RP                            cn_os_ready,parallel_cmds,
xdcp_V                             mn_only,parallel_cmds,
xdcp_all_files_of_dir              cn_os_ready,parallel_cmds,
xdcp_h                             mn_only,parallel_cmds,
xdcp_rsync                         cn_os_ready,parallel_cmds,
xdcp_rsyncfile_files               cn_os_ready,parallel_cmds,
xdcp_rsyncfile_files_changename    cn_os_ready,parallel_cmds,
xdcp_rsyncfile_single_file         cn_os_ready,parallel_cmds,
xdcp_src_dst                       cn_os_ready,parallel_cmds,
```

labels of ``makedns`
```
makedns                                          mn_only,dns,
makedns_d_node                                   mn_only,dns,
makedns_environment_check_forworder_mode         os=sles,cn_os_ready,dns,
makedns_environment_check_master_slave_mode      os=sles,cn_os_ready,dns,
makedns_h                                        mn_only,dns,
makedns_n                                        os=rhels,os=sles,mn_only,dns,
makedns_n_noderange                              mn_only,dns,
makedns_nameserver_on_sn_sync_conf               cn_os_ready,dns,
makedns_nameserver_on_sn_sync_db                 os=Linux,cn_os_ready,dns,
makedns_nameserver_on_sn_sync_db_when_sn_down    os=rhels,cn_os_ready,dns,
makedns_node                                     mn_only,dns,
makedns_ubuntu_n                                 os=ubuntu,mn_only,dns,
makedns_when_nameserver_on_mn_down               os=sles,cn_os_ready,dns,
makedns_when_nameserver_on_sn_down               os=sles,cn_os_ready,dns,
```

labels of ``makedhcp``
```
makedhcp_a             os=Linux,                        //need to combine with makedhcp_a_linux
makedhcp_a_d           os=Linux,                       //need to combine with makedhcp_a_d_linux 
makedhcp_a_d_linux     mn_only,dhcp,
makedhcp_a_d_ubuntu    os=Linux,              //need to combine with makedhcp_a_d_linux 
makedhcp_a_linux       mn_only,dhcp,
makedhcp_a_ubuntu      os=Linux,              //need to combine with makedhcp_a_linux 
makedhcp_d             os=Linux,                    //need to combine with makedhcp_d_linux 
makedhcp_d_linux       mn_only,dhcp,
makedhcp_h             mn_only,dhcp,
makedhcp_help          mn_only,dhcp,
makedhcp_n             mn_only,dhcp,
```

### CODE REVIEW

**Comment by chuckbrazie** [comment]
I am out of the office until 07/16/2018.

I am out of the office until  Monday July 16.


Note: This is an automated response to your message  "Re: [xcat2/xcat-core]
add labels for makedhcp makedns xdcp xdsh makehosts command test cases
(#5367)" sent on 7/3/18 8:38:59 AM.

This is the only notification you will receive while this person is away.

**Comment by chuckbrazie** [comment]
I am out of the office until 07/16/2018.

I am out of the office until  Monday July 16.


Note: This is an automated response to your message  "[xcat2/xcat-core] add
labels for makedhcp makedns xdcp xdsh makehosts command test cases (#5367)"
sent on 7/3/18 8:36:19 AM.

This is the only notification you will receive while this person is away.

**Comment by tingtli** [comment]
@hu-weihua  it is strange that for some of makedhcp cases, their names are for ubuntu/linux, there are no labels for os=ubuntu or os=Linux. Would you please take a look ?

**Comment by chuckbrazie** [comment]
I am out of the office until 07/16/2018.

I am out of the office until  Monday July 16.


Note: This is an automated response to your message  "Re: [xcat2/xcat-core]
add labels for makedhcp makedns xdcp xdsh makehosts command test cases
(#5367)" sent on 7/4/18 1:46:18 AM.

This is the only notification you will receive while this person is away.

**Comment by hu-weihua** [comment]
After changing, the labels of test cases against makedhcp are
```
makedhcp_a                 os=Linux,cn_os_ready,dhcp,
makedhcp_a_d               os=Linux,cn_os_ready,dhcp,
makedhcp_a_d_linux         os=Linux,mn_only,dhcp,
makedhcp_a_d_ubuntu        os=ubuntu,cn_os_ready,dhcp,
makedhcp_a_linux           os=Linux,mn_only,dhcp,
makedhcp_a_ubuntu          os=ubuntu,cn_os_ready,dhcp,
makedhcp_d                 os=Linux,cn_os_ready,dhcp,
makedhcp_d_linux           os=Linux,mn_only,dhcp,
makedhcp_h                 mn_only,dhcp,
makedhcp_help              mn_only,dhcp,
makedhcp_n                 os=Linux,mn_only,dhcp,
makedhcp_remote_network    os=linux,mn_only,dhcp,
```

**Comment by chuckbrazie** [comment]
I am out of the office until 07/16/2018.

I am out of the office until  Monday July 16.


Note: This is an automated response to your message  "Re: [xcat2/xcat-core]
add labels for makedhcp makedns xdcp xdsh makehosts command test cases
(#5367)" sent on 7/4/18 6:00:12 AM.

This is the only notification you will receive while this person is away.

**Comment by chuckbrazie** [comment]
I am out of the office until 07/16/2018.

I am out of the office until  Monday July 16.


Note: This is an automated response to your message  "Re: [xcat2/xcat-core]
add labels for makedhcp makedns xdcp xdsh makehosts command test cases
(#5367)" sent on 7/4/18 6:58:10 AM.

This is the only notification you will receive while this person is away.

**Comment by hu-weihua** [comment]
related task https://github.com/xcat2/xcat2-task-management/issues/208

**Comment by chuckbrazie** [comment]
I am out of the office until 07/16/2018.

I am out of the office until  Monday July 16.


Note: This is an automated response to your message  "Re: [xcat2/xcat-core]
add labels for makedhcp makedns xdcp xdsh makehosts command test cases
(#5367)" sent on 7/5/18 2:40:55 AM.

This is the only notification you will receive while this person is away.

**Pull request merged**
