### PR TITLE
fix defect [Customer] updatenode failed against Ubuntu node #679

### PR DESCRIPTION
**Pull request by immarvin**
replace she-bang "/bin/sh" with "/bin/bash"

### CODE REVIEW

**Comment by immarvin** [comment]
FVT should carry on sufficient tests on this

**Comment by daniceexi** [comment]
@immarvin Did you cover the following two impacted scenarios in your UT? If no, you need to confirm with FVT that the scenarios has been covered by xcat automation test bucket.

* Updatenode for Ubuntu and rh
* Diskless node for Ubuntu and rh

**Comment by daniceexi** [comment]
I have reviewed the code change and agree to merge.

**Comment by immarvin** [comment]
on redhat 7.2:

[root@c910f03c05k21 ~]# cat /etc/os-release 
NAME="Red Hat Enterprise Linux Server"
VERSION="7.2 (Maipo)"
ID="rhel"
ID_LIKE="fedora"
VERSION_ID="7.2"
PRETTY_NAME="Red Hat Enterprise Linux Server 7.2 Beta (Maipo)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:redhat:enterprise_linux:7.2:beta:server"
HOME_URL="https://www.redhat.com/"
BUG_REPORT_URL="https://bugzilla.redhat.com/"

REDHAT_BUGZILLA_PRODUCT="Red Hat Enterprise Linux 7"
REDHAT_BUGZILLA_PRODUCT_VERSION=7.2
REDHAT_SUPPORT_PRODUCT="Red Hat Enterprise Linux"
REDHAT_SUPPORT_PRODUCT_VERSION="7.2 Beta"
[root@c910f03c05k21 ~]# ll /bin/sh          
lrwxrwxrwx. 1 root root 4 Sep 27 22:41 /bin/sh -> bash

on ubuntu:
generally, ``/bin/sh`` is symbol link to either ``bash`` or ``dash``,  xcatdsklspost will work when``/bin/sh`` is a symbol link to ``/bin/bash``,  it won't work when otherwise.

The only thing I need to make sure  is that ``bash`` is in the ubuntu pkglist files for diskful and diskless provision

**Comment by whowutwut** [comment]
I remember that in our instructions we asked the user to change the symlink on Ubuntu from ``/bin/sh`` pointing to ``/bin/dash`` to ``/bin/bash``.  Did we ever change that? 

For 2.12, why not just make a hard change and always make our scripts use ``/bin/bash`` instead of leaving it up to the OS default shell?

**Comment by daniceexi** [comment]
@whowutwut I decision was to use /bin/bash as shebang for all the post/postbootscripts instead of change the default /bin/sh to /bin/bash. The reason was there might be customers want to use /bin/dash instead of /bin/bash. If just arbitrarily changed link to /bin/dash, customers script may fail, even some system scripts may fail.

**Pull request merged**
