### PR TITLE
Update for test case install_xCAT_on_ubuntu

### PR DESCRIPTION
**Pull request by neo954**
This patch solve the problem mentioned in https://github.com/xcat2/xcat2-task-management/issues/225.

### CODE REVIEW

**Comment by hu-weihua** [comment]
I do not think this could resolve the problem, could you help to do the UT and  paste the UT result in the PR? thanks

**Comment by chuckbrazie** [comment]
I am out of the office until 07/16/2018.

I am out of the office until  Monday July 16.


Note: This is an automated response to your message  "[xcat2/xcat-core]
Update for test case install_xCAT_on_ubuntu (#5387)" sent on 7/10/18
8:30:27 AM.

This is the only notification you will receive while this person is away.

**Comment by chuckbrazie** [comment]
I am out of the office until 07/16/2018.

I am out of the office until  Monday July 16.


Note: This is an automated response to your message  "Re: [xcat2/xcat-core]
Update for test case install_xCAT_on_ubuntu (#5387)" sent on 7/10/18
8:35:41 AM.

This is the only notification you will receive while this person is away.

**Comment by chuckbrazie** [comment]
I am out of the office until 07/16/2018.

I am out of the office until  Monday July 16.


Note: This is an automated response to your message  "Re: [xcat2/xcat-core]
Update for test case install_xCAT_on_ubuntu (#5387)" sent on 7/10/18
8:37:16 AM.

This is the only notification you will receive while this person is away.

**Comment by chuckbrazie** [comment]
I am out of the office until 07/16/2018.

I am out of the office until  Monday July 16.


Note: This is an automated response to your message  "Re: [xcat2/xcat-core]
Update for test case install_xCAT_on_ubuntu (#5387)" sent on 7/10/18
8:36:46 AM.

This is the only notification you will receive while this person is away.

**Comment by hu-weihua** [comment]
We have got the test result against this fix, that proved **how important UT is**. 
Pasted UT result in pull request is also very important team ﻿﻿principle,
@neo954, could you follow the principle and do UT before pulling request in the future? thanks.

```
------START::install_xCAT_on_ubuntu::Time:Tue Jul 10 19:28:02 2018------

FILENAME:/opt/xcat/bin/../share/xcat/tools/autotest/testcase//install_xCAT/case0

RUN:arc_all=`uname -a`; code=`lsb_release -sc`;if [[ $arc_all =~ "ppc64le" ]]; then arch="ppc64el";else arch="x86_64";fi; cp "/opt/xcat/share/xcat/tools/autotest/testcase/go-xcat/$code-$arch.sources.list" "/etc/apt/sources.list" [Tue Jul 10 19:28:02 2018]
ElapsedTime:0 sec
RETURN rc = 0
OUTPUT:

RUN:apt-get clean;apt-get update [Tue Jul 10 19:28:02 2018]
ElapsedTime:1 sec
RETURN rc = 0
OUTPUT:
Get:1 file:/xcat-core bionic InRelease [2,568 B]
Get:2 file:/xcat-dep bionic InRelease [2,575 B]
Get:1 file:/xcat-core bionic InRelease [2,568 B]
Get:2 file:/xcat-dep bionic InRelease [2,575 B]
Hit:3 http://ports.ubuntu.com/ubuntu-ports bionic InRelease
Hit:4 http://ports.ubuntu.com/ubuntu-ports bionic-updates InRelease
Hit:5 http://ports.ubuntu.com/ubuntu-ports bionic-security InRelease
Get:6 http://ports.ubuntu.com/ubuntu-ports bionic/restricted ppc64el Packages [664 B]
Get:7 http://ports.ubuntu.com/ubuntu-ports bionic/restricted Translation-en [3,584 B]
Fetched 4,248 B in 1s (6,694 B/s)
Reading package lists...
CHECK:rc == 0	[Pass]

RUN:cp /core-*-snap.tar.bz2 /install_xCAT_xcat-core.tar.bz2 [Tue Jul 10 19:28:03 2018]
ElapsedTime:0 sec
RETURN rc = 0
OUTPUT:
CHECK:rc == 0	[Pass]

RUN:cp /xcat-dep*.tar.bz2 /install_xCAT_xcat-dep.tar.bz2 [Tue Jul 10 19:28:03 2018]
ElapsedTime:0 sec
RETURN rc = 0
OUTPUT:
CHECK:rc == 0	[Pass]

RUN:ls /go-xcat [Tue Jul 10 19:28:03 2018]
ElapsedTime:0 sec
RETURN rc = 0
OUTPUT:
/go-xcat
CHECK:rc == 0	[Pass]

RUN:chmod 777 /go-xcat; /go-xcat --xcat-core=/install_xCAT_xcat-core.tar.bz2 --xcat-dep=/install_xCAT_xcat-dep.tar.bz2  -y install; [Tue Jul 10 19:28:03 2018]
ElapsedTime:34 sec
RETURN rc = 0
OUTPUT:
Operating system:   linux
Architecture:       ppc64le
Linux Distribution: ubuntu
Version:            18.04

Reading repositories ...... done
Reading package lists...
Building dependency tree...
Reading state information...
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 xcat : Depends: libdbd-sqlite3-perl but it is not installable
        Depends: xinetd but it is not installable
        Depends: libnet-telnet-perl but it is not installable
        Recommends: bind9 but it is not going to be installed
        Recommends: tftp-hpa but it is not going to be installed
        Recommends: libsys-virt-perl but it is not installable
        Recommends: xcat-probe (= 2.14.2-snap201807100616) but it is not going to be installed
        Recommends: goconserver but it is not going to be installed
 xcat-server : Depends: libdbd-sqlite3-perl but it is not installable
               Depends: libexpect-perl but it is not installable
               Depends: libsnmp-perl but it is not installable
               Depends: libcrypt-rijndael-perl but it is not installable
               Depends: libcrypt-cbc-perl but it is not installable
               Depends: libjson-perl but it is not installable
               Depends: libnet-https-nb-perl but it is not installable
               Depends: libhttp-async-perl but it is not installable
CHECK:rc == 0	[Pass]

RUN:source "/etc/profile.d/xcat.sh";env;lsxcatd -v [Tue Jul 10 19:28:37 2018]
ElapsedTime:0 sec
RETURN rc = 1
OUTPUT:
CHECK:rc == 0	[Failed]

RUN:service xcatd status [Tue Jul 10 19:28:37 2018]
ElapsedTime:0 sec
RETURN rc = 4
OUTPUT:
Unit xcatd.service could not be found.

RUN:rm -rf /install_xCAT_xcat-core.tar.bz2 /install_xCAT_xcat-dep.tar.bz2 [Tue Jul 10 19:28:37 2018]
ElapsedTime:0 sec
RETURN rc = 0
OUTPUT:

------END::install_xCAT_on_ubuntu::Failed::Time:Tue Jul 10 19:28:37 2018 ::Duration::35 sec------
```

**Comment by chuckbrazie** [comment]
I am out of the office until 07/16/2018.

I am out of the office until  Monday July 16.


Note: This is an automated response to your message  "Re: [xcat2/xcat-core]
Update for test case install_xCAT_on_ubuntu (#5387)" sent on 7/11/18
1:36:35 AM.

This is the only notification you will receive while this person is away.

**Comment by neo954** [comment]
Tinker test cases for issue #5351

**Pull request merged**
