### PR TITLE
fix issue [fvt]2.11 rcons will stay in anaconda interface in rh7.2 ppc64le

### PR DESCRIPTION
**Pull request by immarvin**
fix issue https://github.com/xcat2/xcat-core/issues/317

### CODE REVIEW

**Comment by whowutwut** [comment]
Is this needed for the ESP build?  If so we need to get approval to integrate...

**Comment by daniceexi** [comment]
@whowutwut 
This only affects the console screen display the install process, no function impact. We can merge this after ESP build.

**Comment by immarvin** [comment]
we have found this problem in diskless provision before, refer to the [link] (http://sourceforge.net/p/xcat/bugs/4502/) for more details.

**Comment by daniceexi** [comment]
I have review the change and agree to merge.

**Pull request merged**
