### PR TITLE
MacMap: skip obtaining macmap table from switches without any port connect to switchs and pdus while discovering switch

### PR DESCRIPTION
**Pull request by immarvin**
skip obtaining macmap table from switches without any port connect to switchs and pdus while discovering switch

UT finished on boston02

### CODE REVIEW

**Comment by immarvin** [comment]
hi @cxhong , would you please take a look at this PR.

I think this PR might has some issue, we need to filter out the switches that:
1) defined in `switch` column of `switch` table
2) without any switch  connected to its ports 

seems this PR might filter  the switches with any port connected to a non-switch-or-pdu node, would you please review this PR and modify the logic if any error?

thanks

**Comment by immarvin** [comment]
oh, seems the logic is ok, confusing....

**Comment by cxhong** [comment]
I run switch-based node discovery and switch discovery, looks fine.   
I will approve this PR

**Comment by zet809** [comment]
Good to me, I agree to merge, thx!

**Comment by immarvin** [comment]
fix https://github.com/xcat2/xcat-core/issues/5527

**Pull request merged**
