### PR TITLE
Remove hostname from known_hosts file after nodes reset

### PR DESCRIPTION
**Pull request by cxhong**
Issue #516 , this fix will remove hostname from known_hosts file on the MN to avoid "man-in-the-middle attack" message after nodes reset.

### CODE REVIEW

**Comment by cxhong** [comment]
Pull request #509 will take care "updatenode -k"  problem seeing on Issue #516

**Comment by daniceexi** [comment]
@cxhong I understand your change could fix this issue through removing the original public host key for the target node, and when reconnect to the node with ssh a new host key will be created in know_hosts by default. But it depens on our current configuration that xcat mn just accept the public host key without checkout the authority.

I think a better fix is to run the makeknownhosts in the credentials.pm to regenerate the correct entry in the 'known_hosts' file. **BUT** since this rewrite of known_hosts happens for each node when install a banch of nodes, there may be conflict for multiple processes to wirte konwn_hosts file. At least the performance will be impacted.

Then whether require user to run 'makeknowhosts' manually is an acceptable solution?

**Comment by cxhong** [comment]
Actually updatenode -k is another options to modify  known_host file after node provisioned.  pull request #509 had fixes for "updatenode -k".  User has to manually run it.

**Comment by daniceexi** [comment]
@cxhong 'updatenode -k' does work because it calls the 'makeknownhosts' internally. 
I recommend we don't fix this issue, but tell user to run 'makeknownhosts' command to fix it.

**Comment by cxhong** [comment]
Actually, the root cause for this issue was the file '/etc/ssh/ssh_host_ecdsa_key' was NOT existed when running remoteshell postscripts.  we will use ssh-keygen command to figure out the compute node is supporting 'ecdsa' instead of by checking the existing of file '/etc/ssh/ssh_host_ecdsa_key'.

**Comment by daniceexi** [comment]
I have reviewed this change and agree to merge. @cxhong Thanks for your fix.

**Comment by whowutwut** [comment]
This pull request attempted to address issue #280 but looks like it does not.  Re-opened that issue

**Pull request merged**
