### PR TITLE
Refactor Infiniband Documentation (do not merge)

### PR DESCRIPTION
**Pull request by whowutwut**
This pull request is being used to revisit the process for users to configure the IB support in xCAT.
The attempt is to simplify the process and instruction set for the normal use case.

### CODE REVIEW

**Comment by whowutwut** [comment]
I'd like to get rid of the v1 and v2 concept for 2.12.  I think if we think version2 should be used moving forward, people can still obtain version1 by looking at the source tree... we don't need to ship it. Having these two versions is confusing.  @hu-weihua  What levels of OFED do we use with v1 vs v2?

**Comment by hu-weihua** [comment]
@whowutwut, I rewrote the InfiniBand docs recently. At first I just want to fix 2 bugs(#549 and #505), but I found the doc was not convenient to cover new scenarios, so I almost rewrote InfiniBand drivers installation part, and also add 2 new pages to list ``The Scenarioes Have Been Verified`` and ``Known Issues``.  The related pull request is #912.  @neo954 has reviewed first round.  I did simplify the process and instruction, but I am not sure it's good enough for you. Maybe you can review again and give me your comments.  

I agree to get rid of v1. We kept it before just worry some customer was using it. but up to now we didn't get any feedback for v1, I suppose no customer are using it now.

**Comment by hu-weihua** [comment]
@whowutwut, In the new page ``The Scenarioes Have Been Verified`` I list the certain OFED version and attributes in every scenario. But this list just covers the latest scenarios I have verified(``rhels7.2+ppc64le``  ``ubuntu14.4.3+ppc64le``....),  Some scenario we had ever verified long time ago isn't contained in this list for I lost such information, we can verify again these old scenarios (for example rhels6+x86) and complete this list. But I think maybe no customer care about these old scenario. We can list all the scenarios we think we should list, and do some verify again.

**Comment by whowutwut** [comment]
Closing this pull request.

**Pull request closed without merging**
