### PR TITLE
Fix gmond

### PR DESCRIPTION
**Pull request by omula**
### The modification include

_##Replace init.d calls with systemd ones_

_##Fix indent postscript confGang_

_##Automatic generation of default configuration in postscript_

_##Simplified postscript confGang_

### CODE REVIEW

**Comment by besawn** [comment]
@omula, thanks for your interest in the xCAT project! 

Does this pull request contain fixes for an issue that you have encountered while you are using xCAT?

**Comment by omula** [comment]
@besawn  gangliamon is broken as linux systems no longer use init.d. Therefore I replaced the calls to init.d for systemctl calls.
I also took advantage to rewrite the postscript as it was creating multiple temporary files which are not needed if one uses sed -i and fixed some replacement as it was not working.

**Comment by besawn** [comment]
@omula Do you have some test cases and results related to this pull request that you can share that help to highlight what effect these changes have in your environments? What versions of xCAT are running? Which OS versions and architectures?

**Comment by omula** [comment]
OS: CentOS Linux release 7.6.1810 (Core)
Arch: x86_64
xCAT version: xCAT-server-2.14.6-snap201903290319.noarch

One of the changes produces this message a part from the creation of a default gmond.conf file.
```
/var/log/xcat/cluster.log-20190922-1569116641.gz:Sep 18 19:07:17 node04 xcat: WARNING  gmond configuration file not found
/var/log/xcat/cluster.log-20190922-1569116641.gz:Sep 18 20:36:10 node01 xcat: WARNING  gmond configuration file not found. Generating a default one
```
The command used to generate the default configuration is provided by gmond itself.
https://linux.die.net/man/1/gmond

Before change
```
# monstart gangliamon -r
sms01.xcat.local: node01: bash: /etc/init.d/gmond: No such file or directory
node02: bash: /etc/init.d/gmond: No such file or directory
node03: bash: /etc/init.d/gmond: No such file or directory
```

After change
```
# monstart gangliamon 
sms01.xcat.local: started
```

**Comment by omula** [comment]
@besawn have I provided enough information?
do you need anything else from my side?

**Comment by besawn** [comment]
@omula Before I can merge this pull request, we require all xCAT contributors to sign a contributor's license agreement: https://xcat-docs.readthedocs.io/en/stable/developers/license/contributors.html

Can you review the license agreement and submit a signed copy to become a formal xCAT contributor?

**Comment by omula** [comment]
@besawn we sent yesterday the signed agreement.

**Comment by cxhong** [comment]
@omula , thanks.  I added to our list.

**Pull request merged**
