### PR TITLE
refine doc for mkdef --template

### PR DESCRIPTION
**Pull request by immarvin**
for https://github.com/xcat2/xcat-core/issues/5246

see doc in http://10.3.5.21/xcat-doc/html/guides/admin-guides/manage_clusters/ppc64le/discovery/manually_define.html , http://10.3.5.21/xcat-doc/html/guides/admin-guides/manage_clusters/ppc64le/diskful/copy_image.html , http://10.3.5.21/xcat-doc/html/guides/admin-guides/manage_clusters/ppc64le/diskless/copy_image.html

### CODE REVIEW

**Comment by chuckbrazie** [comment]
I am out of the office until 07/16/2018.

I am out of the office until  Monday July 16.


Note: This is an automated response to your message  "[xcat2/xcat-core]
refine doc for mkdef --template (#5372)" sent on 7/4/18 9:04:46 AM.

This is the only notification you will receive while this person is away.

**Comment by chuckbrazie** [comment]
I am out of the office until 07/16/2018.

I am out of the office until  Monday July 16.


Note: This is an automated response to your message  "Re: [xcat2/xcat-core]
refine doc for mkdef --template (#5372)" sent on 7/4/18 9:13:51 AM.

This is the only notification you will receive while this person is away.

**Comment by neo954** [comment]
The patch looks good. I will merge this one.

**Comment by chuckbrazie** [comment]
I am out of the office until 07/16/2018.

I am out of the office until  Monday July 16.


Note: This is an automated response to your message  "Re: [xcat2/xcat-core]
refine doc for mkdef --template (#5372)" sent on 7/5/18 7:01:21 AM.

This is the only notification you will receive while this person is away.

**Comment by chuckbrazie** [comment]
I am out of the office until 07/16/2018.

I am out of the office until  Monday July 16.


Note: This is an automated response to your message  "Re: [xcat2/xcat-core]
refine doc for mkdef --template (#5372)" sent on 7/5/18 8:22:47 AM.

This is the only notification you will receive while this person is away.

**Pull request merged**
