### PR TITLE
Do not update bootparams table when running nodeset

### PR DESCRIPTION
**Pull request by chenglch**
With the nytprof tool, the buttleneck is the time to update the bootparams
table.To optimize the performance on large scale nodes, this patch tranfer
the bootparams hash through variable reference.

posible impact: getdestiny can not get the information about bootparams.

partial-issue: #2024

### CODE REVIEW

**Comment by immarvin** [comment]
agree to merge to start verification ASAP

**Comment by immarvin** [comment]
hi @whowutwut , would you please add the auto daily build of this branch in the build server?

**Comment by Obihoernchen** [comment]
Now new nodes don't have the following entries
```
kcmdline
kernel?
initrd
```
only addkcmdline.

Are kcmdline, kernel and initrd obsolete now?

**Comment by chenglch** [comment]
@Obihoernchen , yes, they will not be updated.

**Pull request merged**
