### PR TITLE
Get username and password from passwd table for openbmc discover

### PR DESCRIPTION
**Pull request by xuweibj**
#3036 

1. Define default username and password value for node with openbmc mgt.
2. Get username and password defined in passwd table.
3. If there is no openbmc in passwd table, use default value. Or use value in passwd(even empty).
4. Use ``openbmcusername`` and ``openbmcpassword`` in bmcdiscovery_openbmc function.

### CODE REVIEW

**Comment by zet809** [comment]
Looks good to me

**Comment by whowutwut** [comment]
delegate review to @cxhong  , can you review this code ?

**Comment by cxhong** [comment]
will this option also work for openbmc?
```
push @{ $rsp->{data} }, "\tDisplay the BMC IP configuration:\n";
    push @{ $rsp->{data} }, "\t\tbmcdiscover [-u bmc_user] [-p bmc_passwd] -i bmc_ip --ipsource";
````
if it is, the bmc_user and bmc_passwd will be incorrect if  get from passwd table.

**Comment by xuweibj** [comment]
@cxhong ， currently, bmcdiscover for openbmc did not support ``ipsource`` and ``check`` options.

**Comment by xuweibj** [comment]
Hi @cxhong , do you have any other comments for this pull request? Or could you help to merge it?

**Comment by whowutwut** [comment]
@xuweibj  I think we should be able to put in the code for ipsource option, even though it's not implemented yet, because the interface has been defined.  I think it might be `DHCPEnabled` here.. https://github.com/openbmc/phosphor-dbus-interfaces/blob/master/xyz/openbmc_project/Network/EthernetInterface.interface.yaml  

If the API is not clear, we need to bring it up to openbmc team.  

for `check` we can also try to login with the credentials.  It doesn't tell us what is wrong, but it does not authenticate if incorrect credentials. 
```
[root@stratton01 ~]# curl -c cjar -b cjar -k -H "Content-Type: application/json" -X POST https://10.6.9.254/login -d "{\"data\": [ \"abc\", \"invalid\" ] }"
{
  "data": {
    "description": "Invalid username or password"
  },
  "message": "401 Unauthorized",
  "status": "error"
```

**Comment by xuweibj** [comment]
@whowutwut , I think the problem is not because of API. 
For options ``check`` and ``ipsource``, currently we use ipmitool-xcat command. If we want to support openbmc, we must check whether the node is openbmc. If openbmc we use restful, if not use ipmitool. So that we must add judgement in function for these options or restructure code. So we decide support them later.

**Pull request merged**
