### PR TITLE
Revert pull request #5358. Since it cause some side effects.

### PR DESCRIPTION
**Pull request by neo954**
Revert pull request #5358. Since it cause some side effects.

This reverts commit dc2ea9014d1d4e7932104159417f6335cea5fac7.

### CODE REVIEW

**Comment by neo954** [comment]
See #5365.

**Comment by chuckbrazie** [comment]
I am out of the office until 07/16/2018.

I am out of the office until  Monday July 16.


Note: This is an automated response to your message  "Re: [xcat2/xcat-core]
Revert pull request #5358. Since it cause some side effects. (#5364)" sent
on 7/3/18 8:09:44 AM.

This is the only notification you will receive while this person is away.

**Comment by chuckbrazie** [comment]
I am out of the office until 07/16/2018.

I am out of the office until  Monday July 16.


Note: This is an automated response to your message  "[xcat2/xcat-core]
Revert pull request #5358. Since it cause some side effects. (#5364)" sent
on 7/3/18 7:57:53 AM.

This is the only notification you will receive while this person is away.

**Comment by chuckbrazie** [comment]
I am out of the office until 07/16/2018.

I am out of the office until  Monday July 16.


Note: This is an automated response to your message  "Re: [xcat2/xcat-core]
Revert pull request #5358. Since it cause some side effects. (#5364)" sent
on 7/3/18 8:00:32 AM.

This is the only notification you will receive while this person is away.

**Comment by chuckbrazie** [comment]
I am out of the office until 07/16/2018.

I am out of the office until  Monday July 16.


Note: This is an automated response to your message  "Re: [xcat2/xcat-core]
Revert pull request #5358. Since it cause some side effects. (#5364)" sent
on 7/3/18 8:11:44 AM.

This is the only notification you will receive while this person is away.

**Comment by chuckbrazie** [comment]
I am out of the office until 07/16/2018.

I am out of the office until  Monday July 16.


Note: This is an automated response to your message  "Re: [xcat2/xcat-core]
Revert pull request #5358. Since it cause some side effects. (#5364)" sent
on 7/3/18 8:11:06 AM.

This is the only notification you will receive while this person is away.

**Pull request merged**
