### PR TITLE
Refactor the GPU CUDA documentation.

### PR DESCRIPTION
**Pull request by whowutwut**
Organized for both RHEL and Ubuntu sharing common pages.  Made sure the documentation
reflects the chanages made for diskless support in Issue #314 and Issue #316

I think we should just merge this to allow the testing team to reun through the steps for verification

### CODE REVIEW

**Comment by whowutwut** [comment]
@penguhyang  can you take a look at the Ubuntu section to make sure the content is still all there?

**Comment by daniceexi** [comment]
@whowutwut I added two comments and could you offer me a local access to your web server to review this change?

**Comment by whowutwut** [comment]
@daniceexi  Sorry, I forgot to add it, the version is here. I'm going to refresh it with your two comments and will be updated in a few minutes.   http://10.2.5.2/cuda_doc/advanced/gpu

**Comment by daniceexi** [comment]
@whowutwut 
I think we can make this part to be common for rh and ubuntu

**Comment by daniceexi** [comment]
I have reviewed the change and agree to merge.

**Pull request merged**
