### PR TITLE
Postscripts prep

### PR DESCRIPTION
**Pull request by samveen**
Clean up in perl-xCAT/xCAT/DBobjUtils.pm in prep for work on #115

### CODE REVIEW

**Comment by daniceexi** [comment]
I have reviewed the change and agree to check in.

**Comment by daniceexi** [comment]
@samveen Did you use certain tool to help the correcting of the format?

**Comment by samveen** [comment]
@daniceexi : This was all Vim macro based shortcuts. However, I've been considering the use of perl-tidy, but am concerned about the way the comments are spread out in the code. What's your take on it?

**Comment by daniceexi** [comment]
@samveen We did not use any tool to handle the format, we we did was by hand.

**Pull request merged**
