### PR TITLE
fix routeop does not use xcatlib.sh for issue 3359

### LINKED ISSUE #3359: Incorrect `sourcing` of xcatlib.sh by postscripts
I get the following error while running `makeroutes` with `xCAT-2.13.2`

```
[VN samveen@xcatmn1 ~]$ makeroutes kvm2
kvm2: Adding temporary route: route add -net 0.0.0.0 netmask 0.0.0.0 gw 10.0.16.1
kvm2: Persistent route "any net 0.0.0.0 netmask 0.0.0.0 gw 10.0.16.1 ens1f0" added in /etc/sysconfig/static-routes.
kvm2: /tmp/filerG6a4O.dsh: line 29: /tmp/xcatlib.sh: No such file or directory
kvm2: Adding temporary route: route add -net 0.0.0.0 netmask 0.0.0.0 gw 10.0.16.1
kvm2:   error code=7, result=SIOCADDRT: File exists.
kvm2: Persistent route "any net 0.0.0.0 netmask 0.0.0.0 gw 10.0.16.1 ens2f0" added in /etc/sysconfig/static-routes.
kvm2: /tmp/file9XVAFK.dsh: line 29: /tmp/xcatlib.sh: No such file or directory
kvm2: Adding temporary route: route add -net 0.0.0.0 netmask 0.0.0.0 gw 10.0.16.1
kvm2:   error code=7, result=SIOCADDRT: File exists.
kvm2: Persistent route "any net 0.0.0.0 netmask 0.0.0.0 gw 10.0.16.1 eno49" added in /etc/sysconfig/static-routes.
kvm2: /tmp/fileJogT0G.dsh: line 29: /tmp/xcatlib.sh: No such file or directory
[VN samveen@xcatmn1 ~]$ lsxcatd  -v 
Version 2.13.2 (git commit dab564dd7f23cb8bc46119f11d235de33c57802a, built Wed Feb 22 22:42:07 EST 2017)
```

I believe it has something to do with the fact that most postscripts include xcatlib.sh as below:

```
if [ "$(uname -s|tr 'A-Z' 'a-z')" = "linux" ];then
   str_dir_name=`dirname $0`
   . $str_dir_name/xcatlib.sh
fi
```

### PR DESCRIPTION
**Pull request by bybai**
fix #3359 
routeop does not use xcatlib.sh, and routeop is called by makeroutes.

### CODE REVIEW

**Comment by daniceexi** [comment]
@bybai two questions:
* is it working before?
* what's the route cause that we encountered this problem?

**Comment by bybai** [comment]
Hi @daniceexi ,

**Comment by bybai** [comment]
Hi @daniceexi && @immarvin , `makeroutes` should be executed in MN and CN, so `routeop` should find xcatlib.sh in MN or CN, I enhanced code, please review.

**Comment by immarvin** [comment]
hi @bybai , since the error message is caused by inexistence of  ``xcatlib.sh`` while sourcing, I think the PR will not eliminate the error messages and will introduce more error messages

**Comment by immarvin** [comment]
agree to merge

**Pull request merged**
