### PR TITLE
fix defect  [DEV] the format of "ubuntu/genimage" need to be refined #715 

### PR DESCRIPTION
**Pull request by immarvin**
fix defect https://github.com/xcat2/xcat-core/issues/715

1.    indent the code with ``perltidy -w -syn -g -opt -i=4 -nt -io -nbbc -kbl=2 -pscf=-c -aws -pt=2 -bbc ./genimage`` 
 2.   indent manually for the lines not processed in step#1 3.remove the code commented out

### CODE REVIEW

**Comment by whowutwut** [comment]
Sorry, I missed this email notification. Is the only change here perl tidy? 

The changes are too large to see the diff..so I don't know how to review...

if it's only the format change using perltidy, maybe it's okay to merge in for 2.12 GA. What do you think @daniceexi @tingtli ?

**Comment by daniceexi** [comment]
It may safe. But my idea is we should follow the rule that to consider the code safe before the release, the unnecessary checkin should be postponed to next release.

**Comment by whowutwut** [comment]
Ok, if we leave this pull request...  then the master will be 2.13... moving to 2.13...

**Comment by daniceexi** [comment]
@whowutwut It should be 2.12.1, right? We don't plan for 2.13 now.

**Comment by whowutwut** [comment]
Yes, 2.12.1, @immarvin sorry for the delay here ,but I think you might need to resolve the conflicts or re-create the pull request with the perl tidy..

**Comment by immarvin** [comment]
hi @whowutwut ,since ``ubuntu/genimage`` has been changed a lot and this PR has expired, I will close this PR and create a new one later

**Pull request closed without merging**
