### PR TITLE
Fix regex issue that duplicate the node name

### PR DESCRIPTION
**Pull request by chenglch**
close-issue: #2582

### CODE REVIEW

**Comment by whowutwut** [comment]
@chenglch can you paste the output of the following with the changes that you made in the description? 

```
# mkdef -t group -o doubletrouble bmc='|\z|-imm|' mgt=ipmi
# mkdef mgt02 groups=doubletrouble
# lsdef mgt02 -i bmc
Object name: mgt02
    bmc=mgt02mgt02-imm
```

The lsdef at the end should be correct...

**Comment by chenglch** [comment]
```
root@c910f05c01bc01k10:~# mkdef -t group -o doubletrouble bmc='|\z|-imm|' mgt=ipmi
Warning: Cannot determine a member list for group 'doubletrouble'.
1 object definitions have been created or modified.
root@c910f05c01bc01k10:~# mkdef mgt02 groups=doubletrouble
1 object definitions have been created or modified.
root@c910f05c01bc01k10:~# lsdef mgt02 -i bmc
Object name: mgt02
    bmc=mgt02-imm
```

**Comment by zet809** [comment]
The modification looks good to me. But we need to add test cases for issue #2582. @tingtli Will you pls help to do that? Thx!

**Comment by zet809** [comment]
The fix looks good to me, I agree to merge. The defect #2582 have testcase_required label to trace  adding test cases for this issue.

**Pull request merged**
