### PR TITLE
Contributing CLA and guidelines added to the xcat-core project

### PR DESCRIPTION
**Pull request by whowutwut**
Created a CONTRIBUTING.md page at the base xcat-core directory to describe the contributing agreements and processes.  The CLA files are stored in the xcat-core/docs subdirectory. 

Once this is in place, it might be a good idea to remove from the docs developer sections r provide a link to the CONTRIBUTING.md page. (or leave it in both places)

### CODE REVIEW

**Comment by whowutwut** [comment]
@daniceexi  Can you take a look at this xCAT maintainers.md,  I'm not sure if that was created a long time ago but the process of emailing each pull request seems like something that's not being done today...

**Comment by daniceexi** [comment]
@whowutwut 

I think your were talking about this part:

* Create a log entry with intellectual property information about the contribution & contributor. Each log entry should contain the information below, and should be posted to xcat-legal@lists.sourceforge.net:

Right, we did not do that (make a checkin log and email to  xcat-legal@lists.sourceforge.net) when we were in sourceforge.

I think this Clause is trying to log every change which contributed by contributor. But our current code checkin procedure in github is the reviewer will merge the code. That means reviewer always checks in other's code.

But I think it's not a problem now when we using github since for each merge we have the log in the pull request page, that's evidence that the code is make by contributor, the reviewer just do the merge.

@ligc Any idea?

**Comment by whowutwut** [comment]
@daniceexi  yes, that's the section I am talking about...  You are right, since it's tracked by GitHub, we don't need to send separate emails logging the pull requests. 

I think maybe it's okay to remove lines 17-32 in the maintainers.md file

**Comment by daniceexi** [comment]
@ligc 

What's your opinion?

**Comment by whowutwut** [comment]
Based on our discussion this morning we are in agreement to remove the lines 17-32 in the maintainers file.  Just committed that into the pull request

**Comment by daniceexi** [comment]
I am good with the change.

**Pull request merged**
